import Link from "next/link";
import { FormulaDemo } from "../formula-demo";
import { SiteCompositionDemo } from "../site-composition-demo";
import { BalanceMatrixDemo } from "../balance-matrix-demo";
import { BatchCalculationDemo } from "../batch-calculation-demo";
import { AppHeader, PageContainer } from "@/components/site/app-header";

const comparisonSteps = [
  ["Add recipes", "Load saved recipes, add the current calculator recipe, or start with a blank scenario. A comparison supports up to four scenarios."],
  ["Choose a baseline", "Set the reference scenario used for signed mass and percentage differences. Changing the baseline changes only the comparison reference."],
  ["Review the same calculation outputs", "Each scenario is calculated by the same chemistry engine used in Calculator. Invalid scenarios remain visible with their validation details."],
  ["Export or print", "Save the comparison locally, export its JSON record, or print the comparison summary and precursor matrix."],
] as const;

const emiSteps = [
  ["Import measurements", "Add Keysight complex S-parameter CSV files. Parsing and analysis stay in the browser."],
  ["Confirm sample inputs", "Review direction, sample identity, thickness, optional areal density, and four-point-probe resistance readings."],
  ["Inspect calculated quantities", "MAXCalc reports R, T, A, SET, SER, and SEA from the imported complex S-parameters. A is calculated as 1 - R - T."],
  ["Review and export", "Check validation messages, compare replicates or groups, create publication figures, and export the plotted data with the project record."],
] as const;

function Workflow({ items }: Readonly<{ items: readonly (readonly [string, string])[] }>) {
  return <ol className="mt-4 grid gap-3 md:grid-cols-2">{items.map(([title, description], index) => <li className="rounded border bg-slate-50 p-3" key={title}><div className="flex items-start gap-3"><span className="inline-grid h-7 w-7 flex-none place-items-center rounded-full bg-slate-900 text-sm font-bold text-white">{index + 1}</span><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-700">{description}</p></div></div></li>)}</ol>;
}

export default function DemoPage() {
  return <>
    <AppHeader activeSection="other" status="Workflows, definitions, and calculation references" title="Documentation" contextualActions={<Link className="ui-button ui-button-compact" href="/workspace">Calculator</Link>} />
    <main><PageContainer className="space-y-4 py-4" width="comparison">
      <section aria-labelledby="documentation-title" className="rounded-lg border bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-widest text-teal-700">MAXCalc documentation</p><h1 className="mt-2 text-2xl font-semibold tracking-tight" id="documentation-title">Workflows and calculation references</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-700">Use this page to understand what each workspace accepts, calculates, and exports. Scientific inputs are not shared between workspaces unless you explicitly add or import them.</p><nav aria-label="Documentation sections" className="mt-4 flex flex-wrap gap-2"><a className="ui-button ui-button-compact" href="#comparison">Comparison</a><a className="ui-button ui-button-compact" href="#emi-analysis">EMI Analysis</a><a className="ui-button ui-button-compact" href="#calculation-references">Calculation references</a></nav></section>
      <section className="rounded-lg border bg-white p-5 shadow-sm" id="comparison"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-widest text-teal-700">Workspace guide</p><h2 className="mt-1 text-xl font-semibold">Comparison</h2></div><Link className="ui-button ui-button-compact" href="/compare">Open Comparison</Link></div><p className="mt-3 max-w-4xl text-sm leading-6 text-slate-700">Comparison evaluates several recipe setups side by side without changing their saved source records. It is intended for checking precursor choices, target mass, validation status, final weighing totals, and differences relative to one selected baseline.</p><Workflow items={comparisonSteps} /><div className="mt-4 grid gap-3 lg:grid-cols-3"><article className="rounded border p-3"><h3 className="font-semibold">Standard mode</h3><p className="mt-1 text-sm leading-6 text-slate-700">Shows the main weighing results and the differences needed for routine route selection.</p></article><article className="rounded border p-3"><h3 className="font-semibold">Advanced mode</h3><p className="mt-1 text-sm leading-6 text-slate-700">Adds detailed chemistry, diagnostic, and descriptor information when it is available.</p></article><article className="rounded border p-3"><h3 className="font-semibold">Interpretation</h3><p className="mt-1 text-sm leading-6 text-slate-700">A smaller mass difference does not establish experimental equivalence. Confirm purity, material form, hazards, and processing requirements separately.</p></article></div></section>
      <section className="rounded-lg border bg-white p-5 shadow-sm" id="emi-analysis"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-widest text-teal-700">Workspace guide</p><h2 className="mt-1 text-xl font-semibold">EMI Analysis</h2></div><Link className="ui-button ui-button-compact" href="/emi">Open EMI Analysis</Link></div><p className="mt-3 max-w-4xl text-sm leading-6 text-slate-700">EMI Analysis converts complex two-port S-parameter measurements into shielding quantities while preserving the imported measurements, metadata, validation results, and plotting settings in a local project.</p><Workflow items={emiSteps} /><div className="mt-4 overflow-x-auto"><table className="min-w-full border-collapse text-sm"><caption className="mb-2 text-left font-semibold">Reported quantities</caption><thead><tr><th className="border p-2 text-left">Quantity</th><th className="border p-2 text-left">Definition</th><th className="border p-2 text-left">Use</th></tr></thead><tbody><tr><th className="border p-2 text-left">R, T, A</th><td className="border p-2">Power reflection, transmission, and absorption coefficients</td><td className="border p-2">Power balance and shielding contribution review</td></tr><tr><th className="border p-2 text-left">SET</th><td className="border p-2">Total shielding effectiveness in dB</td><td className="border p-2">Overall attenuation of transmitted power</td></tr><tr><th className="border p-2 text-left">SER, SEA</th><td className="border p-2">Reflection and effective absorption contributions in dB</td><td className="border p-2">Contribution-level interpretation under the implemented convention</td></tr><tr><th className="border p-2 text-left">Simon estimate</th><td className="border p-2">Conductivity and thickness based theoretical estimate</td><td className="border p-2">Context only. It is not a measured VNA result.</td></tr></tbody></table></div><aside className="mt-4 border-l-4 border-amber-500 bg-amber-50 p-3 text-sm leading-6 text-amber-950"><strong>Measurement review:</strong> Validation warnings identify mathematical or data-quality concerns. They do not identify a single experimental cause. Review calibration, fixture setup, reference planes, instrument drift, and source-file integrity before accepting or rejecting a measurement.</aside></section>
      <section className="rounded-lg border bg-white p-5 shadow-sm" id="calculation-references"><p className="text-xs font-semibold uppercase tracking-widest text-teal-700">Interactive references</p><h2 className="mt-1 text-xl font-semibold">Calculator methods</h2><p className="mt-2 text-sm leading-6 text-slate-700">These examples expose the same parsing and balancing concepts used by the Calculator workspace.</p><FormulaDemo /><SiteCompositionDemo /><BalanceMatrixDemo /><BatchCalculationDemo /></section>
    </PageContainer></main>
  </>;
}
