import { compositionsEqualExact } from "./composition";
import { buildElementBalanceMatrix, type ElementBalanceMatrix } from "./balance-matrix";
import { parseFormula } from "./formula-parser";
import { solvePrecursorBalance, type PrecursorSolverResult } from "./precursor-solver";
import type { BalancePrecursorDefinition, ElementalComposition, SiteComposition } from "./schemas";
import { siteCompositionToElementalComposition } from "./site-composition";
import { elementPrecursorEligibility } from "./element-precursor-eligibility";

export type PrecursorValidationStatus = "lab-approved" | "spreadsheet-matched" | "hand-audited" | "source-verified" | "registered" | "synthetic" | "deprecated";
export type PrecursorSuggestionSource = "saved-route" | "built-in-route" | "generic-candidate" | "elemental-fallback";
export interface RegisteredPrecursorDefinition extends BalancePrecursorDefinition { readonly validationStatus?: PrecursorValidationStatus; readonly defaultPurityPercent?: string }
export interface RegisteredPrecursorRoute { readonly id: string; readonly name: string; readonly target: ElementalComposition | SiteComposition; readonly precursorIds: readonly string[]; readonly validationStatus: PrecursorValidationStatus; readonly sourceType?: "saved-route" | "built-in-route"; readonly sourceRouteRevisionId?: string }
export interface PrecursorSuggestionOptions { readonly maximumSuggestions?: number; readonly maximumCandidatePrecursors?: number; readonly maximumSearchCandidates?: number }
export interface PrecursorSuggestionDiagnostic { readonly code: "NO_CANDIDATE_ROUTE_FOUND" | "REQUIRED_ELEMENT_ABSENT_FROM_PRECURSOR_REGISTRY" | "ELEMENT_REQUIRES_EXPLICIT_PRECURSOR" | "ATOMIC_WEIGHT_UNAVAILABLE" | "GENERIC_ELEMENTAL_FALLBACK_DISALLOWED" | "CANDIDATE_SOLVER_INFEASIBLE" | "CANDIDATE_INTRODUCES_NON_TARGET_ELEMENTS" | "CANDIDATE_UNDERDETERMINED" | "CANDIDATE_SEARCH_LIMIT_REACHED"; readonly severity: "warning"; readonly message: string; readonly candidateId?: string; readonly element?: string }
export interface PrecursorRouteSuggestion { readonly candidateId: string; readonly name: string; readonly precursorIds: readonly string[]; readonly precursorFormulas: readonly string[]; readonly precursors: readonly RegisteredPrecursorDefinition[]; readonly sourceType: PrecursorSuggestionSource; readonly validationStatus: PrecursorValidationStatus; readonly matrixStatus: "consistent"; readonly solverStatus: PrecursorSolverResult["status"]; readonly solverQuantities: PrecursorSolverResult["exactQuantitiesByPrecursorId"]; readonly introducedNonTargetElements: readonly string[]; readonly warnings: readonly PrecursorSuggestionDiagnostic[]; readonly explanation: string; readonly priority: Readonly<{ sourceRank: number; validationRank: number; precursorCount: number; stableKey: string }>; readonly sourceRouteId?: string; readonly sourceRouteRevisionId?: string }
export interface PrecursorSuggestionResult { readonly suggestions: readonly PrecursorRouteSuggestion[]; readonly diagnostics: readonly PrecursorSuggestionDiagnostic[]; readonly candidatesExamined: number; readonly candidateLimit: number; readonly limitReached: boolean }
export interface PrecursorRouteAssessment { readonly usable: boolean; readonly matrix?: ElementBalanceMatrix; readonly solver?: PrecursorSolverResult; readonly missingElements: readonly string[]; readonly introducedNonTargetElements: readonly string[]; readonly underdetermined: boolean }

const VALIDATION_RANK: Readonly<Record<PrecursorValidationStatus, number>> = Object.freeze({ "lab-approved": 0, "spreadsheet-matched": 1, "hand-audited": 2, "source-verified": 3, registered: 4, synthetic: 5, deprecated: 6 });
function targetComposition(target: ElementalComposition | SiteComposition): ElementalComposition | undefined { if ("amounts" in target) return target; const converted = siteCompositionToElementalComposition(target); return converted.success ? converted.value : undefined }
function precursorComposition(precursor: RegisteredPrecursorDefinition): ElementalComposition | undefined { if (precursor.composition) return precursor.composition; if (!precursor.formula) return undefined; const parsed = parseFormula(precursor.formula); return parsed.success ? parsed.composition : undefined }

export function assessPrecursorRoute(target: ElementalComposition | SiteComposition, precursors: readonly RegisteredPrecursorDefinition[]): PrecursorRouteAssessment {
  const composition = targetComposition(target);
  if (!composition) return Object.freeze({ usable: false, missingElements: Object.freeze([]), introducedNonTargetElements: Object.freeze([]), underdetermined: false });
  const supplied = new Set(precursors.flatMap((item) => Object.keys(precursorComposition(item)?.amounts ?? {})));
  const missingElements = Object.freeze(Object.keys(composition.amounts).filter((element) => !supplied.has(element)));
  const matrixResult = buildElementBalanceMatrix(target, precursors);
  if (!matrixResult.success) return Object.freeze({ usable: false, missingElements, introducedNonTargetElements: Object.freeze([]), underdetermined: false });
  const matrix = matrixResult.value;
  const solver = solvePrecursorBalance(matrix);
  const usable = missingElements.length === 0 && matrix.analysis.rankConsistency === "consistent" && (solver.status === "exact-unique" || solver.status === "exact-multiple");
  return Object.freeze({ usable, matrix, solver, missingElements, introducedNonTargetElements: Object.freeze(solver.precursorOnlyIntroducedElements.map((item) => item.element)), underdetermined: matrix.dimensionClassification === "underdetermined" || solver.status === "exact-multiple" });
}

function routeKey(ids: readonly string[]): string { return [...ids].sort().join("|") }
function elementalFor(element: string, registry: readonly RegisteredPrecursorDefinition[]): RegisteredPrecursorDefinition | undefined { return registry.find((item) => { const amounts = precursorComposition(item)?.amounts; return amounts && Object.keys(amounts).length === 1 && amounts[element] !== undefined }) }
function validationFor(items: readonly RegisteredPrecursorDefinition[]): PrecursorValidationStatus { return items.reduce<PrecursorValidationStatus>((worst, item) => VALIDATION_RANK[item.validationStatus ?? "registered"] > VALIDATION_RANK[worst] ? item.validationStatus ?? "registered" : worst, "lab-approved") }

function generatedElemental(element: string): RegisteredPrecursorDefinition | undefined {
  const eligibility = elementPrecursorEligibility(element);
  if (eligibility.genericElementalFallback !== "allowed") return undefined;
  return Object.freeze({ schemaVersion: "1.0.0", id: `generic-element-${element.toLowerCase()}`, name: `${eligibility.elementName ?? element} (generic elemental identity)`, formula: element, validationStatus: "synthetic" });
}

export function suggestPrecursorRoutes(target: ElementalComposition | SiteComposition, precursorRegistry: readonly RegisteredPrecursorDefinition[], savedRoutes: readonly RegisteredPrecursorRoute[] = [], options: PrecursorSuggestionOptions = {}): PrecursorSuggestionResult {
  const maximumSuggestions = Math.max(1, options.maximumSuggestions ?? 8), maximumCandidatePrecursors = Math.max(1, options.maximumCandidatePrecursors ?? 12), candidateLimit = Math.max(1, options.maximumSearchCandidates ?? 64);
  const diagnostics: PrecursorSuggestionDiagnostic[] = [], composition = targetComposition(target);
  if (!composition) { const invalidDiagnostic: PrecursorSuggestionDiagnostic = { code: "NO_CANDIDATE_ROUTE_FOUND", severity: "warning", message: "The target composition is invalid, so precursor candidates cannot be generated." }; return Object.freeze({ suggestions: Object.freeze([]), diagnostics: Object.freeze([invalidDiagnostic]), candidatesExamined: 0, candidateLimit, limitReached: false }); }
  const required = Object.keys(composition.amounts), generated: RegisteredPrecursorDefinition[] = [];
  for (const element of required) {
    if (precursorRegistry.some((item) => precursorComposition(item)?.amounts[element] !== undefined)) continue;
    const eligibility = elementPrecursorEligibility(element), fallback = generatedElemental(element);
    if (fallback) { generated.push(fallback); continue; }
    if (!eligibility.atomicWeightAvailable) diagnostics.push(Object.freeze({ code: "ATOMIC_WEIGHT_UNAVAILABLE", severity: "warning", element, message: `${element} is a valid element, but no usable atomic-weight value is available for mass calculation.` }));
    else if (eligibility.genericElementalFallback === "requires-explicit-registration") diagnostics.push(Object.freeze({ code: "ELEMENT_REQUIRES_EXPLICIT_PRECURSOR", severity: "warning", element, message: `No permitted elemental fallback is available for ${element}. Add or select an explicitly registered ${element}-bearing precursor.` }));
    else diagnostics.push(Object.freeze({ code: "GENERIC_ELEMENTAL_FALLBACK_DISALLOWED", severity: "warning", element, message: `Generic elemental fallback is disallowed for ${element}. ${eligibility.reason ?? "Add an explicitly registered precursor."}` }));
  }
  const effectiveRegistry = [...precursorRegistry, ...generated], byId = new Map(effectiveRegistry.map((item) => [item.id, item]));
  const raw: { id: string; name: string; items: RegisteredPrecursorDefinition[]; source: PrecursorSuggestionSource; status: PrecursorValidationStatus; explanation: string; bypassSearchLimits?: boolean; route?: RegisteredPrecursorRoute }[] = [];
  for (const route of savedRoutes) { const routeTarget = targetComposition(route.target); if (!routeTarget || !compositionsEqualExact(composition, routeTarget)) continue; const items = route.precursorIds.map((id) => byId.get(id)).filter((item): item is RegisteredPrecursorDefinition => Boolean(item)); if (items.length === route.precursorIds.length) raw.push({ id: `route:${route.id}`, name: route.name, items, source: route.sourceType ?? "saved-route", status: route.validationStatus, explanation: `Exact target match from a ${route.validationStatus} saved route.`, route }) }
  const elementals = required.map((element) => elementalFor(element, effectiveRegistry));
  if (elementals.every((item): item is RegisteredPrecursorDefinition => Boolean(item))) raw.push({ id: `elemental:${routeKey(elementals.map((item) => item.id))}`, name: "Generic direct elemental route \u00b7 Not laboratory validated", items: elementals, source: "elemental-fallback", status: validationFor(elementals), explanation: "A deterministic formula-identity route covers every required element. Purity, supplier, form, availability, hazards, and experimental suitability are not inferred.", bypassSearchLimits: true });
  for (const x of required.filter((element) => element === "C" || element === "N")) for (const binary of effectiveRegistry) { const amounts = precursorComposition(binary)?.amounts, elements = Object.keys(amounts ?? {}); if (!amounts?.[x] || elements.length !== 2 || elements.some((element) => !required.includes(element))) continue; const items = [binary, ...required.filter((element) => element !== x).map((element) => elementalFor(element, effectiveRegistry)).filter((item): item is RegisteredPrecursorDefinition => Boolean(item))]; if (required.some((element) => !items.some((item) => precursorComposition(item)?.amounts[element] !== undefined))) continue; raw.push({ id: `binary:${routeKey(items.map((item) => item.id))}`, name: `${x === "C" ? "Carbide" : "Nitride"}-containing candidate route`, items, source: "generic-candidate", status: validationFor(items), explanation: `A registered binary ${x === "C" ? "carbide" : "nitride"} is combined with registered elemental sources.` }) }
  const seen = new Set<string>(), suggestions: PrecursorRouteSuggestion[] = []; let examined = 0, limitReached = false;
  for (const candidate of raw) { const key = routeKey(candidate.items.map((item) => item.id)); if (seen.has(key) || (!candidate.bypassSearchLimits && candidate.items.length > maximumCandidatePrecursors)) continue; seen.add(key); if (!candidate.bypassSearchLimits && examined >= candidateLimit) { limitReached = true; break } examined += 1; const assessment = assessPrecursorRoute(target, candidate.items); if (!assessment.usable || !assessment.solver) { diagnostics.push(Object.freeze({ code: "CANDIDATE_SOLVER_INFEASIBLE", severity: "warning", candidateId: candidate.id, message: `${candidate.name} was rejected because the exact non-negative solver returned ${assessment.solver?.status ?? "invalid-input"}.` })); continue } const warnings: PrecursorSuggestionDiagnostic[] = []; if (assessment.introducedNonTargetElements.length) warnings.push(Object.freeze({ code: "CANDIDATE_INTRODUCES_NON_TARGET_ELEMENTS", severity: "warning", candidateId: candidate.id, message: `Introduces non-target elements: ${assessment.introducedNonTargetElements.join(", ")}.` })); if (assessment.underdetermined) warnings.push(Object.freeze({ code: "CANDIDATE_UNDERDETERMINED", severity: "warning", candidateId: candidate.id, message: "The candidate has multiple exact non-negative balances; the deterministic solver tie-break is shown." })); const sourceRank = candidate.source === "saved-route" ? (candidate.status === "lab-approved" ? 0 : candidate.status === "spreadsheet-matched" ? 1 : candidate.status === "hand-audited" ? 2 : 6) : candidate.source === "built-in-route" && candidate.status === "source-verified" ? 3 : candidate.source === "generic-candidate" ? 4 : candidate.source === "elemental-fallback" ? 5 : 6; suggestions.push(Object.freeze({ candidateId: candidate.id, name: candidate.name, precursorIds: Object.freeze(candidate.items.map((item) => item.id)), precursorFormulas: Object.freeze(candidate.items.map((item) => item.formula ?? item.name)), precursors: Object.freeze([...candidate.items]), sourceType: candidate.source, validationStatus: candidate.status, matrixStatus: "consistent", solverStatus: assessment.solver.status, solverQuantities: assessment.solver.exactQuantitiesByPrecursorId, introducedNonTargetElements: assessment.introducedNonTargetElements, warnings: Object.freeze(warnings), explanation: candidate.explanation, priority: Object.freeze({ sourceRank, validationRank: VALIDATION_RANK[candidate.status], precursorCount: candidate.items.length, stableKey: candidate.id }), ...(candidate.route ? { sourceRouteId: candidate.route.id, ...(candidate.route.sourceRouteRevisionId ? { sourceRouteRevisionId: candidate.route.sourceRouteRevisionId } : {}) } : {}) })) }
  if (limitReached) diagnostics.push(Object.freeze({ code: "CANDIDATE_SEARCH_LIMIT_REACHED", severity: "warning", message: `Candidate verification stopped at the deterministic limit of ${candidateLimit}.` }));
  suggestions.sort((left, right) => left.priority.sourceRank - right.priority.sourceRank || left.priority.validationRank - right.priority.validationRank || left.priority.precursorCount - right.priority.precursorCount || left.priority.stableKey.localeCompare(right.priority.stableKey));
  const limited = Object.freeze(suggestions.slice(0, maximumSuggestions)); if (!limited.length) diagnostics.push(Object.freeze({ code: "NO_CANDIDATE_ROUTE_FOUND", severity: "warning", message: "No registered precursor set produced an exact non-negative balance for this target." }));
  return Object.freeze({ suggestions: limited, diagnostics: Object.freeze(diagnostics), candidatesExamined: examined, candidateLimit, limitReached });
}
