import { expect, test, type Page } from "@playwright/test";

function printJob(count: 2 | 4 | 6, paperSize: "letter" | "a4", rows = count === 6 ? 2 : 3) {
  const fields = { recipeName: true, revision: true, adjustedFeedFormula: true, targetBatchMass: true, batchBasis: true, precursorName: true, precursorFormula: true, molarRatio: true, purity: true, molarMass: true, atomicRadius: true, finalMass: true, totalMass: true, arithmeticVerificationStatus: true, actionRequiredWarnings: true, minorAdvisories: false, notes: false, radiusSummary: false, engineVersion: true, datasetVersions: true, signatureLines: false };
  const summary = (index: number) => ({ title: `Recipe ${index + 1}`, sourceStatus: `Revision ${index + 1}`, adjustedFeedFormula: "(ScTiVCrMnFeCoNiZr)4AlC3", targetFormula: "(ScTiVCrMnFeCoNiZr)4AlC3", idealFormula: "(ScTiVCrMnFeCoNiZr)4AlC3", intendedFeedFormula: "(ScTiVCrMnFeCoNiZr)4AlC3", realizedFormula: "Sc0.4Ti0.4V0.4Cr0.4Mn0.4Fe0.4Co0.4Ni0.4Zr0.4AlC3", batchMass: "10.000", batchBasis: "ideal-product-mass", totalMass: "10.001", unit: "g", actionRequiredMessages: [], minorAdvisoryMessages: [], engineVersion: "test", atomicWeightDataVersion: "test", radiusSites: [], verificationSummary: { statusLabel: "Arithmetic verification: verified exactly", targetFormulaMoles: "1", largestElementalResidual: "None", atomicDataVersion: "test" }, isHistorical: true, isStale: false, precursors: Array.from({ length: rows }, (_, row) => ({ id: `${index}-${row}`, displayName: row ? `Element ${row}` : "Titanium", formula: row ? "Al" : "Ti", molarQuantity: "1", solverMolarQuantity: "1", solverMolarQuantityExact: "1", hasPostSolverAdjustment: false, finalMass: `${row + 1}.000`, purityPercent: "100", molarMass: row ? "26.982" : "47.867", atomicRadius: row ? "N/A" : "147 pm · metallic", unit: "g", status: "OK" })) });
  const id = `print-${paperSize}-${count}-${rows}`;
  return { schemaVersion: "1.0.0", id, kind: "library", title: "Print test", createdAt: "2026-07-15T12:00:00.000Z", singleRecipeDetailed: false, settings: { paperSize, orientation: count === 2 ? "portrait" : "landscape", recipesPerPage: count, density: count === 2 ? "comfortable" : count === 4 ? "compact" : "ultra-compact", fields, formulaStyle: "adjusted-feed-only", warningDetail: "action-required-only", notesMode: "none", verificationDetail: "status-and-largest-residual", showPageNumbers: true, showPrintDate: true, showApplicationName: true, repeatTableHeaders: true }, entries: Array.from({ length: count }, (_, index) => ({ id: String(index), summary: summary(index) })) };
}

async function openJob(page: Page, job: ReturnType<typeof printJob>) {
  await page.addInitScript(() => { window.print = () => { document.documentElement.dataset.printInvoked = "true"; }; }); await page.goto("/"); await page.evaluate((value) => localStorage.setItem(`max-stoich.print-job.${value.id}`, JSON.stringify(value)), job); await page.goto(`/print?job=${job.id}`); await expect(page.locator('.dedicated-print-root[data-print-ready="true"]')).toBeVisible();
}

for (const paper of ["letter", "a4"] as const) for (const count of [2, 4, 6] as const) test(`PRINT-${paper.toUpperCase()}-${count}-UP packs readable recipes at 100%`, async ({ page }) => {
  await openJob(page, printJob(count, paper)); const root = page.locator(".dedicated-print-root"); await expect(root).toHaveAttribute("data-paper-size", paper); await expect(root).toHaveAttribute("data-recipes-per-page", String(count)); await expect(page.locator(".print-page")).toHaveCount(1); await expect(page.locator(".print-recipe")).toHaveCount(count); await expect(root.getByRole("button")).toHaveCount(0);
  const metrics = await page.locator(".print-recipe").first().evaluate((recipe) => ({ title: parseFloat(getComputedStyle(recipe.querySelector("h2")!).fontSize), row: parseFloat(getComputedStyle(recipe.querySelector("tbody")!).fontSize), mass: parseFloat(getComputedStyle(recipe.querySelector("tbody .mass")!).fontSize), total: parseFloat(getComputedStyle(recipe.querySelector("tfoot .mass")!).fontSize), transform: getComputedStyle(document.querySelector(".dedicated-print-root")!).transform, clipped: document.querySelector(".print-page")!.scrollWidth > document.querySelector(".print-page")!.clientWidth }));
  const minimum = count === 2 ? { title: 17, row: 13, mass: 16, total: 20 } : count === 4 ? { title: 15, row: 12, mass: 14, total: 17 } : { title: 13, row: 11, mass: 13, total: 15 };
  expect(metrics.title).toBeGreaterThanOrEqual(minimum.title); expect(metrics.row).toBeGreaterThanOrEqual(minimum.row); expect(metrics.mass).toBeGreaterThanOrEqual(minimum.mass); expect(metrics.total).toBeGreaterThanOrEqual(minimum.total); expect(metrics.transform).toBe("none"); expect(metrics.clipped).toBe(false);
});

test("PRINT-LONG-001 gives a long recipe additional space without global scaling", async ({ page }) => {
  const job = printJob(6, "letter", 14); job.entries = [job.entries[0]!, ...printJob(6, "letter", 2).entries]; await openJob(page, job); await expect(page.getByText(/will use a full page/)).toBeVisible(); await expect(page.locator(".print-page")).toHaveCount(2); await expect(page.locator(".print-recipe")).toHaveCount(7); await expect(page.locator(".print-formulas strong").first()).toHaveCSS("overflow-wrap", "anywhere");
});
