import { expect, test, type Page } from "@playwright/test";

const WEIGHING_RESULTS_FONT = 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace';

function printJob(count: 2 | 4 | 6, paperSize: "letter" | "a4", rows = count === 6 ? 2 : 3, orientation: "portrait" | "landscape" = count === 2 ? "portrait" : "landscape") {
  const fields = { recipeName: true, revision: true, adjustedFeedFormula: true, targetBatchMass: true, batchBasis: true, precursorName: true, precursorFormula: true, molarRatio: true, purity: true, molarMass: false, atomicRadius: false, finalMass: true, totalMass: true, arithmeticVerificationStatus: true, actionRequiredWarnings: true, minorAdvisories: false, notes: false, radiusSummary: false, engineVersion: true, datasetVersions: true, signatureLines: false };
  const summary = (index: number) => ({ title: index ? `Recipe ${index + 1}` : "Long high-entropy 413 screening batch with reviewed precursor route", sourceStatus: `Revision ${index + 1}`, adjustedFeedFormula: "(ScTiVCrMnFeCoNiZrHfTaWMo)4Al1.2C2.7", targetFormula: "(ScTiVCrMnFeCoNiZrHfTaWMo)4AlC3", idealFormula: "(ScTiVCrMnFeCoNiZrHfTaWMo)4AlC3", intendedFeedFormula: "(ScTiVCrMnFeCoNiZrHfTaWMo)4Al1.2C2.7", realizedFormula: "Sc0.2Ti0.4V0.4Cr0.4Mn0.4Fe0.4Co0.4Ni0.4Zr0.4Hf0.2Ta0.2W0.2Mo0.2Al1.2C2.7", batchMass: "10.000", batchBasis: "ideal-product-mass", totalMass: "10.001", unit: "g", actionRequiredMessages: index === 0 && rows > 3 ? ["Review the long precursor route and confirm the selected purity values before weighing."] : [], minorAdvisoryMessages: [], engineVersion: "test", atomicWeightDataVersion: "test", radiusSites: [], verificationSummary: { statusLabel: "Arithmetic verification: verified exactly", targetFormulaMoles: "1", largestElementalResidual: "None", atomicDataVersion: "test" }, isHistorical: true, isStale: false, precursors: Array.from({ length: rows }, (_, row) => ({ id: `${index}-${row}`, displayName: row ? `Elemental precursor ${row}` : "Titanium carbide", formula: row ? "Al" : "TiC", molarQuantity: "1", solverMolarQuantity: "1", solverMolarQuantityExact: "1", hasPostSolverAdjustment: false, finalMass: `${row + 1}.000`, purityPercent: "100", molarMass: row ? "26.982" : "59.878", atomicRadius: row ? "N/A" : "147 pm · metallic", unit: "g", status: "OK" })) });
  const id = `print-${paperSize}-${count}-${rows}-${orientation}`;
  return { schemaVersion: "1.0.0", id, kind: "library", title: "Print test", createdAt: "2026-07-15T12:00:00.000Z", singleRecipeDetailed: false, settings: { paperSize, orientation, recipesPerPage: count, density: count === 2 ? "comfortable" : count === 4 ? "compact" : "ultra-compact", fields, formulaStyle: "adjusted-feed-only", warningDetail: "action-required-only", notesMode: "none", verificationDetail: "status-and-largest-residual", showPageNumbers: true, showPrintDate: true, showApplicationName: true, repeatTableHeaders: true }, entries: Array.from({ length: count }, (_, index) => ({ id: String(index), summary: summary(index) })) };
}

async function openJob(page: Page, job: ReturnType<typeof printJob>) {
  await page.addInitScript(() => { window.print = () => { document.documentElement.dataset.printInvoked = "true"; }; });
  await page.goto("/");
  await page.evaluate((value) => localStorage.setItem(`max-stoich.print-job.${value.id}`, JSON.stringify(value)), job);
  await page.goto(`/print?job=${job.id}`);
  await expect(page.locator('.dedicated-print-root[data-print-ready="true"]')).toBeVisible();
}

for (const paper of ["letter", "a4"] as const) for (const orientation of ["portrait", "landscape"] as const) for (const count of [2, 4, 6] as const) test(`PRINT-${paper.toUpperCase()}-${orientation.toUpperCase()}-${count}-UP packs content-sized recipes at 100%`, async ({ page }, testInfo) => {
  await openJob(page, printJob(count, paper, undefined, orientation));
  const root = page.locator(".dedicated-print-root");
  await expect(root).toHaveAttribute("data-paper-size", paper); await expect(root).toHaveAttribute("data-orientation", orientation); await expect(root).toHaveAttribute("data-recipes-per-page", String(count)); await expect(page.locator(".print-page")).toHaveCount(1); await expect(page.locator(".print-recipe")).toHaveCount(count); await expect(root.getByRole("button")).toHaveCount(0);
  await page.emulateMedia({ media: "print" });
  const metrics = await page.locator(".print-recipe").first().evaluate((recipe) => ({ title: parseFloat(getComputedStyle(recipe.querySelector("h2")!).fontSize), row: parseFloat(getComputedStyle(recipe.querySelector("tbody")!).fontSize), mass: parseFloat(getComputedStyle(recipe.querySelector("tbody .mass")!).fontSize), total: parseFloat(getComputedStyle(recipe.querySelector("tfoot .mass")!).fontSize), transform: getComputedStyle(document.querySelector(".dedicated-print-root")!).transform, clipped: document.querySelector(".print-page")!.scrollWidth > document.querySelector(".print-page")!.clientWidth }));
  const minimum = count === 2 ? { title: 17, row: 13, mass: 16, total: 20 } : count === 4 ? { title: 15, row: 12, mass: 14, total: 17 } : { title: 13, row: 11, mass: 13, total: 15 };
  expect(metrics.title).toBeGreaterThanOrEqual(minimum.title); expect(metrics.row).toBeGreaterThanOrEqual(minimum.row); expect(metrics.mass).toBeGreaterThanOrEqual(minimum.mass); expect(metrics.total).toBeGreaterThanOrEqual(minimum.total); expect(metrics.transform).toBe("none"); expect(metrics.clipped).toBe(false);
  const geometry = await page.locator(".print-page").evaluate((printPage) => { const pageRect = printPage.getBoundingClientRect(); const cards = [...printPage.querySelectorAll<HTMLElement>(".print-recipe")]; const reserved = [...printPage.querySelectorAll<HTMLElement>(".print-page-header, .print-page-footer")]; const rects = cards.map((card) => card.getBoundingClientRect()); const intersects = (a: DOMRect, b: DOMRect) => a.left < b.right - .5 && a.right > b.left + .5 && a.top < b.bottom - .5 && a.bottom > b.top + .5; return { withinPage: rects.every((rect) => rect.left >= pageRect.left - 1 && rect.right <= pageRect.right + 1 && rect.top >= pageRect.top - 1 && rect.bottom <= pageRect.bottom + 1), cardsOverlap: rects.some((rect, index) => rects.slice(index + 1).some((other) => intersects(rect, other))), reservedOverlap: rects.some((rect) => reserved.some((item) => intersects(rect, item.getBoundingClientRect()))), splitPolicy: cards.every((card) => ["avoid", "avoid-page"].includes(getComputedStyle(card).breakInside)), contentSized: cards.every((card) => Math.abs(card.getBoundingClientRect().height - card.scrollHeight) <= 3), sparseCardPageRatio: Math.max(...rects.map((rect) => rect.height / pageRect.height)) }; });
  expect(geometry).toMatchObject({ withinPage: true, cardsOverlap: false, reservedOverlap: false, splitPolicy: true, contentSized: true }); if (count === 6) expect(geometry.sparseCardPageRatio).toBeLessThan(.34);
  const representative = (paper === "letter" && orientation === "portrait" && count === 6) || (paper === "a4" && orientation === "landscape" && count === 4); const artifactName = `${paper}-${orientation}-${count}-up`; const pdf = await page.pdf({ format: paper === "letter" ? "Letter" : "A4", landscape: orientation === "landscape", path: representative ? testInfo.outputPath(`${artifactName}.pdf`) : undefined, printBackground: true, preferCSSPageSize: true }); expect(pdf.byteLength).toBeGreaterThan(10_000); if (representative) await page.screenshot({ fullPage: true, path: testInfo.outputPath(`${artifactName}.png`) });
});

test("PRINT-LONG-001 gives a long recipe additional space without global scaling", async ({ page }) => {
  const job = printJob(6, "letter", 14); job.settings.fields.molarMass = true; job.settings.fields.atomicRadius = true; job.entries = [job.entries[0]!, ...printJob(6, "letter", 2).entries]; await openJob(page, job); await expect(page.getByText(/will use a full page/)).toBeVisible(); await expect(page.locator(".print-page")).toHaveCount(2); await expect(page.locator(".print-recipe")).toHaveCount(7); await expect(page.locator(".print-formulas strong").first()).toHaveCSS("overflow-wrap", "anywhere"); await page.emulateMedia({ media: "print" }); const dimensions = await page.locator(".print-page").first().evaluate((printPage) => ({ clientHeight: printPage.clientHeight, scrollHeight: printPage.scrollHeight, cardHeight: printPage.querySelector<HTMLElement>(".print-recipe")!.getBoundingClientRect().height, gridHeight: printPage.querySelector<HTMLElement>(".print-recipe-grid")!.getBoundingClientRect().height })); expect(dimensions.scrollHeight, JSON.stringify(dimensions)).toBeLessThanOrEqual(dimensions.clientHeight + 1);
});

test("PRINT-THEME-001 is identical in Light, Dark, and Midnight and reuses weighing-result typography", async ({ page }) => {
  await openJob(page, printJob(6, "a4", 2, "landscape")); await page.emulateMedia({ media: "print" }); const samples = [];
  for (const theme of ["light", "dark", "midnight"] as const) { await page.evaluate((value) => { document.documentElement.dataset.theme = value; }, theme); samples.push(await page.locator(".print-recipe").first().evaluate((recipe) => { const card = getComputedStyle(recipe); const mass = getComputedStyle(recipe.querySelector(".mass")!); const rule = getComputedStyle(recipe.querySelector("td")!); return { background: card.backgroundColor, color: card.color, border: card.borderColor, rule: rule.borderBottomColor, font: card.fontFamily, massFont: mass.fontFamily, numerals: mass.fontVariantNumeric, filter: card.filter, opacity: card.opacity, shadow: card.boxShadow }; })); }
  expect(samples[1]).toEqual(samples[0]); expect(samples[2]).toEqual(samples[0]); expect(samples[0]).toMatchObject({ background: "rgb(255, 255, 255)", color: "rgb(17, 24, 39)", border: "rgb(51, 65, 85)", rule: "rgb(51, 65, 85)", font: WEIGHING_RESULTS_FONT, massFont: WEIGHING_RESULTS_FONT, numerals: "tabular-nums", filter: "none", opacity: "1", shadow: "none" });
});

test("PRINT-CREDIT-001 has one non-overlapping brand and the complete professional credit", async ({ page }) => {
  await openJob(page, printJob(4, "letter", 3, "landscape")); await page.emulateMedia({ media: "print" }); await expect(page.getByText("MAX Stoich", { exact: true })).toHaveCount(1); const credit = page.locator(".print-credit"); await expect(credit).toContainText("Built by Matthew Deng"); await expect(credit).toContainText("deng301@purdue.edu for inquiries"); await expect(credit).toContainText("Built for the Anasori Lab"); await expect(credit.getByRole("link", { name: "deng301@purdue.edu for inquiries" })).toHaveAttribute("href", "mailto:deng301@purdue.edu");
  expect(await page.locator(".print-page").evaluate((printPage) => { const nodes = [...printPage.querySelectorAll<HTMLElement>(".page-app, .print-page-header > span, .print-credit, .page-meta, .print-recipe")]; const rects = nodes.map((node) => node.getBoundingClientRect()); return !rects.some((rect, index) => rects.slice(index + 1).some((other) => rect.left < other.right - .5 && rect.right > other.left + .5 && rect.top < other.bottom - .5 && rect.bottom > other.top + .5)); })).toBe(true);
});
