"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useAccountRepositories } from "@/components/cloud/use-account-repositories";
import { calculatedPatternSchema, type CalculatedXRDPattern } from "@/lib/xrd/schemas";
import type { XRDPeakAnalysis } from "@/lib/xrd/stage3";
import { XRDReferenceRepository, type XRDReference, type XRDReferenceRevision } from "@/lib/xrd/references";

type Selection = { readonly pattern: CalculatedXRDPattern; readonly referenceId: string; readonly revisionId: string; readonly revisionNumber: number };
const sourceLabels: Record<XRDReference["sourceType"], string> = { COD: "COD", LMSL_CIF: "LMSL CIF", USER_CIF: "User CIF", LMSL_EMPIRICAL: "LMSL empirical", USER_EMPIRICAL: "User empirical" };
function fmt(value: number, digits = 4) { return value.toLocaleString(undefined, { maximumFractionDigits: digits }); }

function ComparisonPlot({ x, y, pattern }: { readonly x: readonly number[]; readonly y: readonly number[]; readonly pattern: CalculatedXRDPattern }) {
  const width = 900, height = 270, left = 55, right = 18, top = 18, bottom = 42, minX = Math.max(Math.min(...x), pattern.twoThetaRange.minDeg), maxX = Math.min(Math.max(...x), pattern.twoThetaRange.maxDeg);
  const xMap = (v: number) => left + (v-minX)/(maxX-minX)*(width-left-right), maxY = Math.max(...y, 1), yMap = (v: number) => top+(1-v/maxY)*(height-top-bottom);
  const stride = Math.max(1, Math.ceil(x.length/4000)), points = x.filter((_, i) => i%stride===0).map((v, i) => `${xMap(v)},${yMap(y[i*stride] ?? 0)}`).join(" ");
  return <div><svg aria-label="Measured empirical pattern with calculated theoretical reference sticks" className="xrd-stick-plot" role="img" viewBox={`0 0 ${width} ${height}`}><polyline fill="none" points={points} stroke="var(--ink)" strokeWidth="1.2" />{pattern.reflections.filter((peak) => peak.twoThetaDeg>=minX && peak.twoThetaDeg<=maxX).map((peak, i) => <line key={i} stroke="var(--accent)" x1={xMap(peak.twoThetaDeg)} x2={xMap(peak.twoThetaDeg)} y1={height-bottom} y2={height-bottom-(peak.relativeIntensity/100)*65} />)}<text x={left} y={14}>Measured empirical intensity</text><text fill="var(--accent)" x={width-230} y={14}>Calculated intensity sticks</text><text x={width/2} y={height-6} textAnchor="middle">2θ (degrees)</text></svg><p className="xrd-plot-note">Measured and calculated intensities use distinct scales; this overlay does not claim quantitative intensity equivalence.</p></div>;
}

function StructureRevisionDetails({ revision }: { readonly revision: XRDReferenceRevision & { readonly payload: Extract<XRDReferenceRevision["payload"], { kind: "STRUCTURE" }> } }) {
  const pattern = revision.payload.theoreticalPattern, width=900, height=220, left=55, right=18, bottom=36, span=pattern.twoThetaRange.maxDeg-pattern.twoThetaRange.minDeg, x=(v:number)=>left+(v-pattern.twoThetaRange.minDeg)/span*(width-left-right);
  return <section className="xrd-panel" aria-labelledby="saved-structure-pattern-title"><div className="xrd-section-heading"><div><span className="xrd-step-kicker">Saved calculated pattern</span><h2 id="saved-structure-pattern-title">Theoretical structure detail</h2><p>Calculated intensity is normalized within this pymatgen pattern; it is not measured empirical intensity.</p></div></div><svg aria-label={`Saved theoretical XRD stick pattern for ${revision.formula}`} className="xrd-stick-plot" role="img" viewBox={`0 0 ${width} ${height}`}>{pattern.reflections.map((peak,i)=><line className="xrd-stick" key={i} x1={x(peak.twoThetaDeg)} x2={x(peak.twoThetaDeg)} y1={height-bottom} y2={height-bottom-(peak.relativeIntensity/100)*(height-bottom-18)} />)}<line className="xrd-axis" x1={left} x2={width-right} y1={height-bottom} y2={height-bottom}/><text className="xrd-axis-label" textAnchor="middle" x={width/2} y={height-5}>2θ (degrees)</text></svg><div className="xrd-reflection-table"><table><caption>Persisted calculated reflections</caption><thead><tr><th>2θ (°)</th><th>Calculated relative intensity</th><th>d (Å)</th><th>Grouped hkl</th></tr></thead><tbody>{pattern.reflections.map((peak,i)=><tr key={i}><td>{fmt(peak.twoThetaDeg,5)}</td><td>{fmt(peak.relativeIntensity,3)}</td><td>{fmt(peak.dAngstrom,6)}</td><td>{peak.hkls.map((item)=>`(${item.h} ${item.k} ${item.l})${item.multiplicity?` ×${item.multiplicity}`:""}`).join(", ")}</td></tr>)}</tbody></table></div></section>;
}

export function XrdReferenceLibrary({ candidatePattern, activeAnalysis, onSelect }: { readonly candidatePattern: CalculatedXRDPattern | null; readonly activeAnalysis: XRDPeakAnalysis | null; readonly onSelect: (selection: Selection) => void }) {
  const repositories = useAccountRepositories(), repository = useMemo(() => new XRDReferenceRepository(repositories.database), [repositories.database]), fileRef = useRef<HTMLInputElement>(null), bundleRef = useRef<HTMLInputElement>(null);
  const [references, setReferences] = useState<readonly XRDReference[]>([]), [selected, setSelected] = useState<{ reference: XRDReference; revision: XRDReferenceRevision }>(), [history, setHistory] = useState<readonly XRDReferenceRevision[]>([]);
  const [query, setQuery] = useState(""), [source, setSource] = useState("ALL"), [status, setStatus] = useState("ALL"), [message, setMessage] = useState("Saved references remain usable offline in this browser.");
  const [empirical, setEmpirical] = useState({ displayName: "", formula: "", wavelength: "1.54184", sampleId: "", batchId: "", recipeId: "", associatedRevisionId: "", notes: "" });
  const [cifSource, setCifSource] = useState<"USER_CIF" | "LMSL_CIF">("USER_CIF"), [pending, setPending] = useState(false);
  const [associationRevisionId, setAssociationRevisionId] = useState("");
  const refresh = useCallback(async () => setReferences(await repository.list()), [repository]);
  useEffect(() => { queueMicrotask(() => void refresh()); }, [refresh]);
  const structures = references.filter((item) => ["COD", "LMSL_CIF", "USER_CIF"].includes(item.sourceType));
  const shown = references.filter((item) => { const text = `${item.displayName} ${item.phaseName ?? ""} ${item.formula} ${item.tags.join(" ")}`.toLowerCase(); return (!query.trim() || text.includes(query.trim().toLowerCase())) && (source === "ALL" || item.sourceType === source) && (status === "ALL" || item.validationStatus === status); });

  async function open(referenceId: string) { const item = await repository.get(referenceId); if (!item) return; setSelected(item); setAssociationRevisionId(item.revision.payload.kind === "EMPIRICAL" ? item.revision.payload.associatedStructure?.revisionId ?? "" : ""); setHistory(await repository.revisions(referenceId)); }
  async function savePattern(pattern: CalculatedXRDPattern, sourceType?: "COD" | "LMSL_CIF" | "USER_CIF") {
    if (!pattern.cifContent) throw new Error("The exact CIF text is unavailable; recalculate this reference with the Stage 5 service first.");
    const saved = await repository.createStructure({ pattern, cifText: pattern.cifContent, sourceType }); await refresh(); await open(saved.reference.referenceId);
    setMessage(saved.duplicates.length ? `Saved as an intentional separate entry; ${saved.duplicates.length} existing revision(s) use identical CIF content.` : "Reference saved locally with exact CIF text, hashes, calculation settings, and an immutable revision.");
  }
  async function upload(file: File) {
    setPending(true); try { const cifContent = await file.text(); const response = await fetch("/api/xrd/pattern/calculate", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ cifContent, metadata: { sourceType: cifSource === "LMSL_CIF" ? "lmsl-cif" : "user-cif", sourceId: file.name }, radiation: { preset: "CuKa" }, twoThetaRange: { minDeg: 10, maxDeg: 90 } }) });
      const body: unknown = await response.json().catch(() => null); if (!response.ok) throw new Error(typeof body === "object" && body && "error" in body ? String((body as { error?: { message?: string } }).error?.message) : "CIF calculation failed.");
      await savePattern(calculatedPatternSchema.parse(body), cifSource);
    } catch (error) { setMessage(error instanceof Error ? error.message : "CIF import failed."); } finally { setPending(false); if (fileRef.current) fileRef.current.value = ""; }
  }
  async function promoteEmpirical() {
    if (!activeAnalysis) return; setPending(true); try {
      let associatedStructure: Selection | undefined;
      if (empirical.associatedRevisionId) { const revision = await repository.getRevision(empirical.associatedRevisionId); if (revision) associatedStructure = { pattern: revision.payload.kind === "STRUCTURE" ? revision.payload.theoreticalPattern : candidatePattern!, referenceId: revision.referenceId, revisionId: revision.revisionId, revisionNumber: revision.revisionNumber }; }
      const saved = await repository.createEmpirical({ measurementId: activeAnalysis.parentMeasurementId, processedRepresentationId: activeAnalysis.parentProcessedRepresentationId, peakAnalysisId: activeAnalysis.peakAnalysisId,
        displayName: empirical.displayName, formula: empirical.formula, wavelengthAngstrom: Number(empirical.wavelength), sampleId: empirical.sampleId, batchId: empirical.batchId, recipeId: empirical.recipeId, notes: empirical.notes,
        associatedStructure: associatedStructure ? { referenceId: associatedStructure.referenceId, revisionId: associatedStructure.revisionId, revisionNumber: associatedStructure.revisionNumber } : undefined });
      await refresh(); await open(saved.reference.referenceId); setMessage("Empirical reference saved as UNREVIEWED with exact Stage 2/3 lineage. It was not automatically validated.");
    } catch (error) { setMessage(error instanceof Error ? error.message : "Empirical reference could not be saved."); } finally { setPending(false); }
  }
  async function selectRevisionForStage4(revision: XRDReferenceRevision) {
    let structure = revision;
    if (revision.payload.kind === "EMPIRICAL") { if (!revision.payload.associatedStructure) { setMessage("This empirical reference has no associated crystallographic structure and cannot supply hkl/lattice data to Stage 4."); return; } const linked = await repository.getRevision(revision.payload.associatedStructure.revisionId); if (!linked) { setMessage("The associated structure revision is unavailable."); return; } structure = linked; }
    if (structure.payload.kind !== "STRUCTURE") return;
    onSelect({ pattern: structure.payload.theoreticalPattern, referenceId: structure.referenceId, revisionId: structure.revisionId, revisionNumber: structure.revisionNumber }); setMessage(`Selected exact structure revision ${structure.revisionNumber} for Stage 4.`);
  }
  async function changeStatus(value: XRDReferenceRevision["validationStatus"]) { if (!selected) return; await repository.revise(selected.reference.referenceId, { validationStatus: value }, `Validation status changed to ${value}`, "VALIDATION"); await refresh(); await open(selected.reference.referenceId); }
  async function updateAssociation() { if (!selected || selected.revision.payload.kind !== "EMPIRICAL") return; let associatedStructure = null; if (associationRevisionId) { const revision = await repository.getRevision(associationRevisionId); if (!revision || revision.payload.kind !== "STRUCTURE") { setMessage("The selected structure revision is unavailable."); return; } associatedStructure = { referenceId: revision.referenceId, revisionId: revision.revisionId, revisionNumber: revision.revisionNumber }; } await repository.revise(selected.reference.referenceId, { payload: { ...selected.revision.payload, associatedStructure } }, associatedStructure ? "Associated crystallographic structure revision changed" : "Crystallographic structure association removed", "SCIENTIFIC"); await refresh(); await open(selected.reference.referenceId); setMessage("Association changed in a new scientific revision; earlier revisions remain unchanged."); }
  function download() { if (!selected) return; const blob = new Blob([repository.exportMetadata(selected.reference, selected.revision)], { type: "application/json" }), url = URL.createObjectURL(blob), anchor = document.createElement("a"); anchor.href=url; anchor.download=`${selected.reference.referenceId}-r${selected.revision.revisionNumber}.json`; anchor.click(); URL.revokeObjectURL(url); }
  function downloadBundle() { if (!selected) return; const blob = new Blob([repository.exportBundle(selected.reference, selected.revision)], { type: "application/json" }), url = URL.createObjectURL(blob), anchor = document.createElement("a"); anchor.href=url; anchor.download=`${selected.reference.referenceId}-r${selected.revision.revisionNumber}.xrd-reference.json`; anchor.click(); URL.revokeObjectURL(url); }
  async function importBundle(file: File) { setPending(true); try { const imported = await repository.importBundle(await file.text()); await refresh(); await open(imported.reference.referenceId); setMessage("Reference bundle imported under a new local identity after hash and lineage validation."); } catch (error) { setMessage(error instanceof Error ? error.message : "Reference bundle import failed."); } finally { setPending(false); if (bundleRef.current) bundleRef.current.value=""; } }

  const comparison = selected?.revision.payload.kind === "EMPIRICAL" && selected.revision.payload.associatedStructure ? selected.revision : undefined;
  const [comparisonData, setComparisonData] = useState<{ x: readonly number[]; y: readonly number[]; pattern: CalculatedXRDPattern }>();
  useEffect(() => { if (!comparison || comparison.payload.kind !== "EMPIRICAL" || !comparison.payload.associatedStructure) return; let active = true; void Promise.all([repositories.database.xrdMeasurements.get(comparison.payload.sourceMeasurementId), repository.getRevision(comparison.payload.associatedStructure.revisionId)]).then(([measurement, structure]) => { if (active && measurement && structure?.payload.kind === "STRUCTURE") setComparisonData({ x: measurement.measurement.twoThetaDeg, y: measurement.measurement.intensity, pattern: structure.payload.theoreticalPattern }); }); return () => { active = false; }; }, [comparison, repositories.database, repository]);

  return <div className="xrd-workspace"><section className="xrd-panel" aria-labelledby="xrd-reference-library-title"><div className="xrd-section-heading"><div><span className="xrd-step-kicker">Versioned local library</span><h2 id="xrd-reference-library-title">XRD references</h2><p>Structures and measured empirical patterns remain scientifically distinct, but can be linked explicitly.</p></div></div>
    <div className="xrd-search-form"><label>Search name, formula, or tag<input aria-label="Search XRD references" onChange={(e)=>setQuery(e.target.value)} value={query} /></label><label>Source<select onChange={(e)=>setSource(e.target.value)} value={source}><option value="ALL">All</option>{Object.entries(sourceLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Status<select onChange={(e)=>setStatus(e.target.value)} value={status}><option value="ALL">All</option>{["UNREVIEWED","REVIEWED","VALIDATED","DEPRECATED"].map((v)=><option key={v}>{v}</option>)}</select></label></div>
    <p aria-live="polite" className="xrd-status">{message}</p>{shown.length===0?<p>No saved references match these filters.</p>:<div className="xrd-results-list">{shown.map((item)=><article key={item.referenceId}><div><h3>{item.displayName}<small>{item.formula} · {sourceLabels[item.sourceType]} · revision {item.currentRevisionNumber}</small></h3><dl><div><dt>Status</dt><dd>{item.validationStatus}</dd></div><div><dt>Crystal system</dt><dd>{item.crystalSystem ?? "Empirical only"}</dd></div><div><dt>Updated</dt><dd>{new Date(item.updatedAt).toLocaleString()}</dd></div></dl></div><button className="ui-button" onClick={()=>void open(item.referenceId)} type="button">Open</button></article>)}</div>}</section>

    <section className="xrd-panel"><h3>Add a crystallographic structure</h3>{candidatePattern?.reference.sourceType==="cod"&&<button className="ui-button ui-button-primary" disabled={pending} onClick={()=>void savePattern(candidatePattern,"COD").catch((e)=>setMessage(e instanceof Error?e.message:"Save failed."))} type="button">Save current COD result offline</button>}<div className="xrd-import-actions"><label>Uploaded CIF source<select onChange={(e)=>setCifSource(e.target.value as typeof cifSource)} value={cifSource}><option value="USER_CIF">User CIF</option><option value="LMSL_CIF">LMSL CIF</option></select></label><input accept=".cif,text/plain" aria-label="Upload CIF" disabled={pending} onChange={(e)=>{const file=e.target.files?.[0];if(file)void upload(file);}} ref={fileRef} type="file" /><label>Portable reference bundle<input accept=".json,application/json" aria-label="Import XRD reference bundle" disabled={pending} onChange={(e)=>{const file=e.target.files?.[0];if(file)void importBundle(file);}} ref={bundleRef} type="file" /></label></div></section>

    {activeAnalysis&&<section className="xrd-panel"><h3>Save selected analysis as an empirical reference</h3><p>The reference will point to the immutable measurement, processing run, and curated peak analysis instead of copying arrays.</p><div className="xrd-stage3-grid"><label>Reference name<input onChange={(e)=>setEmpirical({...empirical,displayName:e.target.value})} value={empirical.displayName} /></label><label>Composition / formula<input onChange={(e)=>setEmpirical({...empirical,formula:e.target.value})} value={empirical.formula} /></label><label>Wavelength (Å)<input min="0.000001" onChange={(e)=>setEmpirical({...empirical,wavelength:e.target.value})} type="number" value={empirical.wavelength} /></label><label>Associated structure<select onChange={(e)=>setEmpirical({...empirical,associatedRevisionId:e.target.value})} value={empirical.associatedRevisionId}><option value="">None</option>{structures.map((item)=><option key={item.referenceId} value={item.currentRevisionId}>{item.displayName} · r{item.currentRevisionNumber}</option>)}</select></label><label>Sample ID (optional)<input onChange={(e)=>setEmpirical({...empirical,sampleId:e.target.value})} value={empirical.sampleId} /></label><label>Batch ID (optional)<input onChange={(e)=>setEmpirical({...empirical,batchId:e.target.value})} value={empirical.batchId} /></label><label>Recipe ID (optional)<input onChange={(e)=>setEmpirical({...empirical,recipeId:e.target.value})} value={empirical.recipeId} /></label><label>Notes<textarea onChange={(e)=>setEmpirical({...empirical,notes:e.target.value})} value={empirical.notes} /></label></div><button className="ui-button ui-button-primary" disabled={pending||!empirical.displayName.trim()||!empirical.formula.trim()||!(Number(empirical.wavelength)>0)} onClick={()=>void promoteEmpirical()} type="button">Save as LMSL empirical reference</button></section>}

    {selected&&<section className="xrd-panel"><div className="xrd-section-heading"><div><span className="xrd-step-kicker">Reference detail · revision {selected.revision.revisionNumber}</span><h2>{selected.revision.displayName}</h2><p>{selected.revision.payload.kind==="STRUCTURE"?"Crystallographic structure with a reproducible calculated pattern":"Measured empirical reference with immutable experimental lineage"}</p></div></div><dl className="xrd-pattern-metadata"><div><dt>Source</dt><dd>{sourceLabels[selected.revision.sourceType]}</dd></div><div><dt>Formula</dt><dd>{selected.revision.formula}</dd></div><div><dt>Validation</dt><dd><select aria-label="Reference validation status" onChange={(e)=>void changeStatus(e.target.value as XRDReferenceRevision["validationStatus"])} value={selected.revision.validationStatus}>{["UNREVIEWED","REVIEWED","VALIDATED","DEPRECATED"].map((v)=><option key={v}>{v}</option>)}</select></dd></div>{selected.revision.payload.kind==="STRUCTURE"?<><div><dt>Space group</dt><dd>{selected.revision.payload.spaceGroup}</dd></div><div><dt>Crystal system</dt><dd>{selected.revision.payload.crystalSystem}</dd></div><div><dt>CIF SHA-256</dt><dd className="xrd-hash">{selected.revision.payload.cifSha256}</dd></div><div><dt>Pattern SHA-256</dt><dd className="xrd-hash">{selected.revision.payload.theoreticalPatternSha256}</dd></div></>:<><div><dt>Raw SHA-256</dt><dd className="xrd-hash">{selected.revision.payload.rawArtifactSha256}</dd></div><div><dt>Wavelength</dt><dd>{fmt(selected.revision.payload.wavelengthAngstrom,6)} Å</dd></div><div><dt>Processing / peaks</dt><dd>{selected.revision.payload.selectedProcessedRepresentationId?"Selected":"Raw only"} / {selected.revision.payload.selectedPeakAnalysisId?"Curated":"None"}</dd></div><div><dt>Structure link</dt><dd>{selected.revision.payload.associatedStructure?`Explicit revision ${selected.revision.payload.associatedStructure.revisionNumber}`:"None"}</dd></div></>}</dl><div className="xrd-library-actions"><button className="ui-button ui-button-primary" onClick={()=>void selectRevisionForStage4(selected.revision)} type="button">Use in Stage 4</button><button className="ui-button" onClick={download} type="button">Export metadata JSON</button><button className="ui-button" onClick={downloadBundle} type="button">Export portable bundle</button></div>{comparison&&comparisonData&&<ComparisonPlot {...comparisonData} />}<h3>Revision history</h3><div className="xrd-results-list">{history.map((revision)=><article key={revision.revisionId}><div><h3>Revision {revision.revisionNumber}<small>{revision.changeKind} · {new Date(revision.createdAt).toLocaleString()}</small></h3><p>{revision.changeSummary}</p></div><button className="ui-button" onClick={()=>setSelected({reference:selected.reference,revision})} type="button">Inspect</button></article>)}</div></section>}
    {selected?.revision.payload.kind === "STRUCTURE" && <StructureRevisionDetails revision={selected.revision as XRDReferenceRevision & { readonly payload: Extract<XRDReferenceRevision["payload"], { kind: "STRUCTURE" }> }} />}
    {selected?.revision.payload.kind === "EMPIRICAL" && <section className="xrd-panel"><h3>Structure association</h3><p>Choose an exact structure revision. Matching formula text alone never creates this link.</p><div className="xrd-import-actions"><label>Associated structure<select aria-label="Edit empirical structure association" onChange={(event)=>setAssociationRevisionId(event.target.value)} value={associationRevisionId}><option value="">No associated structure</option>{structures.map((item)=><option key={item.currentRevisionId} value={item.currentRevisionId}>{item.displayName} · revision {item.currentRevisionNumber}</option>)}</select></label><button className="ui-button" onClick={()=>void updateAssociation()} type="button">Save association revision</button></div></section>}
  </div>;
}
