"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { normalizeLeadingSiteRatioGroup } from "@max-stoich/chemistry-engine";
import { compareScenarios } from "@/lib/comparison/difference";
import { addComparisonScenario, calculateComparison, createComparisonWorkspace, duplicateScenario, MAX_COMPARISON_SCENARIOS, removeScenario, updateScenario } from "@/lib/comparison/model";
import { canonicalizeWorkspaceScientificInput, sha256Hex, stableCanonicalize } from "@/lib/persistence/canonical";
import { createOwnedRecordExport } from "@/lib/persistence/backup";
import { downloadText, safeExportFilename } from "@/lib/export/laboratory-export";
import { useAccountRepositories } from "@/components/cloud/use-account-repositories";
import type { ComparisonScenario, ComparisonWorkspace, RecipeRevision, SavedRecipe, SavedRoute, WorkspaceRecoveryState } from "@/lib/persistence/entities";
import type { WorkspaceCalculationState, WorkspaceRecipeState } from "@/lib/workspace/adapter";
import { buildWorkspaceCalculation } from "@/lib/workspace/adapter";
import { aluminumCoefficientForTargetChange, migrateWorkspaceAluminumInput } from "@/lib/workspace/aluminum-feed";
import { blankWorkspaceState } from "@/components/workspace/workspace-shell";
import { WeighingSummaryCard, WeighingSummaryDialog, type WeighingSummaryEntry } from "@/components/weighing-summary/weighing-summary-dialog";
import { AtomicRadiusPanel } from "@/components/descriptor-panel/atomic-radius-panel";
import { CalculationVerificationDialog, type CalculationVerificationEntry } from "@/components/verification/calculation-verification-dialog";
import { buildCalculationVerification } from "@/lib/presentation/calculation-verification";
import { buildWeighingSummary } from "@/lib/presentation/weighing-summary";
import { createDefaultUserSettings, type LocalUserSettings } from "@/lib/settings/user-settings";
import { createPrintJob, launchPrintJob } from "@/lib/print/print-model";
import { buildComparisonAnalysis, comparisonOverviewTsv, precursorMatrixTsv, signedDifference, type MatrixDisplayMode } from "@/lib/comparison/analysis";
import { SiteBrand } from "@/components/site/site-brand";

const clone = <T,>(value: T): T => structuredClone(value);
const forkHistoricalComparison = (value: ComparisonWorkspace): ComparisonWorkspace => { if (!value.historical) return value; const now = new Date().toISOString(); return { ...value, id: `comparison-${crypto.randomUUID()}`, name: `${value.name} (current engine)`, historical: false, createdAt: now, updatedAt: now }; };
const validResult = (calculation: WorkspaceCalculationState) => calculation.state === "valid" || calculation.state === "valid-with-warnings" ? calculation.result : undefined;
const calculationReason = (calculation: WorkspaceCalculationState) => calculation.errors.find((item) => item.code.includes("MISSING_REQUIRED_ELEMENT_SOURCE"))?.message ?? calculation.errors[0]?.message ?? "The current inputs do not produce a valid result.";
const blankPrecursor = (index: number) => ({ id: `precursor-${crypto.randomUUID()}`, name: `Precursor ${index}`, formula: "", purityPercent: "100", constraintMode: "solver" as const, fixedValue: "", minimum: "", maximum: "", ratioDenominatorId: "", numeratorRatio: "1", denominatorRatio: "1", molarMassOverride: "", molarMassOverrideSource: "" });

function uniqueName(name: string, scenarios: readonly ComparisonScenario[]): string {
  if (!scenarios.some((item) => item.name === name)) return name;
  let suffix = 2; while (scenarios.some((item) => item.name === `${name} (${suffix})`)) suffix += 1;
  return `${name} (${suffix})`;
}

interface RecipeCandidate { readonly recipe: SavedRecipe; readonly revision: RecipeRevision; readonly warningCount: number }

function RecipePicker({ open, candidates, existing, capacity, onClose, onAdd }: { open: boolean; candidates: readonly RecipeCandidate[]; existing: ReadonlySet<string>; capacity: number; onClose: () => void; onAdd: (ids: readonly string[]) => string | undefined }) {
  const ref = useRef<HTMLDialogElement>(null); const closeRef = useRef<HTMLButtonElement>(null);
  const [search, setSearch] = useState(""); const [selected, setSelected] = useState<ReadonlySet<string>>(new Set()); const [message, setMessage] = useState("");
  useEffect(() => { const dialog = ref.current; if (!dialog) return; if (open && !dialog.open) { setSelected(new Set()); setSearch(""); setMessage(""); dialog.showModal(); closeRef.current?.focus(); } else if (!open && dialog.open) dialog.close(); }, [open]);
  const visible = candidates.filter((item) => item.recipe.name.toLowerCase().includes(search.trim().toLowerCase()));
  const toggle = (id: string) => setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });
  const add = () => { if (!selected.size) { setMessage("Select at least one saved recipe."); return; } if (selected.size > capacity) { setMessage(`Only ${capacity} more scenario${capacity === 1 ? "" : "s"} can be added.`); return; } const rejection = onAdd([...selected]); if (rejection) setMessage(rejection); };
  return <dialog aria-labelledby="recipe-picker-title" className="m-auto max-h-[90vh] w-[min(94vw,70rem)] overflow-auto rounded-xl border-2 border-slate-800 p-0 backdrop:bg-slate-950/60" onCancel={(event) => { event.preventDefault(); onClose(); }} onClose={onClose} ref={ref}>
    <header className="sticky top-0 z-10 flex flex-wrap items-center gap-2 border-b bg-white p-4"><div className="mr-auto"><h2 className="text-xl font-bold" id="recipe-picker-title">Add saved recipes</h2><p className="text-sm">Current revisions are imported as independent editable scenarios. Different target formulas are allowed.</p></div><button className="rounded border px-3 py-2" onClick={onClose} ref={closeRef}>Cancel</button><button className="rounded bg-teal-800 px-3 py-2 font-semibold text-white" onClick={add}>Add selected</button></header>
    <div className="p-4"><label className="block font-medium">Search by recipe name<input className="mt-1 w-full rounded border px-3 py-2" onChange={(event) => setSearch(event.target.value)} value={search} /></label><div className="mt-3 flex gap-2"><button className="rounded border px-3 py-2 text-sm" onClick={() => setSelected(new Set(visible.filter((item) => !existing.has(item.revision.id)).map((item) => item.recipe.id)))}>Select all visible</button><button className="rounded border px-3 py-2 text-sm" onClick={() => setSelected(new Set())}>Clear selection</button></div>
      {message && <p aria-live="assertive" className="mt-3 rounded border border-red-400 bg-red-50 p-3 font-semibold">{message}</p>}
      <ul className="mt-4 space-y-2">{visible.map(({ recipe, revision, warningCount }) => { const already = existing.has(revision.id); return <li className="rounded border p-3" key={recipe.id}><label className="flex items-start gap-3"><input checked={selected.has(recipe.id)} className="mt-1 size-5" disabled={already} onChange={() => toggle(recipe.id)} type="checkbox" /><span><strong>{recipe.name}</strong>{already && <span className="ml-2 rounded bg-slate-200 px-2 py-1 text-xs font-semibold">Already added</span>}<span className="mt-1 block font-mono text-sm">{recipe.targetFormula}</span><span className="mt-1 block text-sm">Revision {revision.revisionNumber} · updated {new Date(recipe.updatedAt).toLocaleDateString()} · {recipe.validationStatus}</span><span className="block text-sm">{revision.inputState.requestedMassGrams} g · {revision.inputState.basis} · {warningCount} warning{warningCount === 1 ? "" : "s"}</span></span></label></li>; })}</ul>
      {!visible.length && <p className="mt-5 text-center text-slate-600">No saved recipes match this search.</p>}
    </div>
  </dialog>;
}

export function ComparisonShell() {
  const repositories = useAccountRepositories();
  const [workspace, setWorkspace] = useState<ComparisonWorkspace>(() => createComparisonWorkspace());
  const [currentRecovery, setCurrentRecovery] = useState<WorkspaceRecoveryState>();
  const [savedComparisons, setSavedComparisons] = useState<readonly ComparisonWorkspace[]>([]);
  const [recipes, setRecipes] = useState<readonly SavedRecipe[]>([]);
  const [recipeCandidates, setRecipeCandidates] = useState<readonly RecipeCandidate[]>([]);
  const [routes, setRoutes] = useState<readonly SavedRoute[]>([]);
  const [sourceRouteId, setSourceRouteId] = useState("");
  const [removedWorkspace, setRemovedWorkspace] = useState<ComparisonWorkspace>();
  const [status, setStatus] = useState("Opening comparison workspace…");
  const [pickerOpen, setPickerOpen] = useState(false);
  const [summaryOpen, setSummaryOpen] = useState(false);
  const [mode, setMode] = useState<"standard" | "advanced">("standard");
  const [verificationOpen, setVerificationOpen] = useState(false);
  const [verificationScenarioIds, setVerificationScenarioIds] = useState<readonly string[]>([]);
  const [userSettings, setUserSettings] = useState<LocalUserSettings>(() => createDefaultUserSettings());
  const [traceOpen, setTraceOpen] = useState(false);
  const [analysisView, setAnalysisView] = useState<"cards" | "overview" | "differences" | "matrix">("cards");
  const [baselineId, setBaselineId] = useState("");
  const [batchRepresentation, setBatchRepresentation] = useState<"original" | "common-batch">("original");
  const [commonBatchMass, setCommonBatchMass] = useState("5");
  const [matrixMode, setMatrixMode] = useState<MatrixDisplayMode>("final-mass");
  const [scenarioSort, setScenarioSort] = useState<"saved-order" | "name" | "total-mass" | "precursors" | "warnings" | "residual">("saved-order");
  const [hiddenScenarioIds, setHiddenScenarioIds] = useState<ReadonlySet<string>>(new Set());
  const [comparisonPrintMode, setComparisonPrintMode] = useState<"full-recipes" | "overview-only" | "precursor-matrix" | "overview-plus-compact-recipes">("full-recipes");
  const verificationTriggerRef = useRef<HTMLButtonElement>(null);
  const calculations = useMemo(() => calculateComparison(workspace), [workspace]);
  const difference = useMemo(() => compareScenarios(workspace.scenarios, calculations), [calculations, workspace.scenarios]);
  const displayedScenarios = useMemo(() => {
    const summaries = new Map(difference.summaries.map((item) => [item.scenarioId, item]));
    const visible = workspace.scenarios.filter((item) => !hiddenScenarioIds.has(item.id));
    if (scenarioSort === "saved-order") return visible;
    return [...visible].sort((left, right) => {
      const leftSummary = summaries.get(left.id), rightSummary = summaries.get(right.id);
      if (scenarioSort === "name") return left.name.localeCompare(right.name);
      if (scenarioSort === "precursors") return left.inputState.precursors.length - right.inputState.precursors.length;
      if (scenarioSort === "warnings") return (leftSummary?.warningCodes.length ?? Number.MAX_SAFE_INTEGER) - (rightSummary?.warningCodes.length ?? Number.MAX_SAFE_INTEGER);
      if (scenarioSort === "residual") return Number(leftSummary?.largestResidualMoles ?? Number.POSITIVE_INFINITY) - Number(rightSummary?.largestResidualMoles ?? Number.POSITIVE_INFINITY);
      return Number(leftSummary?.totalMassGrams ?? Number.POSITIVE_INFINITY) - Number(rightSummary?.totalMassGrams ?? Number.POSITIVE_INFINITY);
    });
  }, [difference.summaries, hiddenScenarioIds, scenarioSort, workspace.scenarios]);
  const analysis = useMemo(() => buildComparisonAnalysis(displayedScenarios, baselineId, batchRepresentation === "original" ? { kind: "original" } : { kind: "common-batch", targetMassGrams: commonBatchMass }), [baselineId, batchRepresentation, commonBatchMass, displayedScenarios]);

  const refresh = useCallback(async () => {
    const [comparisons, recipeList, routeList] = await Promise.all([repositories.listComparisons(), repositories.listRecipes(), repositories.listRoutes()]);
    const candidates = (await Promise.all(recipeList.map(async (recipe) => { const revision = await repositories.getRevision(recipe.currentRevisionId); if (!revision) return undefined; const calculation = buildWorkspaceCalculation(migrateWorkspaceAluminumInput(revision.inputState)); return { recipe, revision, warningCount: validResult(calculation)?.warnings.length ?? 0 }; }))).filter((item): item is RecipeCandidate => Boolean(item));
    setSavedComparisons(comparisons); setRecipes(recipeList); setRoutes(routeList); setRecipeCandidates(candidates);
  }, [repositories]);

  useEffect(() => { let active = true; void (async () => { await repositories.database.open(); const [recovery, settings] = await Promise.all([repositories.loadRecovery(), repositories.getSettings()]); if (active) { setCurrentRecovery(recovery); setUserSettings(settings); } await refresh(); if (active) setStatus("Comparison ready · no scenarios selected"); })().catch((error) => active && setStatus(`Comparison unavailable: ${error instanceof Error ? error.message : "local database error"}`)); return () => { active = false; }; }, [refresh, repositories]);

  useEffect(() => {
    const cloudChanged = () => { void refresh().then(() => setStatus("Cloud changes downloaded. Open scenarios remain unchanged; saved recipe and comparison lists were refreshed.")); };
    window.addEventListener("max-stoich:cloud-data-changed", cloudChanged);
    return () => window.removeEventListener("max-stoich:cloud-data-changed", cloudChanged);
  }, [refresh]);

  useEffect(() => {
    queueMicrotask(() => {
      const raw = sessionStorage.getItem("max-stoich:lab-comparison-staging");
      if (!raw) return;
      sessionStorage.removeItem("max-stoich:lab-comparison-staging");
      try {
        const staged = JSON.parse(raw) as Pick<ComparisonScenario, "name" | "inputState" | "validationStatus" | "source">;
        if (staged.source.kind !== "lab-library" || !staged.source.labId || !staged.source.labVersionId) throw new Error("Invalid lab comparison handoff.");
        setWorkspace((current) => addComparisonScenario(forkHistoricalComparison(current), migrateWorkspaceAluminumInput(staged.inputState), uniqueName(staged.name, current.scenarios), staged.source, staged.validationStatus));
        setStatus("Added a read-only lab publication snapshot to comparison. Temporary edits never modify the lab source.");
      } catch { setStatus("The selected lab publication could not be added to comparison."); }
    });
  }, []);

  const edit = (scenarioId: string, update: (input: WorkspaceRecipeState) => WorkspaceRecipeState) => setWorkspace((current) => updateScenario(forkHistoricalComparison(current), scenarioId, update));
  const existingRevisionIds = useMemo(() => new Set(workspace.scenarios.flatMap((item) => item.source.recipeRevisionId ? [item.source.recipeRevisionId] : [])), [workspace.scenarios]);

  const addSelectedRecipes = (recipeIds: readonly string[]) => {
    const selected = recipeIds.map((id) => recipeCandidates.find((item) => item.recipe.id === id)).filter((item): item is RecipeCandidate => Boolean(item));
    if (selected.some((item) => existingRevisionIds.has(item.revision.id))) { const message = "A selected recipe revision is already in this comparison. Use Duplicate on its scenario to add another copy."; setStatus(message); return message; }
    try {
      let next = forkHistoricalComparison(workspace);
      for (const item of selected) next = addComparisonScenario(next, migrateWorkspaceAluminumInput(item.revision.inputState), uniqueName(item.recipe.name, next.scenarios), { kind: "saved-recipe", recipeId: item.recipe.id, recipeRevisionId: item.revision.id }, item.recipe.validationStatus);
      setWorkspace(next); setPickerOpen(false); setStatus(`Added ${selected.length} saved recipe${selected.length === 1 ? "" : "s"}.`); return undefined;
    } catch (error) { const message = error instanceof Error ? error.message : "Recipes could not be added."; setStatus(message); return message; }
  };

  const addCurrentRecipe = () => {
    if (!currentRecovery) { setStatus("No current calculator recipe is available. Open the calculator and enter a recipe first."); return; }
    const input = migrateWorkspaceAluminumInput(currentRecovery.committedRecipe); const saved = recipes.find((item) => item.id === currentRecovery.baseRecipeId);
    try { setWorkspace((current) => addComparisonScenario(forkHistoricalComparison(current), input, uniqueName(saved?.name ?? "Unsaved calculation", current.scenarios), saved ? { kind: "working-recipe", recipeId: saved.id, recipeRevisionId: currentRecovery.baseRevisionId } : { kind: "working-recipe" }, saved?.validationStatus ?? "synthetic")); setStatus("Added the current calculator recipe."); } catch (error) { setStatus(error instanceof Error ? error.message : "Current recipe could not be added."); }
  };

  const addBlankScenario = () => {
    const input = blankWorkspaceState();
    try { setWorkspace((current) => addComparisonScenario(forkHistoricalComparison(current), input, uniqueName("Blank scenario", current.scenarios), { kind: "empty" }, "synthetic")); setStatus("Added a blank editable scenario."); } catch (error) { setStatus(error instanceof Error ? error.message : "Blank scenario could not be added."); }
  };

  const addRoute = async () => { const route = routes.find((item) => item.id === sourceRouteId); if (!route) return; const revision = await repositories.getRouteRevision(route.currentRevisionId); if (!revision) return; const base = workspace.scenarios[0]?.inputState ?? currentRecovery?.committedRecipe; if (!base) { setStatus("Add a recipe before adding a saved route."); return; } try { setWorkspace((current) => addComparisonScenario(current, migrateWorkspaceAluminumInput({ ...base, precursors: revision.precursors, ...revision.defaults }), uniqueName(route.name, current.scenarios), { kind: "saved-route", routeId: route.id, routeRevisionId: revision.id }, route.validationStatus)); setStatus(`Added ${route.name}.`); } catch (error) { setStatus(error instanceof Error ? error.message : "Route could not be added."); } };

  const saveComparison = async () => {
    if (workspace.scenarios.length < 2) { setStatus("Add at least one more scenario before saving this comparison."); return; }
    try {
      const scenarios = await Promise.all(workspace.scenarios.map(async (scenario) => { const calculation = calculations[scenario.id]!; const result = validResult(calculation); if (!result) return { ...scenario, historical: undefined }; const canonicalInput = canonicalizeWorkspaceScientificInput(scenario.inputState); const canonicalOutput = stableCanonicalize(JSON.parse(result.canonicalScientificRepresentation)); return { ...scenario, historical: { canonicalInput, canonicalOutput, inputDigest: await sha256Hex(canonicalInput), outputDigest: await sha256Hex(canonicalOutput), engineVersion: result.engineVersion, atomicWeightDataVersion: result.dataVersions.atomicWeights, calculatedAt: new Date().toISOString(), result: clone(result) } }; }));
      const name = workspace.name.trim() || "Recipe comparison";
      const saved: ComparisonWorkspace = { ...workspace, name, scenarios, historical: true, updatedAt: new Date().toISOString() };
      await repositories.saveComparison(saved);
      const persisted = await repositories.getComparison(saved.id);
      if (!persisted) throw new Error("The comparison was not found after saving.");
      setWorkspace(clone(persisted)); await refresh(); setStatus("Comparison saved");
    } catch (error) { setStatus(`Comparison was not saved. ${error instanceof Error ? error.message : "Local storage failed."} Your working scenarios are unchanged.`); }
  };

  const promote = async (scenario: ComparisonScenario) => { const result = validResult(calculations[scenario.id]!); if (!result) { setStatus("Only a valid scenario can be saved as a recipe."); return; } try { const source = scenario.source; const saved = await repositories.saveCalculatedRevision({ name: `${scenario.name} from comparison`, inputState: scenario.inputState, result, revisionNote: `Promoted from comparison ${workspace.name}`, ...(source.kind === "lab-library" && source.labId && source.labEntryId && source.labVersionId ? { copiedFromLab: { labId: source.labId, labName: source.labName ?? "Private lab", entryId: source.labEntryId, entryTitle: source.labEntryTitle ?? scenario.name, publicationVersionId: source.labVersionId, versionNumber: source.labVersionNumber ?? 1, publisherName: source.labPublisherName ?? "Lab member", publishedAt: source.labPublishedAt ?? new Date().toISOString(), copiedAt: new Date().toISOString() } } : {}) }); setStatus(`Saved ${saved.recipe.name}, revision 1`); await refresh(); } catch (error) { setStatus(`Recipe was not saved. ${error instanceof Error ? error.message : "Local storage failed."}`); } };
  const saveRoute = async (scenario: ComparisonScenario) => { try { await repositories.saveRouteRevision({ name: `${scenario.name} route`, inputState: scenario.inputState, validationStatus: scenario.validationStatus }); setStatus(`Saved ${scenario.name} as an independent route.`); await refresh(); } catch (error) { setStatus(`Route was not saved. ${error instanceof Error ? error.message : "Local storage failed."}`); } };
  const exportComparison = async () => { try { const envelope = await createOwnedRecordExport("max-stoich-comparison-workspace", { comparison: workspace }); downloadText(safeExportFilename(workspace.name, "json"), JSON.stringify(envelope, null, 2), "application/json;charset=utf-8"); setStatus("Exported a digest-protected MAX Stoich comparison record."); } catch (error) { setStatus(`Comparison export failed. ${error instanceof Error ? error.message : "The file could not be created."}`); } };
  const copyAnalysis = async (kind: "overview" | "matrix") => { await navigator.clipboard.writeText(kind === "overview" ? comparisonOverviewTsv(analysis) : precursorMatrixTsv(analysis, matrixMode)); setStatus(`Copied comparison ${kind}.`); };
  const exportAnalysisCsv = () => { const text = (analysisView === "matrix" ? precursorMatrixTsv(analysis, matrixMode) : comparisonOverviewTsv(analysis)).replaceAll("\t", ","); downloadText(safeExportFilename(`${workspace.name}-${analysisView}`, "csv"), text, "text/csv;charset=utf-8"); setStatus("Exported the selected comparison representation as CSV."); };

  const summaryEntries: readonly WeighingSummaryEntry[] = workspace.scenarios.map((scenario) => { const calculation = calculations[scenario.id]!; const result = validResult(calculation); const sourceStatus = scenario.source.kind === "saved-recipe" ? `Saved recipe revision ${recipeCandidates.find((item) => item.revision.id === scenario.source.recipeRevisionId)?.revision.revisionNumber ?? "—"}` : scenario.source.kind.replaceAll("-", " "); if (!result) return { unavailable: { title: scenario.name, sourceStatus, reason: calculationReason(calculation), validationStatus: scenario.validationStatus } }; return { summary: buildWeighingSummary({ title: scenario.name, sourceStatus, inputState: scenario.inputState, result, validationStatus: scenario.validationStatus, isHistorical: Boolean(scenario.historical) }) }; });
  const verificationEntries: readonly CalculationVerificationEntry[] = workspace.scenarios.filter((scenario) => verificationScenarioIds.length === 0 || verificationScenarioIds.includes(scenario.id)).map((scenario) => { const calculation = calculations[scenario.id]!; const result = validResult(calculation); const unavailable = { title: scenario.name, reason: calculationReason(calculation) }; return result ? { verification: buildCalculationVerification({ title: scenario.name, inputState: scenario.inputState, result }) } : { unavailable }; });
  const printComparison = () => {
    if (!displayedScenarios.length) { setStatus("Print unavailable: show at least one scenario."); return; }
    const visibleEntries = displayedScenarios.map((scenario) => {
      const calculation = analysis.calculations[scenario.id]!;
      const result = validResult(calculation);
      if (!result) return { id: scenario.id, unavailable: { title: scenario.name, sourceStatus: scenario.source.kind.replaceAll("-", " "), reason: calculationReason(calculation), validationStatus: scenario.validationStatus } } as const;
      return { id: scenario.id, summary: buildWeighingSummary({ title: scenario.name, sourceStatus: scenario.source.kind.replaceAll("-", " "), inputState: scenario.inputState, result, validationStatus: scenario.validationStatus, isHistorical: Boolean(scenario.historical) }) } as const;
    });
    const includeRecipes = comparisonPrintMode === "full-recipes" || comparisonPrintMode === "overview-plus-compact-recipes";
    try { launchPrintJob(createPrintJob({ kind: "comparison", title: workspace.name || "Recipe comparison", singleRecipeDetailed: false, settings: comparisonPrintMode === "overview-plus-compact-recipes" ? { ...userSettings.print, density: "ultra-compact", recipesPerPage: 6 } : userSettings.print, entries: includeRecipes ? visibleEntries : [], comparisonContent: { mode: comparisonPrintMode, analysis, matrixMode } })); setStatus(`Opened the dedicated ${comparisonPrintMode.replaceAll("-", " ")} print view in visible scenario order.`); }
    catch (error) { setStatus(`Print unavailable: ${error instanceof Error ? error.message : "print state could not be created"}`); }
  };

  return <main className="comparison-workspace min-h-screen bg-slate-100 text-slate-950">
    <div className="comparison-mode-bar flex justify-end gap-2 border-b bg-white px-4 py-2" aria-label="Comparison detail mode" role="group"><button className="rounded border px-3 py-1 font-semibold disabled:text-slate-400" disabled={!workspace.scenarios.length} onClick={printComparison}>Print comparison</button><button aria-pressed={mode === "standard"} className={`rounded-l border px-3 py-1 ${mode === "standard" ? "bg-slate-900 text-white" : ""}`} onClick={() => setMode("standard")}>Standard</button><button aria-pressed={mode === "advanced"} className={`rounded-r border px-3 py-1 ${mode === "advanced" ? "bg-slate-900 text-white" : ""}`} onClick={() => setMode("advanced")}>Advanced</button></div>
    <header className="comparison-command-bar sticky top-0 z-20 flex flex-wrap items-center gap-2 border-b bg-white p-3 shadow-sm"><Link aria-label="MAX Stoich calculator" className="comparison-brand-link font-bold" href="/workspace"><SiteBrand /></Link><span aria-hidden="true" className="text-slate-400">·</span><h1 className="mr-auto text-lg font-bold">Recipe comparison</h1><div className="comparison-primary-actions flex flex-wrap gap-2"><button className="rounded bg-teal-800 px-3 py-2 font-semibold text-white disabled:bg-slate-400" disabled={workspace.scenarios.length >= MAX_COMPARISON_SCENARIOS} title={workspace.scenarios.length >= MAX_COMPARISON_SCENARIOS ? `Maximum ${MAX_COMPARISON_SCENARIOS} scenarios reached` : undefined} onClick={() => setPickerOpen(true)}>Add saved recipes</button><button className="rounded border px-3 py-2 font-semibold" disabled={workspace.scenarios.length >= MAX_COMPARISON_SCENARIOS} title={workspace.scenarios.length >= MAX_COMPARISON_SCENARIOS ? `Maximum ${MAX_COMPARISON_SCENARIOS} scenarios reached` : undefined} onClick={addCurrentRecipe}>Add current recipe</button><button className="rounded bg-slate-900 px-3 py-2 font-semibold text-white" onClick={() => void saveComparison()}>Save comparison</button></div><div className="comparison-secondary-actions flex flex-wrap gap-2"><button className="rounded border px-3 py-2" disabled={workspace.scenarios.length >= MAX_COMPARISON_SCENARIOS} title={workspace.scenarios.length >= MAX_COMPARISON_SCENARIOS ? `Maximum ${MAX_COMPARISON_SCENARIOS} scenarios reached` : undefined} onClick={addBlankScenario}>Add blank scenario</button><button className="rounded border px-3 py-2 disabled:text-slate-400" disabled={!workspace.scenarios.length} onClick={() => setSummaryOpen(true)}>View comparison summaries</button><details className="relative"><summary className="cursor-pointer rounded border px-3 py-2">More</summary><div className="absolute right-0 z-30 mt-1 grid w-64 gap-2 rounded border bg-white p-3 shadow-xl"><button className="rounded border px-2 py-1 text-left disabled:text-slate-400" disabled={!workspace.scenarios.length} onClick={() => void exportComparison()}>Export comparison JSON</button><Link className="rounded border px-2 py-1" href="/settings">Layouts &amp; data</Link><select aria-label="Saved route source" className="rounded border px-2 py-1" onChange={(event) => setSourceRouteId(event.target.value)} value={sourceRouteId}><option value="">Saved route…</option>{routes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="rounded border px-2 py-1 text-left" disabled={!sourceRouteId || workspace.scenarios.length >= MAX_COMPARISON_SCENARIOS} onClick={() => void addRoute()}>Add saved route</button></div></details></div><p aria-live="polite" className="comparison-status w-full text-sm font-medium">{status}</p></header>

    <section aria-label="Comparison identity" className="mx-auto flex max-w-[1600px] flex-wrap items-end gap-3 border-b bg-white p-4"><label className="text-sm font-medium">Comparison name<input className="ml-2 rounded border px-2 py-1" onChange={(event) => setWorkspace((current) => ({ ...current, name: event.target.value, historical: false }))} value={workspace.name} /></label><select aria-label="Open saved comparison" className="rounded border px-2 py-1" onChange={(event) => { const saved = savedComparisons.find((item) => item.id === event.target.value); if (saved) { setWorkspace(clone(saved)); setRemovedWorkspace(undefined); setStatus("Viewing saved comparison exactly as stored."); } }} value=""><option value="">Open saved comparison…</option>{savedComparisons.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>{removedWorkspace && <button className="rounded border px-2 py-1" onClick={() => { setWorkspace(removedWorkspace); setRemovedWorkspace(undefined); setStatus("Restored the removed scenario."); }}>Undo scenario removal</button>}</section>
    {workspace.scenarios.length > 0 && <section className="mx-auto max-w-[1600px] border-b bg-white p-4" aria-label="Comparison analysis controls">
      <div className="flex flex-wrap gap-2" role="group" aria-label="Comparison view">{(["cards", "overview", "differences", "matrix"] as const).map((view) => <button aria-pressed={analysisView === view} className={`rounded border px-3 py-2 font-semibold ${analysisView === view ? "bg-slate-900 text-white" : ""}`} key={view} onClick={() => setAnalysisView(view)}>{view === "cards" ? "Recipe cards" : view === "overview" ? "Summary metrics" : view === "differences" ? "Difference table" : "Precursor matrix"}</button>)}</div>
      <div className="mt-3 flex flex-wrap items-end gap-3"><label className="text-sm font-semibold">Baseline<select className="mt-1 block rounded border px-3 py-2" disabled={!analysis.scenarios.length} onChange={(event) => setBaselineId(event.target.value)} value={analysis.baselineId}>{analysis.scenarios.map((scenario) => <option key={scenario.id} value={scenario.id}>{scenario.name}</option>)}</select></label><label className="text-sm font-semibold">Batch representation<select className="mt-1 block rounded border px-3 py-2" onChange={(event) => setBatchRepresentation(event.target.value as "original" | "common-batch")} value={batchRepresentation}><option value="original">Original saved batch masses</option><option value="common-batch">Common comparison batch</option></select></label>{batchRepresentation === "common-batch" && <label className="text-sm font-semibold">Common target batch (g)<input className="mt-1 block w-32 rounded border px-3 py-2" inputMode="decimal" onChange={(event) => setCommonBatchMass(event.target.value)} value={commonBatchMass} /></label>}<label className="text-sm font-semibold">Scenario order<select className="mt-1 block rounded border px-3 py-2" onChange={(event) => setScenarioSort(event.target.value as typeof scenarioSort)} value={scenarioSort}><option value="saved-order">Saved order</option><option value="name">Name</option><option value="total-mass">Total mass</option><option value="precursors">Number of precursors</option><option value="warnings">Warning severity</option><option value="residual">Verification residual</option></select></label>{analysisView === "matrix" && <label className="text-sm font-semibold">Matrix values<select className="mt-1 block rounded border px-3 py-2" onChange={(event) => setMatrixMode(event.target.value as MatrixDisplayMode)} value={matrixMode}><option value="final-mass">Final mass</option><option value="molar-ratio">Molar ratio</option><option value="presence">Presence only</option><option value="difference-from-baseline">Difference from baseline</option></select></label>}<label className="text-sm font-semibold">Comparison print content<select className="mt-1 block rounded border px-3 py-2" onChange={(event) => setComparisonPrintMode(event.target.value as typeof comparisonPrintMode)} value={comparisonPrintMode}><option value="full-recipes">Full recipes</option><option value="overview-only">Comparison overview only</option><option value="precursor-matrix">Precursor matrix</option><option value="overview-plus-compact-recipes">Overview plus compact recipes</option></select></label><button className="rounded border px-3 py-2" onClick={() => void copyAnalysis(analysisView === "matrix" ? "matrix" : "overview")}>Copy {analysisView === "matrix" ? "matrix" : "overview"}</button><button className="rounded border px-3 py-2" onClick={exportAnalysisCsv}>Export CSV</button></div>
      <fieldset className="mt-3"><legend className="text-sm font-semibold">Temporarily shown scenarios</legend><div className="mt-1 flex flex-wrap gap-3">{workspace.scenarios.map((scenario) => <label className="flex items-center gap-2 text-sm" key={scenario.id}><input checked={!hiddenScenarioIds.has(scenario.id)} onChange={(event) => setHiddenScenarioIds((current) => { const next = new Set(current); if (event.target.checked) next.delete(scenario.id); else next.add(scenario.id); return next; })} type="checkbox" />{scenario.name}</label>)}</div><p className="mt-1 text-xs">Hidden scenarios remain in the saved comparison and can be shown again at any time.</p></fieldset>
      <p className="mt-2 text-sm font-semibold">{analysis.representationLabel}. The baseline and normalization are presentation-only and never modify saved recipes.</p>
    </section>}

    {workspace.scenarios.length === 0 ? <section className="mx-auto mt-10 max-w-2xl rounded-xl border-2 border-dashed border-slate-400 bg-white p-10 text-center"><h2 className="text-2xl font-bold">No recipes selected for comparison</h2><p className="mt-2 text-slate-600">Add saved recipes, add the current calculator recipe, or create a blank comparison scenario.</p><div className="mt-6 flex flex-wrap justify-center gap-3"><button className="rounded bg-teal-800 px-4 py-3 font-semibold text-white" onClick={() => setPickerOpen(true)}>Add saved recipes</button><button className="rounded border px-4 py-3 font-semibold" onClick={addCurrentRecipe}>Add current recipe</button><button className="rounded border px-4 py-3 font-semibold" onClick={addBlankScenario}>Add blank scenario</button></div></section> : <>
      {workspace.scenarios.length === 1 && <p className="mx-auto mt-4 max-w-[1600px] rounded border border-blue-300 bg-blue-50 p-3 font-semibold">Add at least one more scenario to compare results.</p>}
      {analysisView === "overview" && <section className="mx-auto my-4 max-w-[1600px] overflow-x-auto rounded border bg-white p-4"><h2 className="text-lg font-bold">Comparison overview</h2><table className="mt-3 w-full border-collapse text-sm"><thead><tr><th className="border p-2 text-left">Scenario</th><th className="border p-2">Target / adjusted feed</th><th className="border p-2">Target batch</th><th className="border p-2">Total weighing</th><th className="border p-2">Precursors</th><th className="border p-2">Largest residual</th><th className="border p-2">Warnings</th><th className="border p-2">Validation</th></tr></thead><tbody>{analysis.scenarios.map((scenario) => { const summary = analysis.difference.summaries.find((item) => item.scenarioId === scenario.id)!; return <tr key={scenario.id}><th className="border p-2 text-left">{scenario.name}{scenario.id === analysis.baselineId && <span className="ml-2 rounded bg-teal-100 px-2 py-1 text-xs">Baseline</span>}</th><td className="border p-2 font-mono">{scenario.inputState.targetFormula}</td><td className="border p-2 text-right">{scenario.inputState.requestedMassGrams} g</td><td className="border p-2 text-right">{summary.totalMassGrams ?? "Unavailable"}{summary.totalMassGrams && " g"}</td><td className="border p-2 text-right">{scenario.inputState.precursors.length}</td><td className="border p-2 text-right">{summary.largestResidualMoles ?? "Unavailable"}</td><td className="border p-2 text-right">{summary.warningCodes.length}</td><td className="border p-2">{scenario.validationStatus}</td></tr>; })}</tbody></table></section>}
      {analysisView === "differences" && <section className="mx-auto my-4 max-w-[1600px] overflow-x-auto rounded border bg-white p-4"><h2 className="text-lg font-bold">Differences relative to baseline</h2><p className="mt-1 text-sm">Signed arithmetic differences are descriptive; they do not rank scientific quality.</p><table className="mt-3 w-full border-collapse text-sm"><thead><tr><th className="border p-2 text-left">Scenario</th><th className="border p-2">Total mass difference</th><th className="border p-2">Added precursors</th><th className="border p-2">Removed precursors</th><th className="border p-2">Warning differences</th></tr></thead><tbody>{analysis.scenarios.map((scenario) => { const baseline = analysis.difference.summaries.find((item) => item.scenarioId === analysis.baselineId); const current = analysis.difference.summaries.find((item) => item.scenarioId === scenario.id); const delta = signedDifference(current?.totalMassGrams, baseline?.totalMassGrams); const added = analysis.difference.rows.filter((row) => row.cells[scenario.id] && !row.cells[analysis.baselineId]).map((row) => row.cells[scenario.id]!.formula); const removed = analysis.difference.rows.filter((row) => !row.cells[scenario.id] && row.cells[analysis.baselineId]).map((row) => row.cells[analysis.baselineId]!.formula); return <tr key={scenario.id}><th className="border p-2 text-left">{scenario.name}{scenario.id === analysis.baselineId && " · Baseline"}</th><td className="border p-2 text-right">{scenario.id === analysis.baselineId ? "Baseline" : delta.value ? `${delta.value} g${delta.percent ? ` (${delta.percent})` : ""}` : "Unavailable"}</td><td className="border p-2">{added.join(", ") || "None"}</td><td className="border p-2">{removed.join(", ") || "None"}</td><td className="border p-2">{current?.warningCodes.filter((code) => !baseline?.warningCodes.includes(code)).join(", ") || "None"}</td></tr>; })}</tbody></table></section>}
      {analysisView === "matrix" && <section className="mx-auto my-4 max-w-[1600px] overflow-x-auto rounded border bg-white p-4"><h2 className="text-lg font-bold">Precursor matrix</h2><table className="mt-3 w-full border-collapse text-sm"><thead><tr><th className="border p-2 text-left">Precursor</th>{analysis.scenarios.map((scenario) => <th className="border p-2" key={scenario.id}>{scenario.name}{scenario.id === analysis.baselineId && <span className="block text-xs">Baseline</span>}</th>)}</tr></thead><tbody>{analysis.difference.rows.map((row) => { const baselineCell = row.cells[analysis.baselineId]; return <tr key={row.key}><th className="border p-2 text-left font-mono">{Object.values(row.cells).find(Boolean)?.formula ?? row.key}</th>{analysis.scenarios.map((scenario) => { const cell = row.cells[scenario.id]; const text = !cell ? "Missing" : !cell.finalMassGrams ? "Unavailable" : matrixMode === "presence" ? (Number(cell.finalMassGrams) === 0 ? "Zero" : "Present") : matrixMode === "molar-ratio" ? cell.solverQuantityExact ?? "Unavailable" : matrixMode === "difference-from-baseline" ? (scenario.id === analysis.baselineId ? "Baseline" : signedDifference(cell.finalMassGrams, baselineCell?.finalMassGrams).value ?? "Unavailable") : `${cell.finalMassGrams} g`; return <td className="border p-2 text-right" key={scenario.id}>{text}</td>; })}</tr>; })}</tbody></table></section>}
      {analysisView === "cards" && <div className="mx-auto grid max-w-[1600px] gap-4 p-4 lg:grid-cols-2">{displayedScenarios.map((scenario) => { const calculation = calculations[scenario.id]!; const result = validResult(calculation); return <section aria-label={`${scenario.name} scenario`} className={`rounded border bg-white p-4 shadow-sm ${scenario.id === analysis.baselineId ? "border-4 border-teal-700" : ""}`} key={scenario.id}><div className="flex flex-wrap items-center gap-2">{scenario.id === analysis.baselineId && <span className="rounded bg-teal-100 px-2 py-1 text-xs font-bold">Baseline</span>}<input aria-label={`${scenario.name} name`} className="min-w-0 flex-1 rounded border px-2 py-1 font-semibold" onChange={(event) => setWorkspace((current) => ({ ...current, scenarios: current.scenarios.map((item) => item.id === scenario.id ? { ...item, name: event.target.value } : item), historical: false }))} value={scenario.name} /><span className="text-xs">{calculation.state} · {scenario.validationStatus}</span><button className="rounded border px-2 py-1 text-xs" disabled={workspace.scenarios.length >= MAX_COMPARISON_SCENARIOS} onClick={() => { try { setWorkspace((current) => duplicateScenario(current, scenario.id)); setStatus(`Duplicated ${scenario.name}.`); } catch (error) { setStatus(error instanceof Error ? error.message : "Cannot duplicate scenario"); } }}>Duplicate</button><button className="rounded border border-red-300 px-2 py-1 text-xs" onClick={() => { setRemovedWorkspace(workspace); setWorkspace((current) => removeScenario(current, scenario.id)); setStatus(`Removed ${scenario.name}.`); }}>Remove</button></div><p className="mt-1 text-xs">Source: {scenario.source.kind}{scenario.source.recipeRevisionId ? ` · revision ${recipeCandidates.find((item) => item.revision.id === scenario.source.recipeRevisionId)?.revision.revisionNumber ?? "—"}` : ""}{scenario.historical ? ` · historical engine ${scenario.historical.engineVersion}` : " · current engine"}</p>
        <div className="mt-3 grid gap-2 sm:grid-cols-2"><label className="text-xs sm:col-span-2">Scenario target formula<input aria-label={`${scenario.name} target formula`} className="mt-1 w-full rounded border px-2 py-1 font-mono" onChange={(event) => edit(scenario.id, (input) => { const targetFormula = event.target.value; const normalized = input.normalizeLeadingSiteRatios ? normalizeLeadingSiteRatioGroup(targetFormula, { enabled: true, expectedSite: "M" }) : undefined; return { ...input, targetFormula, aluminumPerFormula: aluminumCoefficientForTargetChange(input, targetFormula), siteComposition: normalized?.success ? normalized.value.explicitSiteModel : undefined, radiusDescriptorConfig: undefined, presetId: "custom" }; })} value={scenario.inputState.targetFormula} /></label><label className="text-xs">Batch mass<input className="mt-1 w-full rounded border px-2 py-1" onChange={(event) => edit(scenario.id, (input) => ({ ...input, requestedMassGrams: event.target.value }))} value={scenario.inputState.requestedMassGrams} /></label><label className="text-xs">Aluminum per formula<input className="mt-1 w-full rounded border px-2 py-1" onChange={(event) => edit(scenario.id, (input) => ({ ...input, aluminumPerFormula: event.target.value }))} value={scenario.inputState.aluminumPerFormula ?? ""} /></label><label className="text-xs">Handling loss %<input className="mt-1 w-full rounded border px-2 py-1" onChange={(event) => edit(scenario.id, (input) => ({ ...input, handlingLossPercent: event.target.value }))} value={scenario.inputState.handlingLossPercent} /></label></div>
        <div className="mt-3 space-y-2">{scenario.inputState.precursors.map((precursor, index) => <div className="grid grid-cols-[1fr_6rem_auto] gap-2" key={precursor.id}><input aria-label={`${scenario.name} precursor ${index + 1} formula`} className="rounded border px-2 font-mono" onChange={(event) => edit(scenario.id, (input) => ({ ...input, precursors: input.precursors.map((item) => item.id === precursor.id ? { ...item, formula: event.target.value, name: event.target.value || item.name } : item) }))} value={precursor.formula} /><input aria-label={`${scenario.name} precursor ${index + 1} purity`} className="rounded border px-2" onChange={(event) => edit(scenario.id, (input) => ({ ...input, precursors: input.precursors.map((item) => item.id === precursor.id ? { ...item, purityPercent: event.target.value } : item) }))} value={precursor.purityPercent} /><button aria-label={`Remove ${precursor.name} from ${scenario.name}`} className="rounded border border-red-300 px-2 text-xs" onClick={() => edit(scenario.id, (input) => ({ ...input, precursors: input.precursors.filter((item) => item.id !== precursor.id) }))}>Remove</button></div>)}<button className="rounded border px-3 py-2 text-sm" onClick={() => edit(scenario.id, (input) => ({ ...input, precursors: [...input.precursors, blankPrecursor(input.precursors.length + 1)] }))}>Add precursor</button></div>
        {result ? <div className="mt-4"><WeighingSummaryCard advanced={mode === "advanced"} headingLevel={3} summary={buildWeighingSummary({ title: `${scenario.name} results`, sourceStatus: scenario.source.kind === "saved-recipe" ? `Saved recipe · revision ${recipeCandidates.find((item) => item.revision.id === scenario.source.recipeRevisionId)?.revision.revisionNumber ?? "—"}` : scenario.source.kind.replaceAll("-", " "), inputState: scenario.inputState, result, validationStatus: scenario.validationStatus, isHistorical: Boolean(scenario.historical) })} /></div> : <div className="mt-3 rounded border border-red-300 bg-red-50 p-3 text-sm" role="alert"><strong>Action required — No valid weighing result.</strong><p>Reason: {calculationReason(calculation)}</p><details className="mt-2"><summary>Technical details</summary><ul>{calculation.errors.map((item) => <li key={`${item.code}-${item.fieldPath}`}>{item.message}</li>)}</ul></details></div>}
        {mode === "advanced" && <>{<AtomicRadiusPanel config={scenario.inputState.radiusDescriptorConfig} onConfigChange={(radiusDescriptorConfig) => edit(scenario.id, (input) => ({ ...input, radiusDescriptorConfig }))} onConfigureSites={() => setStatus("Configure explicit crystallographic sites in the calculator; flat formulas are never used for site inference.")} siteModel={scenario.inputState.siteComposition} />}{result && <details className="mt-3 rounded border bg-slate-50 p-3"><summary className="font-semibold">Solver, balance, residuals, and provenance</summary><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="font-semibold">Solver</dt><dd>{result.solver?.backend.name ?? "Unavailable"} · {result.solver?.status ?? result.status}</dd></div><div><dt className="font-semibold">Matrix / rank</dt><dd>{result.matrix ? `${result.matrix.dimensions.rows} × ${result.matrix.dimensions.columns} · rank ${result.matrix.analysis.matrixRank} · ${result.matrix.analysis.rankConsistency}` : "Unavailable"}</dd></div><div><dt className="font-semibold">Adjustments</dt><dd>{result.resolvedAdjustmentOrder.length ? result.resolvedAdjustmentOrder.join(" → ") : "None"}</dd></div><div><dt className="font-semibold">Residuals</dt><dd>{result.realizedElements.length} elemental residuals recorded</dd></div><div><dt className="font-semibold">Trace / provenance</dt><dd>{result.trace.length} trace steps · engine {result.engineVersion} · atomic weights {result.dataVersions.atomicWeights}</dd></div></dl></details>}</>}
        <div className="mt-3 flex flex-wrap gap-2"><button className="rounded border px-2 py-1 text-sm" onClick={() => void promote(scenario)}>Save as recipe</button><button className="rounded border px-2 py-1 text-sm" onClick={() => void saveRoute(scenario)}>Save as route</button>{scenario.historical && <button className="rounded border px-2 py-1 text-sm" onClick={() => edit(scenario.id, (input) => input)}>Recalculate selected</button>}</div>
      </section>; })}</div>}
      <section aria-labelledby="difference-heading" className="mx-auto mb-8 max-w-[1600px] overflow-x-auto rounded border bg-white p-4"><h2 className="text-lg font-semibold" id="difference-heading">Deterministic differences</h2><p className="mt-1 text-sm">These labels compare calculated values only; they do not identify an experimentally superior or more stable route.</p><div className="mt-3 flex flex-wrap gap-2">{workspace.selectedMetrics.map((metric) => <span className="rounded bg-slate-100 px-2 py-1 text-xs" key={metric}>{metric.replaceAll("-", " ")}: {difference.metricLeaders[metric]?.map((id) => workspace.scenarios.find((item) => item.id === id)?.name).join(", ")}</span>)}</div></section>
    </>}

    {workspace.scenarios.length > 0 && <section aria-label="Comparison calculation details" className="comparison-verification-actions border-b bg-white px-4 py-3"><strong>Calculation details</strong><p className="mt-1 text-xs text-slate-600">Audit mole-to-mass conversion, rounding, elemental reconciliation, and each scenario trace.</p><div className="mt-2 flex flex-wrap gap-2"><button className="rounded border border-slate-400 px-3 py-2 font-semibold disabled:text-slate-400" disabled={!workspace.scenarios.some((scenario) => Boolean(validResult(calculations[scenario.id]!)))} onClick={() => { setVerificationScenarioIds([]); setVerificationOpen(true); }} ref={verificationTriggerRef}>Verify calculations</button><button aria-expanded={traceOpen} className="rounded border border-slate-400 px-3 py-2 font-semibold" onClick={() => setTraceOpen((value) => !value)}>{traceOpen ? "Close calculation trace" : "Open calculation trace"}</button>{workspace.scenarios.map((scenario) => <button className="rounded border px-3 py-2 text-sm disabled:text-slate-400" disabled={!validResult(calculations[scenario.id]!)} key={scenario.id} onClick={(event) => { verificationTriggerRef.current = event.currentTarget; setVerificationScenarioIds([scenario.id]); setVerificationOpen(true); }}>Verify {scenario.name}</button>)}</div>{traceOpen && <div className="mt-3 grid gap-3">{workspace.scenarios.map((scenario) => { const result = validResult(calculations[scenario.id]!); return <section className="max-h-72 overflow-auto rounded border bg-slate-50 p-3" key={scenario.id}><h3 className="font-semibold">{scenario.name}</h3>{result ? <ol className="mt-2 space-y-2 text-sm">{result.trace.map((step, index) => <li className="border-b pb-2" key={`${step.stepCode}-${index}`}><strong className="font-mono">{step.stepCode}</strong> · {step.description}</li>)}</ol> : <p className="mt-2 text-sm">No valid calculation trace: {calculationReason(calculations[scenario.id]!)}</p>}</section>; })}</div>}</section>}
    <RecipePicker candidates={recipeCandidates} capacity={MAX_COMPARISON_SCENARIOS - workspace.scenarios.length} existing={existingRevisionIds} onAdd={addSelectedRecipes} onClose={() => setPickerOpen(false)} open={pickerOpen} />
    <WeighingSummaryDialog entries={summaryEntries} onClose={() => setSummaryOpen(false)} onOpenVerification={() => { setSummaryOpen(false); setVerificationScenarioIds([]); setVerificationOpen(true); }} onPrint={printComparison} onStatus={setStatus} open={summaryOpen && workspace.scenarios.length > 0} title={workspace.name || "Comparison weighing summaries"} />
    <CalculationVerificationDialog entries={verificationEntries} onClose={() => { setVerificationOpen(false); requestAnimationFrame(() => verificationTriggerRef.current?.focus()); }} onStatus={setStatus} open={verificationOpen && workspace.scenarios.length > 0} title={verificationScenarioIds.length === 1 ? "Scenario calculation verification" : "Comparison calculation verification"} />
  </main>;
}
