"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { normalizeLeadingSiteRatioGroup } from "@max-stoich/chemistry-engine";
import { compareScenarios } from "@/lib/comparison/difference";
import { addComparisonScenario, calculateComparison, createComparisonWorkspace, duplicateScenario, MAX_COMPARISON_SCENARIOS, removeScenario, updateScenario } from "@/lib/comparison/model";
import { canonicalizeWorkspaceScientificInput, sha256Hex, stableCanonicalize } from "@/lib/persistence/canonical";
import { createOwnedRecordExport } from "@/lib/persistence/backup";
import { downloadText, safeExportFilename } from "@/lib/export/laboratory-export";
import { LocalDataRepositories } from "@/lib/persistence/repositories";
import type { ComparisonScenario, ComparisonWorkspace, RecipeRevision, SavedRecipe, SavedRoute, WorkspaceRecoveryState } from "@/lib/persistence/entities";
import type { WorkspaceCalculationState, WorkspaceRecipeState } from "@/lib/workspace/adapter";
import { buildWorkspaceCalculation } from "@/lib/workspace/adapter";
import { aluminumCoefficientForTargetChange, migrateWorkspaceAluminumInput } from "@/lib/workspace/aluminum-feed";
import { blankWorkspaceState } from "@/components/workspace/workspace-shell";
import { WeighingSummaryCard, WeighingSummaryDialog, type WeighingSummaryEntry } from "@/components/weighing-summary/weighing-summary-dialog";
import { AtomicRadiusPanel } from "@/components/descriptor-panel/atomic-radius-panel";
import { CalculationVerificationDialog, type CalculationVerificationEntry } from "@/components/verification/calculation-verification-dialog";
import { buildCalculationVerification } from "@/lib/presentation/calculation-verification";
import { buildWeighingSummary } from "@/lib/presentation/weighing-summary";
import { createDefaultUserSettings, type LocalUserSettings } from "@/lib/settings/user-settings";
import { createPrintJob, launchPrintJob } from "@/lib/print/print-model";

const clone = <T,>(value: T): T => structuredClone(value);
const forkHistoricalComparison = (value: ComparisonWorkspace): ComparisonWorkspace => { if (!value.historical) return value; const now = new Date().toISOString(); return { ...value, id: `comparison-${crypto.randomUUID()}`, name: `${value.name} (current engine)`, historical: false, createdAt: now, updatedAt: now }; };
const validResult = (calculation: WorkspaceCalculationState) => calculation.state === "valid" || calculation.state === "valid-with-warnings" ? calculation.result : undefined;
const calculationReason = (calculation: WorkspaceCalculationState) => calculation.errors.find((item) => item.code.includes("MISSING_REQUIRED_ELEMENT_SOURCE"))?.message ?? calculation.errors[0]?.message ?? "The current inputs do not produce a valid result.";
const blankPrecursor = (index: number) => ({ id: `precursor-${crypto.randomUUID()}`, name: `Precursor ${index}`, formula: "", purityPercent: "100", constraintMode: "solver" as const, fixedValue: "", minimum: "", maximum: "", ratioDenominatorId: "", numeratorRatio: "1", denominatorRatio: "1", molarMassOverride: "", molarMassOverrideSource: "" });

function uniqueName(name: string, scenarios: readonly ComparisonScenario[]): string {
  if (!scenarios.some((item) => item.name === name)) return name;
  let suffix = 2; while (scenarios.some((item) => item.name === `${name} (${suffix})`)) suffix += 1;
  return `${name} (${suffix})`;
}

interface RecipeCandidate { readonly recipe: SavedRecipe; readonly revision: RecipeRevision; readonly warningCount: number }

function RecipePicker({ open, candidates, existing, capacity, onClose, onAdd }: { open: boolean; candidates: readonly RecipeCandidate[]; existing: ReadonlySet<string>; capacity: number; onClose: () => void; onAdd: (ids: readonly string[]) => string | undefined }) {
  const ref = useRef<HTMLDialogElement>(null); const closeRef = useRef<HTMLButtonElement>(null);
  const [search, setSearch] = useState(""); const [selected, setSelected] = useState<ReadonlySet<string>>(new Set()); const [message, setMessage] = useState("");
  useEffect(() => { const dialog = ref.current; if (!dialog) return; if (open && !dialog.open) { setSelected(new Set()); setSearch(""); setMessage(""); dialog.showModal(); closeRef.current?.focus(); } else if (!open && dialog.open) dialog.close(); }, [open]);
  const visible = candidates.filter((item) => item.recipe.name.toLowerCase().includes(search.trim().toLowerCase()));
  const toggle = (id: string) => setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });
  const add = () => { if (!selected.size) { setMessage("Select at least one saved recipe."); return; } if (selected.size > capacity) { setMessage(`Only ${capacity} more scenario${capacity === 1 ? "" : "s"} can be added.`); return; } const rejection = onAdd([...selected]); if (rejection) setMessage(rejection); };
  return <dialog aria-labelledby="recipe-picker-title" className="m-auto max-h-[90vh] w-[min(94vw,70rem)] overflow-auto rounded-xl border-2 border-slate-800 p-0 backdrop:bg-slate-950/60" onCancel={(event) => { event.preventDefault(); onClose(); }} onClose={onClose} ref={ref}>
    <header className="sticky top-0 z-10 flex flex-wrap items-center gap-2 border-b bg-white p-4"><div className="mr-auto"><h2 className="text-xl font-bold" id="recipe-picker-title">Add saved recipes</h2><p className="text-sm">Current revisions are imported as independent editable scenarios. Different target formulas are allowed.</p></div><button className="rounded border px-3 py-2" onClick={onClose} ref={closeRef}>Cancel</button><button className="rounded bg-teal-800 px-3 py-2 font-semibold text-white" onClick={add}>Add selected</button></header>
    <div className="p-4"><label className="block font-medium">Search by recipe name<input className="mt-1 w-full rounded border px-3 py-2" onChange={(event) => setSearch(event.target.value)} value={search} /></label><div className="mt-3 flex gap-2"><button className="rounded border px-3 py-2 text-sm" onClick={() => setSelected(new Set(visible.filter((item) => !existing.has(item.revision.id)).map((item) => item.recipe.id)))}>Select all visible</button><button className="rounded border px-3 py-2 text-sm" onClick={() => setSelected(new Set())}>Clear selection</button></div>
      {message && <p aria-live="assertive" className="mt-3 rounded border border-red-400 bg-red-50 p-3 font-semibold">{message}</p>}
      <ul className="mt-4 space-y-2">{visible.map(({ recipe, revision, warningCount }) => { const already = existing.has(revision.id); return <li className="rounded border p-3" key={recipe.id}><label className="flex items-start gap-3"><input checked={selected.has(recipe.id)} className="mt-1 size-5" disabled={already} onChange={() => toggle(recipe.id)} type="checkbox" /><span><strong>{recipe.name}</strong>{already && <span className="ml-2 rounded bg-slate-200 px-2 py-1 text-xs font-semibold">Already added</span>}<span className="mt-1 block font-mono text-sm">{recipe.targetFormula}</span><span className="mt-1 block text-sm">Revision {revision.revisionNumber} · updated {new Date(recipe.updatedAt).toLocaleDateString()} · {recipe.validationStatus}</span><span className="block text-sm">{revision.inputState.requestedMassGrams} g · {revision.inputState.basis} · {warningCount} warning{warningCount === 1 ? "" : "s"}</span></span></label></li>; })}</ul>
      {!visible.length && <p className="mt-5 text-center text-slate-600">No saved recipes match this search.</p>}
    </div>
  </dialog>;
}

export function ComparisonShell() {
  const repositories = useMemo(() => new LocalDataRepositories(), []);
  const [workspace, setWorkspace] = useState<ComparisonWorkspace>(() => createComparisonWorkspace());
  const [currentRecovery, setCurrentRecovery] = useState<WorkspaceRecoveryState>();
  const [savedComparisons, setSavedComparisons] = useState<readonly ComparisonWorkspace[]>([]);
  const [recipes, setRecipes] = useState<readonly SavedRecipe[]>([]);
  const [recipeCandidates, setRecipeCandidates] = useState<readonly RecipeCandidate[]>([]);
  const [routes, setRoutes] = useState<readonly SavedRoute[]>([]);
  const [sourceRouteId, setSourceRouteId] = useState("");
  const [removedWorkspace, setRemovedWorkspace] = useState<ComparisonWorkspace>();
  const [status, setStatus] = useState("Opening comparison workspace…");
  const [pickerOpen, setPickerOpen] = useState(false);
  const [summaryOpen, setSummaryOpen] = useState(false);
  const [mode, setMode] = useState<"standard" | "advanced">("standard");
  const [verificationOpen, setVerificationOpen] = useState(false);
  const [verificationScenarioIds, setVerificationScenarioIds] = useState<readonly string[]>([]);
  const [userSettings, setUserSettings] = useState<LocalUserSettings>(() => createDefaultUserSettings());
  const [traceOpen, setTraceOpen] = useState(false);
  const verificationTriggerRef = useRef<HTMLButtonElement>(null);
  const calculations = useMemo(() => calculateComparison(workspace), [workspace]);
  const difference = useMemo(() => compareScenarios(workspace.scenarios, calculations), [calculations, workspace.scenarios]);

  const refresh = useCallback(async () => {
    const [comparisons, recipeList, routeList] = await Promise.all([repositories.listComparisons(), repositories.listRecipes(), repositories.listRoutes()]);
    const candidates = (await Promise.all(recipeList.map(async (recipe) => { const revision = await repositories.getRevision(recipe.currentRevisionId); if (!revision) return undefined; const calculation = buildWorkspaceCalculation(migrateWorkspaceAluminumInput(revision.inputState)); return { recipe, revision, warningCount: validResult(calculation)?.warnings.length ?? 0 }; }))).filter((item): item is RecipeCandidate => Boolean(item));
    setSavedComparisons(comparisons); setRecipes(recipeList); setRoutes(routeList); setRecipeCandidates(candidates);
  }, [repositories]);

  useEffect(() => { let active = true; void (async () => { await repositories.database.open(); const [recovery, settings] = await Promise.all([repositories.loadRecovery(), repositories.getSettings()]); if (active) { setCurrentRecovery(recovery); setUserSettings(settings); } await refresh(); if (active) setStatus("Comparison ready · no scenarios selected"); })().catch((error) => active && setStatus(`Comparison unavailable: ${error instanceof Error ? error.message : "local database error"}`)); return () => { active = false; }; }, [refresh, repositories]);

  const edit = (scenarioId: string, update: (input: WorkspaceRecipeState) => WorkspaceRecipeState) => setWorkspace((current) => updateScenario(forkHistoricalComparison(current), scenarioId, update));
  const existingRevisionIds = useMemo(() => new Set(workspace.scenarios.flatMap((item) => item.source.recipeRevisionId ? [item.source.recipeRevisionId] : [])), [workspace.scenarios]);

  const addSelectedRecipes = (recipeIds: readonly string[]) => {
    const selected = recipeIds.map((id) => recipeCandidates.find((item) => item.recipe.id === id)).filter((item): item is RecipeCandidate => Boolean(item));
    if (selected.some((item) => existingRevisionIds.has(item.revision.id))) { const message = "A selected recipe revision is already in this comparison. Use Duplicate on its scenario to add another copy."; setStatus(message); return message; }
    try {
      let next = forkHistoricalComparison(workspace);
      for (const item of selected) next = addComparisonScenario(next, migrateWorkspaceAluminumInput(item.revision.inputState), uniqueName(item.recipe.name, next.scenarios), { kind: "saved-recipe", recipeId: item.recipe.id, recipeRevisionId: item.revision.id }, item.recipe.validationStatus);
      setWorkspace(next); setPickerOpen(false); setStatus(`Added ${selected.length} saved recipe${selected.length === 1 ? "" : "s"}.`); return undefined;
    } catch (error) { const message = error instanceof Error ? error.message : "Recipes could not be added."; setStatus(message); return message; }
  };

  const addCurrentRecipe = () => {
    if (!currentRecovery) { setStatus("No current calculator recipe is available. Open the calculator and enter a recipe first."); return; }
    const input = migrateWorkspaceAluminumInput(currentRecovery.committedRecipe); const saved = recipes.find((item) => item.id === currentRecovery.baseRecipeId);
    try { setWorkspace((current) => addComparisonScenario(forkHistoricalComparison(current), input, uniqueName(saved?.name ?? "Unsaved calculation", current.scenarios), saved ? { kind: "working-recipe", recipeId: saved.id, recipeRevisionId: currentRecovery.baseRevisionId } : { kind: "working-recipe" }, saved?.validationStatus ?? "synthetic")); setStatus("Added the current calculator recipe."); } catch (error) { setStatus(error instanceof Error ? error.message : "Current recipe could not be added."); }
  };

  const addBlankScenario = () => {
    const input = blankWorkspaceState();
    try { setWorkspace((current) => addComparisonScenario(forkHistoricalComparison(current), input, uniqueName("Blank scenario", current.scenarios), { kind: "empty" }, "synthetic")); setStatus("Added a blank editable scenario."); } catch (error) { setStatus(error instanceof Error ? error.message : "Blank scenario could not be added."); }
  };

  const addRoute = async () => { const route = routes.find((item) => item.id === sourceRouteId); if (!route) return; const revision = await repositories.getRouteRevision(route.currentRevisionId); if (!revision) return; const base = workspace.scenarios[0]?.inputState ?? currentRecovery?.committedRecipe; if (!base) { setStatus("Add a recipe before adding a saved route."); return; } try { setWorkspace((current) => addComparisonScenario(current, migrateWorkspaceAluminumInput({ ...base, precursors: revision.precursors, ...revision.defaults }), uniqueName(route.name, current.scenarios), { kind: "saved-route", routeId: route.id, routeRevisionId: revision.id }, route.validationStatus)); setStatus(`Added ${route.name}.`); } catch (error) { setStatus(error instanceof Error ? error.message : "Route could not be added."); } };

  const saveComparison = async () => {
    if (workspace.scenarios.length < 2) { setStatus("Add at least one more scenario before saving this comparison."); return; }
    try {
      const scenarios = await Promise.all(workspace.scenarios.map(async (scenario) => { const calculation = calculations[scenario.id]!; const result = validResult(calculation); if (!result) return { ...scenario, historical: undefined }; const canonicalInput = canonicalizeWorkspaceScientificInput(scenario.inputState); const canonicalOutput = stableCanonicalize(JSON.parse(result.canonicalScientificRepresentation)); return { ...scenario, historical: { canonicalInput, canonicalOutput, inputDigest: await sha256Hex(canonicalInput), outputDigest: await sha256Hex(canonicalOutput), engineVersion: result.engineVersion, atomicWeightDataVersion: result.dataVersions.atomicWeights, calculatedAt: new Date().toISOString(), result: clone(result) } }; }));
      const name = workspace.name.trim() || "Recipe comparison";
      const saved: ComparisonWorkspace = { ...workspace, name, scenarios, historical: true, updatedAt: new Date().toISOString() };
      await repositories.saveComparison(saved);
      const persisted = await repositories.getComparison(saved.id);
      if (!persisted) throw new Error("The comparison was not found after saving.");
      setWorkspace(clone(persisted)); await refresh(); setStatus("Comparison saved");
    } catch (error) { setStatus(`Comparison was not saved. ${error instanceof Error ? error.message : "Local storage failed."} Your working scenarios are unchanged.`); }
  };

  const promote = async (scenario: ComparisonScenario) => { const result = validResult(calculations[scenario.id]!); if (!result) { setStatus("Only a valid scenario can be saved as a recipe."); return; } try { const saved = await repositories.saveCalculatedRevision({ name: `${scenario.name} from comparison`, inputState: scenario.inputState, result, revisionNote: `Promoted from comparison ${workspace.name}` }); setStatus(`Saved ${saved.recipe.name}, revision 1`); await refresh(); } catch (error) { setStatus(`Recipe was not saved. ${error instanceof Error ? error.message : "Local storage failed."}`); } };
  const saveRoute = async (scenario: ComparisonScenario) => { try { await repositories.saveRouteRevision({ name: `${scenario.name} route`, inputState: scenario.inputState, validationStatus: scenario.validationStatus }); setStatus(`Saved ${scenario.name} as an independent route.`); await refresh(); } catch (error) { setStatus(`Route was not saved. ${error instanceof Error ? error.message : "Local storage failed."}`); } };
  const exportComparison = async () => { try { const envelope = await createOwnedRecordExport("max-stoich-comparison-workspace", { comparison: workspace }); downloadText(safeExportFilename(workspace.name, "json"), JSON.stringify(envelope, null, 2), "application/json;charset=utf-8"); setStatus("Exported a digest-protected MAX Stoich comparison record."); } catch (error) { setStatus(`Comparison export failed. ${error instanceof Error ? error.message : "The file could not be created."}`); } };

  const summaryEntries: readonly WeighingSummaryEntry[] = workspace.scenarios.map((scenario) => { const calculation = calculations[scenario.id]!; const result = validResult(calculation); const sourceStatus = scenario.source.kind === "saved-recipe" ? `Saved recipe revision ${recipeCandidates.find((item) => item.revision.id === scenario.source.recipeRevisionId)?.revision.revisionNumber ?? "—"}` : scenario.source.kind.replaceAll("-", " "); if (!result) return { unavailable: { title: scenario.name, sourceStatus, reason: calculationReason(calculation), validationStatus: scenario.validationStatus } }; return { summary: buildWeighingSummary({ title: scenario.name, sourceStatus, inputState: scenario.inputState, result, validationStatus: scenario.validationStatus, isHistorical: Boolean(scenario.historical) }) }; });
  const verificationEntries: readonly CalculationVerificationEntry[] = workspace.scenarios.filter((scenario) => verificationScenarioIds.length === 0 || verificationScenarioIds.includes(scenario.id)).map((scenario) => { const calculation = calculations[scenario.id]!; const result = validResult(calculation); const unavailable = { title: scenario.name, reason: calculationReason(calculation) }; return result ? { verification: buildCalculationVerification({ title: scenario.name, inputState: scenario.inputState, result }) } : { unavailable }; });
  const printComparison = () => {
    if (!summaryEntries.length) { setStatus("Print unavailable: add at least one scenario."); return; }
    try { launchPrintJob(createPrintJob({ kind: "comparison", title: workspace.name || "Recipe comparison", singleRecipeDetailed: false, settings: userSettings.print, entries: summaryEntries.map((entry, index) => entry.summary ? { id: workspace.scenarios[index]!.id, summary: entry.summary } : { id: workspace.scenarios[index]!.id, unavailable: entry.unavailable }) })); setStatus("Opened the dedicated comparison print view in visible scenario order."); }
    catch (error) { setStatus(`Print unavailable: ${error instanceof Error ? error.message : "print state could not be created"}`); }
  };

  return <main className="comparison-workspace min-h-screen bg-slate-100 text-slate-950">
    <div className="comparison-mode-bar flex justify-end gap-2 border-b bg-white px-4 py-2" aria-label="Comparison detail mode" role="group"><button className="rounded border px-3 py-1 font-semibold disabled:text-slate-400" disabled={!workspace.scenarios.length} onClick={printComparison}>Print comparison</button><button aria-pressed={mode === "standard"} className={`rounded-l border px-3 py-1 ${mode === "standard" ? "bg-slate-900 text-white" : ""}`} onClick={() => setMode("standard")}>Standard</button><button aria-pressed={mode === "advanced"} className={`rounded-r border px-3 py-1 ${mode === "advanced" ? "bg-slate-900 text-white" : ""}`} onClick={() => setMode("advanced")}>Advanced</button></div>
    <header className="sticky top-0 z-20 flex flex-wrap items-center gap-2 border-b bg-white p-3 shadow-sm"><Link className="font-bold" href="/workspace">← Calculator</Link><h1 className="mr-auto text-lg font-bold">Recipe comparison</h1><button className="rounded bg-teal-800 px-3 py-2 font-semibold text-white disabled:bg-slate-400" disabled={workspace.scenarios.length >= MAX_COMPARISON_SCENARIOS} title={workspace.scenarios.length >= MAX_COMPARISON_SCENARIOS ? `Maximum ${MAX_COMPARISON_SCENARIOS} scenarios reached` : undefined} onClick={() => setPickerOpen(true)}>Add saved recipes</button><button className="rounded border px-3 py-2 font-semibold" disabled={workspace.scenarios.length >= MAX_COMPARISON_SCENARIOS} title={workspace.scenarios.length >= MAX_COMPARISON_SCENARIOS ? `Maximum ${MAX_COMPARISON_SCENARIOS} scenarios reached` : undefined} onClick={addCurrentRecipe}>Add current recipe</button><button className="rounded border px-3 py-2 font-semibold" disabled={workspace.scenarios.length >= MAX_COMPARISON_SCENARIOS} title={workspace.scenarios.length >= MAX_COMPARISON_SCENARIOS ? `Maximum ${MAX_COMPARISON_SCENARIOS} scenarios reached` : undefined} onClick={addBlankScenario}>Add blank scenario</button><button className="rounded border px-3 py-2 font-semibold disabled:text-slate-400" disabled={!workspace.scenarios.length} onClick={() => setSummaryOpen(true)}>View comparison summaries</button><button className="rounded bg-slate-900 px-3 py-2 font-semibold text-white" onClick={() => void saveComparison()}>Save comparison</button><details className="relative"><summary className="cursor-pointer rounded border px-3 py-2">More</summary><div className="absolute right-0 z-30 mt-1 grid w-64 gap-2 rounded border bg-white p-3 shadow-xl"><button className="rounded border px-2 py-1 text-left disabled:text-slate-400" disabled={!workspace.scenarios.length} onClick={() => void exportComparison()}>Export comparison JSON</button><Link className="rounded border px-2 py-1" href="/settings">Layouts & data</Link><select aria-label="Saved route source" className="rounded border px-2 py-1" onChange={(event) => setSourceRouteId(event.target.value)} value={sourceRouteId}><option value="">Saved route…</option>{routes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="rounded border px-2 py-1 text-left" disabled={!sourceRouteId || workspace.scenarios.length >= MAX_COMPARISON_SCENARIOS} onClick={() => void addRoute()}>Add saved route</button></div></details><p aria-live="polite" className="w-full text-sm font-medium">{status}</p></header>

    <section aria-label="Comparison identity" className="mx-auto flex max-w-[1600px] flex-wrap items-end gap-3 border-b bg-white p-4"><label className="text-sm font-medium">Comparison name<input className="ml-2 rounded border px-2 py-1" onChange={(event) => setWorkspace((current) => ({ ...current, name: event.target.value, historical: false }))} value={workspace.name} /></label><select aria-label="Open saved comparison" className="rounded border px-2 py-1" onChange={(event) => { const saved = savedComparisons.find((item) => item.id === event.target.value); if (saved) { setWorkspace(clone(saved)); setRemovedWorkspace(undefined); setStatus("Viewing saved comparison exactly as stored."); } }} value=""><option value="">Open saved comparison…</option>{savedComparisons.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>{removedWorkspace && <button className="rounded border px-2 py-1" onClick={() => { setWorkspace(removedWorkspace); setRemovedWorkspace(undefined); setStatus("Restored the removed scenario."); }}>Undo scenario removal</button>}</section>

    {workspace.scenarios.length === 0 ? <section className="mx-auto mt-10 max-w-2xl rounded-xl border-2 border-dashed border-slate-400 bg-white p-10 text-center"><h2 className="text-2xl font-bold">No recipes selected for comparison</h2><p className="mt-2 text-slate-600">Add saved recipes, add the current calculator recipe, or create a blank comparison scenario.</p><div className="mt-6 flex flex-wrap justify-center gap-3"><button className="rounded bg-teal-800 px-4 py-3 font-semibold text-white" onClick={() => setPickerOpen(true)}>Add saved recipes</button><button className="rounded border px-4 py-3 font-semibold" onClick={addCurrentRecipe}>Add current recipe</button><button className="rounded border px-4 py-3 font-semibold" onClick={addBlankScenario}>Add blank scenario</button></div></section> : <>
      {workspace.scenarios.length === 1 && <p className="mx-auto mt-4 max-w-[1600px] rounded border border-blue-300 bg-blue-50 p-3 font-semibold">Add at least one more scenario to compare results.</p>}
      <div className="mx-auto grid max-w-[1600px] gap-4 p-4 lg:grid-cols-2">{workspace.scenarios.map((scenario) => { const calculation = calculations[scenario.id]!; const result = validResult(calculation); return <section aria-label={`${scenario.name} scenario`} className="rounded border bg-white p-4 shadow-sm" key={scenario.id}><div className="flex flex-wrap items-center gap-2"><input aria-label={`${scenario.name} name`} className="min-w-0 flex-1 rounded border px-2 py-1 font-semibold" onChange={(event) => setWorkspace((current) => ({ ...current, scenarios: current.scenarios.map((item) => item.id === scenario.id ? { ...item, name: event.target.value } : item), historical: false }))} value={scenario.name} /><span className="text-xs">{calculation.state} · {scenario.validationStatus}</span><button className="rounded border px-2 py-1 text-xs" disabled={workspace.scenarios.length >= MAX_COMPARISON_SCENARIOS} onClick={() => { try { setWorkspace((current) => duplicateScenario(current, scenario.id)); setStatus(`Duplicated ${scenario.name}.`); } catch (error) { setStatus(error instanceof Error ? error.message : "Cannot duplicate scenario"); } }}>Duplicate</button><button className="rounded border border-red-300 px-2 py-1 text-xs" onClick={() => { setRemovedWorkspace(workspace); setWorkspace((current) => removeScenario(current, scenario.id)); setStatus(`Removed ${scenario.name}.`); }}>Remove</button></div><p className="mt-1 text-xs">Source: {scenario.source.kind}{scenario.source.recipeRevisionId ? ` · revision ${recipeCandidates.find((item) => item.revision.id === scenario.source.recipeRevisionId)?.revision.revisionNumber ?? "—"}` : ""}{scenario.historical ? ` · historical engine ${scenario.historical.engineVersion}` : " · current engine"}</p>
        <div className="mt-3 grid gap-2 sm:grid-cols-2"><label className="text-xs sm:col-span-2">Scenario target formula<input aria-label={`${scenario.name} target formula`} className="mt-1 w-full rounded border px-2 py-1 font-mono" onChange={(event) => edit(scenario.id, (input) => { const targetFormula = event.target.value; const normalized = input.normalizeLeadingSiteRatios ? normalizeLeadingSiteRatioGroup(targetFormula, { enabled: true, expectedSite: "M" }) : undefined; return { ...input, targetFormula, aluminumPerFormula: aluminumCoefficientForTargetChange(input, targetFormula), siteComposition: normalized?.success ? normalized.value.explicitSiteModel : undefined, radiusDescriptorConfig: undefined, presetId: "custom" }; })} value={scenario.inputState.targetFormula} /></label><label className="text-xs">Batch mass<input className="mt-1 w-full rounded border px-2 py-1" onChange={(event) => edit(scenario.id, (input) => ({ ...input, requestedMassGrams: event.target.value }))} value={scenario.inputState.requestedMassGrams} /></label><label className="text-xs">Aluminum per formula<input className="mt-1 w-full rounded border px-2 py-1" onChange={(event) => edit(scenario.id, (input) => ({ ...input, aluminumPerFormula: event.target.value }))} value={scenario.inputState.aluminumPerFormula ?? ""} /></label><label className="text-xs">Handling loss %<input className="mt-1 w-full rounded border px-2 py-1" onChange={(event) => edit(scenario.id, (input) => ({ ...input, handlingLossPercent: event.target.value }))} value={scenario.inputState.handlingLossPercent} /></label></div>
        <div className="mt-3 space-y-2">{scenario.inputState.precursors.map((precursor, index) => <div className="grid grid-cols-[1fr_6rem_auto] gap-2" key={precursor.id}><input aria-label={`${scenario.name} precursor ${index + 1} formula`} className="rounded border px-2 font-mono" onChange={(event) => edit(scenario.id, (input) => ({ ...input, precursors: input.precursors.map((item) => item.id === precursor.id ? { ...item, formula: event.target.value, name: event.target.value || item.name } : item) }))} value={precursor.formula} /><input aria-label={`${scenario.name} precursor ${index + 1} purity`} className="rounded border px-2" onChange={(event) => edit(scenario.id, (input) => ({ ...input, precursors: input.precursors.map((item) => item.id === precursor.id ? { ...item, purityPercent: event.target.value } : item) }))} value={precursor.purityPercent} /><button aria-label={`Remove ${precursor.name} from ${scenario.name}`} className="rounded border border-red-300 px-2 text-xs" onClick={() => edit(scenario.id, (input) => ({ ...input, precursors: input.precursors.filter((item) => item.id !== precursor.id) }))}>Remove</button></div>)}<button className="rounded border px-3 py-2 text-sm" onClick={() => edit(scenario.id, (input) => ({ ...input, precursors: [...input.precursors, blankPrecursor(input.precursors.length + 1)] }))}>Add precursor</button></div>
        {result ? <div className="mt-4"><WeighingSummaryCard advanced={mode === "advanced"} headingLevel={3} summary={buildWeighingSummary({ title: `${scenario.name} results`, sourceStatus: scenario.source.kind === "saved-recipe" ? `Saved recipe · revision ${recipeCandidates.find((item) => item.revision.id === scenario.source.recipeRevisionId)?.revision.revisionNumber ?? "—"}` : scenario.source.kind.replaceAll("-", " "), inputState: scenario.inputState, result, validationStatus: scenario.validationStatus, isHistorical: Boolean(scenario.historical) })} /></div> : <div className="mt-3 rounded border border-red-300 bg-red-50 p-3 text-sm" role="alert"><strong>Action required — No valid weighing result.</strong><p>Reason: {calculationReason(calculation)}</p><details className="mt-2"><summary>Technical details</summary><ul>{calculation.errors.map((item) => <li key={`${item.code}-${item.fieldPath}`}>{item.message}</li>)}</ul></details></div>}
        {mode === "advanced" && <>{<AtomicRadiusPanel config={scenario.inputState.radiusDescriptorConfig} onConfigChange={(radiusDescriptorConfig) => edit(scenario.id, (input) => ({ ...input, radiusDescriptorConfig }))} onConfigureSites={() => setStatus("Configure explicit crystallographic sites in the calculator; flat formulas are never used for site inference.")} siteModel={scenario.inputState.siteComposition} />}{result && <details className="mt-3 rounded border bg-slate-50 p-3"><summary className="font-semibold">Solver, balance, residuals, and provenance</summary><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="font-semibold">Solver</dt><dd>{result.solver?.backend.name ?? "Unavailable"} · {result.solver?.status ?? result.status}</dd></div><div><dt className="font-semibold">Matrix / rank</dt><dd>{result.matrix ? `${result.matrix.dimensions.rows} × ${result.matrix.dimensions.columns} · rank ${result.matrix.analysis.matrixRank} · ${result.matrix.analysis.rankConsistency}` : "Unavailable"}</dd></div><div><dt className="font-semibold">Adjustments</dt><dd>{result.resolvedAdjustmentOrder.length ? result.resolvedAdjustmentOrder.join(" → ") : "None"}</dd></div><div><dt className="font-semibold">Residuals</dt><dd>{result.realizedElements.length} elemental residuals recorded</dd></div><div><dt className="font-semibold">Trace / provenance</dt><dd>{result.trace.length} trace steps · engine {result.engineVersion} · atomic weights {result.dataVersions.atomicWeights}</dd></div></dl></details>}</>}
        <div className="mt-3 flex flex-wrap gap-2"><button className="rounded border px-2 py-1 text-sm" onClick={() => void promote(scenario)}>Save as recipe</button><button className="rounded border px-2 py-1 text-sm" onClick={() => void saveRoute(scenario)}>Save as route</button>{scenario.historical && <button className="rounded border px-2 py-1 text-sm" onClick={() => edit(scenario.id, (input) => input)}>Recalculate selected</button>}</div>
      </section>; })}</div>
      <section aria-labelledby="difference-heading" className="mx-auto mb-8 max-w-[1600px] overflow-x-auto rounded border bg-white p-4"><h2 className="text-lg font-semibold" id="difference-heading">Deterministic differences</h2><p className="mt-1 text-sm">These labels compare calculated values only; they do not identify an experimentally superior or more stable route.</p><div className="mt-3 flex flex-wrap gap-2">{workspace.selectedMetrics.map((metric) => <span className="rounded bg-slate-100 px-2 py-1 text-xs" key={metric}>{metric.replaceAll("-", " ")}: {difference.metricLeaders[metric]?.map((id) => workspace.scenarios.find((item) => item.id === id)?.name).join(", ")}</span>)}</div></section>
    </>}

    {workspace.scenarios.length > 0 && <section aria-label="Comparison calculation details" className="comparison-verification-actions border-b bg-white px-4 py-3"><strong>Calculation details</strong><p className="mt-1 text-xs text-slate-600">Audit mole-to-mass conversion, rounding, elemental reconciliation, and each scenario trace.</p><div className="mt-2 flex flex-wrap gap-2"><button className="rounded border border-slate-400 px-3 py-2 font-semibold disabled:text-slate-400" disabled={!workspace.scenarios.some((scenario) => Boolean(validResult(calculations[scenario.id]!)))} onClick={() => { setVerificationScenarioIds([]); setVerificationOpen(true); }} ref={verificationTriggerRef}>Verify calculations</button><button aria-expanded={traceOpen} className="rounded border border-slate-400 px-3 py-2 font-semibold" onClick={() => setTraceOpen((value) => !value)}>{traceOpen ? "Close calculation trace" : "Open calculation trace"}</button>{workspace.scenarios.map((scenario) => <button className="rounded border px-3 py-2 text-sm disabled:text-slate-400" disabled={!validResult(calculations[scenario.id]!)} key={scenario.id} onClick={(event) => { verificationTriggerRef.current = event.currentTarget; setVerificationScenarioIds([scenario.id]); setVerificationOpen(true); }}>Verify {scenario.name}</button>)}</div>{traceOpen && <div className="mt-3 grid gap-3">{workspace.scenarios.map((scenario) => { const result = validResult(calculations[scenario.id]!); return <section className="max-h-72 overflow-auto rounded border bg-slate-50 p-3" key={scenario.id}><h3 className="font-semibold">{scenario.name}</h3>{result ? <ol className="mt-2 space-y-2 text-sm">{result.trace.map((step, index) => <li className="border-b pb-2" key={`${step.stepCode}-${index}`}><strong className="font-mono">{step.stepCode}</strong> · {step.description}</li>)}</ol> : <p className="mt-2 text-sm">No valid calculation trace: {calculationReason(calculations[scenario.id]!)}</p>}</section>; })}</div>}</section>}
    <RecipePicker candidates={recipeCandidates} capacity={MAX_COMPARISON_SCENARIOS - workspace.scenarios.length} existing={existingRevisionIds} onAdd={addSelectedRecipes} onClose={() => setPickerOpen(false)} open={pickerOpen} />
    <WeighingSummaryDialog entries={summaryEntries} onClose={() => setSummaryOpen(false)} onOpenVerification={() => { setSummaryOpen(false); setVerificationScenarioIds([]); setVerificationOpen(true); }} onPrint={printComparison} onStatus={setStatus} open={summaryOpen && workspace.scenarios.length > 0} title={workspace.name || "Comparison weighing summaries"} />
    <CalculationVerificationDialog entries={verificationEntries} onClose={() => { setVerificationOpen(false); requestAnimationFrame(() => verificationTriggerRef.current?.focus()); }} onStatus={setStatus} open={verificationOpen && workspace.scenarios.length > 0} title={verificationScenarioIds.length === 1 ? "Scenario calculation verification" : "Comparison calculation verification"} />
  </main>;
}
