"use client";

import { useEffect, useRef, useState } from "react";
import type { WeighingSummary } from "@/lib/presentation/weighing-summary";
import { serializeWeighingSummary } from "@/lib/presentation/weighing-summary";

export type WeighingSummaryEntry = Readonly<{ summary: WeighingSummary; unavailable?: never } | { summary?: never; unavailable: Readonly<{ title: string; sourceStatus: string; reason: string; validationStatus: string }> }>;

function RadiusSummary({ summary }: { summary: WeighingSummary }) {
  return <section aria-label="Advanced site-radius summary" className="summary-radius mt-5 border-t-2 border-slate-800 pt-3"><h4 className="font-bold">Site-radius screening descriptors</h4>{summary.radiusSites.length ? <>{summary.radiusSites.map((site) => <article className="mt-3" key={site.siteId}><h5 className="font-semibold">{site.siteLabel}</h5><p className="text-sm">{site.datasetName} · {site.datasetDefinition} · version {site.datasetVersion} · vacancy {site.vacancyFraction}</p>{site.available ? <p className="mt-1 font-mono text-sm">Mean {site.meanRadiusPm} pm · min {site.minimumRadiusPm} · max {site.maximumRadiusPm} · range {site.rangeRadiusPm} · SD {site.standardDeviationPm} · δ {site.mismatchPercent}%</p> : <p className="mt-1 rounded bg-amber-50 p-2 text-sm font-semibold">Aggregate unavailable: missing {site.missingElements.join(", ")}. No occupant was dropped or renormalized.</p>}<table className="radius-detail-table mt-2 w-full text-left text-sm"><caption className="sr-only">{site.siteLabel} resolved atomic radius values</caption><thead><tr><th>Element</th><th>Site</th><th>Occupancy</th><th>Radius</th><th>Definition</th><th>Dataset</th><th>Source</th></tr></thead><tbody>{site.occupants.map((item) => <tr key={`${site.siteId}-${item.element}`}><th>{item.element}</th><td>{item.siteId}</td><td>{item.occupancy}</td><td>{item.radiusPm ? `${item.radiusPm} pm` : "Unavailable"}</td><td>{item.definition}</td><td>{item.datasetName}</td><td>{item.overridden ? "Override" : "Dataset"}</td></tr>)}</tbody></table></article>)}<p className="radius-disclaimer mt-3 text-xs font-semibold">{summary.radiusDisclaimer}</p></> : <p className="mt-2 text-sm">No explicit-site radius descriptor is configured. Flat formulas are not used to infer crystallographic sites.</p>}</section>;
}

export function WeighingSummaryCard({ summary, headingLevel = 2, onCopy, advanced = false }: { summary: WeighingSummary; headingLevel?: 2 | 3; onCopy?: () => void; advanced?: boolean }) {
  const Heading = headingLevel === 2 ? "h2" : "h3";
  return <section className="weighing-summary-card rounded-lg border-2 border-slate-800 bg-white p-5 text-slate-950">
    <div className="flex items-start justify-between gap-3"><div><Heading className="text-2xl font-bold">{summary.title}</Heading><p className="mt-1 text-sm font-semibold">{summary.sourceStatus}{summary.validationStatus ? ` · ${summary.validationStatus}` : ""}{summary.isHistorical ? " · Historical saved result" : ""}</p></div>{onCopy && <button className="summary-control rounded border px-3 py-2 font-semibold" onClick={onCopy}>Copy individual scenario</button>}</div>
    <div className="mt-5"><p className="text-sm font-bold uppercase tracking-wide">Adjusted intended feed</p><p aria-label={`Adjusted intended feed formula ${summary.adjustedFeedFormula}`} className="mt-1 break-all font-mono text-3xl font-bold leading-tight tabular-nums">{summary.adjustedFeedFormula}</p></div>
    <p className="mt-4 text-lg"><strong>Target batch:</strong> <span className="font-mono tabular-nums">{summary.batchMass} g</span> · {summary.batchBasis}</p>
    <span className="sr-only">Final total</span><table className="summary-weighing-table mt-5 w-full border-collapse text-xl tabular-nums"><caption className="sr-only">Final precursor weighing masses and molar quantities</caption><thead><tr className="border-b-2 border-slate-800 text-left text-sm uppercase"><th className="py-2">Precursor</th><th className="py-2">Formula</th><th className="py-2 text-right">Molar ratio</th><th className="py-2 text-right">Purity</th><th className="py-2 text-right">Final mass</th><th className="py-2">Status</th></tr></thead><tbody>{summary.precursors.map((item) => <tr className="border-b border-slate-300" key={item.id}><th className="py-3 text-left font-bold">{item.displayName}</th><td className="py-3 font-mono">{item.formula}</td><td className="py-3 text-right font-mono"><span title={`${item.hasPostSolverAdjustment ? "Final intended" : "Solver"} molar quantity`}>{item.molarQuantity} mol/mol target</span>{item.molarQuantityExact && item.molarQuantityExact !== item.molarQuantity && <span className="block text-xs">exact {item.molarQuantityExact}</span>}{item.hasPostSolverAdjustment && <span className="block text-xs">solver {item.solverMolarQuantity} · exact {item.solverMolarQuantityExact}</span>}</td><td className="py-3 text-right font-mono">{item.purityPercent}%</td><td className="py-3 text-right font-mono text-2xl font-bold">{item.finalMass} {item.unit}</td><td className="py-3 pl-2 text-sm">{item.status}</td></tr>)}</tbody><tfoot><tr className="border-t-4 border-slate-900"><th className="pt-4 text-left text-2xl" colSpan={4}>TOTAL</th><td className="pt-4 text-right font-mono text-3xl font-black">{summary.totalMass} {summary.unit}</td><td /></tr></tfoot></table>
    {summary.actionRequiredMessages.length > 0 && <section className="mt-5 border-l-4 border-amber-700 bg-amber-50 p-3" aria-label="Action required"><h4 className="font-bold">Action required before weighing</h4><ul className="mt-1 list-disc pl-5">{summary.actionRequiredMessages.map((message) => <li key={message}>{message}</li>)}</ul></section>}
    {advanced && <section aria-label="Compact calculation verification" className="mt-5 border-t-2 border-slate-800 pt-3"><h4 className="font-bold">Calculation verification</h4><dl className="mt-2 grid gap-1 text-sm sm:grid-cols-2"><div><dt>Arithmetic status</dt><dd className="font-semibold">{summary.verificationSummary.statusLabel}</dd></div><div><dt>Target formula moles</dt><dd className="font-mono">{summary.verificationSummary.targetFormulaMoles} mol</dd></div><div><dt>Largest elemental residual</dt><dd className="font-mono">{summary.verificationSummary.largestElementalResidual}</dd></div><div><dt>Molar-mass data</dt><dd>{summary.verificationSummary.atomicDataVersion}</dd></div></dl><p className="mt-2 text-xs">Use Verify calculation in the results panel for full precursor conversion, reconciliation, equations, and assumptions.</p></section>}
    {advanced && <RadiusSummary summary={summary} />}
    <footer className="summary-signature mt-5 border-t pt-2 text-xs">Engine {summary.engineVersion} · atomic weights {summary.atomicWeightDataVersion}<span className="signature-line float-right">Operator/signature ____________________</span></footer>
  </section>;
}

export function WeighingSummaryDialog({ open, title, entries, onClose, onStatus, onOpenVerification, onPrint }: { open: boolean; title: string; entries: readonly WeighingSummaryEntry[]; onClose: () => void; onStatus: (message: string) => void; onOpenVerification?: () => void; onPrint?: () => void }) {
  const dialogRef = useRef<HTMLDialogElement>(null); const closeRef = useRef<HTMLButtonElement>(null); const [advanced, setAdvanced] = useState(false);
  useEffect(() => { const dialog = dialogRef.current; if (!dialog) return; if (open && !dialog.open) { setAdvanced(false); dialog.showModal(); closeRef.current?.focus(); } else if (!open && dialog.open) dialog.close(); }, [open]);
  const summaries = entries.flatMap((entry) => entry.summary ? [entry.summary] : []);
  const textFor = (summary: WeighingSummary) => serializeWeighingSummary(summary, { includeAdvanced: advanced });
  const copyText = entries.length === 1 && entries[0]?.summary ? textFor(entries[0].summary) : entries.map((entry, index) => entry.summary ? `=== ${index + 1}. ${entry.summary.title} ===\n${textFor(entry.summary)}` : `=== ${index + 1}. ${entry.unavailable.title} ===\n${entry.unavailable.sourceStatus}\n\nNo valid weighing result\nReason: ${entry.unavailable.reason}`).join("\n\n");
  const copy = async (text: string, message: string) => { try { await navigator.clipboard.writeText(text); onStatus(message); } catch { onStatus("Clipboard permission was denied."); } };
  const radiusSiteIds = [...new Set(summaries.flatMap((summary) => summary.radiusSites.map((site) => site.siteId)))];
  const differentRadiusDatasets = radiusSiteIds.some((siteId) => new Set(summaries.flatMap((summary) => summary.radiusSites.filter((site) => site.siteId === siteId).map((site) => `${site.datasetName}@${site.datasetVersion}`))).size > 1);
  return <dialog aria-labelledby="weighing-summary-dialog-title" className="weighing-summary-dialog m-auto max-h-[94vh] w-[min(96vw,110rem)] overflow-auto rounded-xl border-2 border-slate-800 bg-slate-100 p-0 backdrop:bg-slate-950/60" onCancel={(event) => { event.preventDefault(); onClose(); }} onClose={onClose} ref={dialogRef}>{open && <>
    <div className="summary-control sticky top-0 z-10 flex flex-wrap items-center gap-2 border-b bg-white p-3 shadow"><h1 className="mr-auto text-xl font-bold" id="weighing-summary-dialog-title">{title}</h1><label className="flex items-center gap-2 rounded border px-3 py-2 font-semibold"><input checked={advanced} onChange={(event) => setAdvanced(event.target.checked)} type="checkbox" />Include advanced radius summary</label>{advanced && onOpenVerification && <button className="rounded border px-3 py-2 font-semibold" onClick={onOpenVerification}>Full calculation verification</button>}<button className="rounded border px-3 py-2 font-semibold" disabled={!entries.length} onClick={() => void copy(copyText, entries.length === 1 ? advanced ? "Advanced weighing summary copied" : "Weighing summary copied" : "All comparison summaries copied")}>{entries.length === 1 ? advanced ? "Copy advanced summary" : "Copy summary" : "Copy all summaries"}</button><button className="rounded border px-3 py-2 font-semibold" disabled={!entries.length || !onPrint} onClick={onPrint}>Print{entries.length > 1 ? " all" : ""}</button><button className="rounded bg-slate-900 px-3 py-2 font-semibold text-white" onClick={onClose} ref={closeRef}>Close</button></div>
    {advanced && summaries.length > 1 && differentRadiusDatasets && <p className="summary-dataset-warning mx-5 mt-4 rounded border border-amber-500 bg-amber-50 p-3 font-semibold">Not directly comparable — different radius datasets. Values are shown without ranking or a calculated difference.</p>}
    <div className="comparison-print-overview hidden"><strong>{title}</strong> · {entries.length} scenarios · generated {new Date().toLocaleDateString()}</div>
    <div className="weighing-summary-print-root grid gap-5 p-5" data-summary-count={entries.length}>{entries.map((entry, index) => entry.summary ? <WeighingSummaryCard advanced={advanced} headingLevel={2} key={`${entry.summary.title}-${index}`} onCopy={summaries.length > 1 ? () => void copy(textFor(entry.summary!), `${entry.summary!.title} summary copied`) : undefined} summary={entry.summary} /> : <section className="weighing-summary-card rounded-lg border-2 border-red-700 bg-white p-5" key={`${entry.unavailable.title}-${index}`}><h2 className="text-2xl font-bold">{entry.unavailable.title}</h2><p className="mt-1 text-sm font-semibold">{entry.unavailable.sourceStatus} · {entry.unavailable.validationStatus}</p><p className="mt-6 text-2xl font-bold">No valid weighing result</p><p className="mt-2 text-lg"><strong>Reason:</strong> {entry.unavailable.reason}</p></section>)}</div>
  </>}</dialog>;
}
