"use client";

import { useEffect, useMemo, useState } from "react";
import { DEFAULT_ATOMIC_RADIUS_REGISTRY } from "@max-stoich/chemistry-engine";
import type { LocalDataRepositories } from "@/lib/persistence/repositories";
import {
  FIELD_LABELS, PRINT_FIELD_LABELS, createDefaultUserSettings, createRecommendedPrintSettings, relativeTemplateCarbonLabel, validateDisplaySettings, validatePositiveDecimal, validateUserSettings,
  type LocalUserSettings, type PrintField, type PrintSettings, type WeighingResultDisplaySettings, type WeighingResultField,
} from "@/lib/settings/user-settings";
import type { Mode } from "@/lib/persistence/workspace-types";
import { useTheme } from "@/components/theme/theme-provider";
import type { AppearancePreference } from "@/lib/theme/theme";
import { PrintDocument } from "@/components/print/print-root";
import { createPrintJob, launchPrintJob, type PrintableRecipeEntry } from "@/lib/print/print-model";
import type { WeighingSummary } from "@/lib/presentation/weighing-summary";

function Preview({ mode, display, datasetId }: { mode: Mode; display: WeighingResultDisplaySettings; datasetId: string }) {
  const fields = display.columnOrder.filter((field) => display.visibleFields.includes(field));
  const dataset = DEFAULT_ATOMIC_RADIUS_REGISTRY.usableDatasets.find((item) => item.datasetId === datasetId);
  const row = (compound: boolean): Record<WeighingResultField, string> => ({
    "precursor-name": compound ? "TiC" : "Ti", formula: compound ? "TiC" : "Ti", purity: compound ? "99.5%" : "100%", "solver-molar-ratio": compound ? "0.5" : "1", "final-intended-molar-ratio": compound ? "0.5" : "1", "batch-scaled-moles": compound ? "24.1 mmol" : "48.2 mmol", "molar-mass": compound ? "59.878 g/mol" : "47.867 g/mol", "pure-required-mass": compound ? "1.443 g" : "2.306 g", "pre-round-mass": compound ? "1.450 g" : "2.307 g", "final-mass": compound ? "1.450 g" : "2.307 g", "realized-moles": compound ? "24.1 mmol" : "48.2 mmol", status: compound ? "Review" : "OK", warning: compound ? "1 advisory" : "None", "atomic-radius": compound ? "Not applicable" : dataset?.values.find((item) => item.element === "Ti" && item.defaultForPolicy)?.radiusPm ? `${dataset.values.find((item) => item.element === "Ti" && item.defaultForPolicy)!.radiusPm} pm · ${dataset.definition}` : "No value", "atomic-radius-source": compound ? "Not applicable" : dataset ? `${dataset.name} · ${dataset.datasetVersion}` : "No usable dataset selected", source: compound ? "Synthetic preview" : "Elemental route",
  });
  return <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[520px] text-left text-xs"><caption className="mb-1 text-left font-semibold">{mode === "standard" ? "Standard" : "Advanced"} mode preview · synthetic display-only rows</caption><thead><tr>{fields.map((field) => <th className="border-b p-2" key={field}>{FIELD_LABELS[field]}</th>)}</tr></thead><tbody>{[false, true].map((compound) => <tr key={String(compound)}>{fields.map((field) => <td className="border-b p-2" key={field}>{row(compound)[field]}</td>)}</tr>)}</tbody></table>{fields.includes("atomic-radius") && !dataset && <p className="mt-2 rounded bg-amber-50 p-2 text-xs font-semibold">Atomic-radius column enabled, but no usable dataset is selected.</p>}</div>;
}

function DisplayEditor({ mode, value, onChange }: { mode: Mode; value: WeighingResultDisplaySettings; onChange: (value: WeighingResultDisplaySettings) => void }) {
  const errors = validateDisplaySettings(value, mode);
  const setVisible = (field: WeighingResultField, checked: boolean) => onChange({ ...value, visibleFields: checked ? [...value.visibleFields, field] : value.visibleFields.filter((item) => item !== field) });
  const move = (field: WeighingResultField, direction: -1 | 1) => { const index = value.columnOrder.indexOf(field); const target = index + direction; if (target < 0 || target >= value.columnOrder.length) return; const order = [...value.columnOrder]; [order[index], order[target]] = [order[target]!, order[index]!]; onChange({ ...value, columnOrder: order }); };
  return <section aria-labelledby={`${mode}-display-heading`} className="rounded border p-4"><h3 className="font-semibold" id={`${mode}-display-heading`}>{mode === "standard" ? "Standard" : "Advanced"} mode columns</h3><p className="mt-1 text-sm">Visibility and order are independent from the other mode and do not change calculation or export order.</p><div className="mt-3 space-y-1">{value.columnOrder.map((field, index) => <div className="grid grid-cols-[minmax(0,1fr)_auto_auto] items-center gap-2 rounded border p-2" key={field}><label className="flex items-center gap-2 text-sm"><input checked={value.visibleFields.includes(field)} onChange={(event) => setVisible(field, event.target.checked)} type="checkbox" />{FIELD_LABELS[field]}</label><button aria-label={`Move ${FIELD_LABELS[field]} up in ${mode} mode`} className="rounded border px-2 py-1 disabled:text-slate-400" disabled={index === 0} onClick={() => move(field, -1)} type="button">Up</button><button aria-label={`Move ${FIELD_LABELS[field]} down in ${mode} mode`} className="rounded border px-2 py-1 disabled:text-slate-400" disabled={index === value.columnOrder.length - 1} onClick={() => move(field, 1)} type="button">Down</button></div>)}</div>{errors.map((error) => <p className="mt-2 text-sm font-semibold text-red-800" key={error}>{error}</p>)}</section>;
}

const REQUIRED_PRINT_FIELDS = new Set<PrintField>(["recipeName", "adjustedFeedFormula", "finalMass", "totalMass"]);

function syntheticSummary(index: number): WeighingSummary {
  const formulas = ["Ti", "Al", "C", "TiC"];
  return {
    title: `Representative carbide ${index + 1}`, sourceStatus: "Synthetic print preview", adjustedFeedFormula: "(TiVNbMo)4AlC2.7", targetFormula: "(TiVNbMo)4AlC3", idealFormula: "(TiVNbMo)4AlC3", intendedFeedFormula: "(TiVNbMo)4AlC2.7", realizedFormula: "(TiVNbMo)4AlC2.6998",
    batchMass: "5.000", batchBasis: "ideal-product-mass", totalMass: "5.184", unit: "g", actionRequiredMessages: index === 0 ? ["Review the carbon-deficient intended feed before weighing."] : [], minorAdvisoryMessages: ["Representative advisory for layout testing."], engineVersion: "preview", atomicWeightDataVersion: "preview", radiusSites: [{ siteId: "M", siteLabel: "M site", datasetName: "Representative radius data", datasetDefinition: "metallic radius", datasetVersion: "preview", vacancyFraction: "0", available: true, mismatchPercent: "4.2", missingElements: [], occupants: [] }],
    verificationSummary: { statusLabel: "Arithmetic verification: verified", targetFormulaMoles: "0.0123", largestElementalResidual: "C 0.000001 mol", atomicDataVersion: "preview" }, isHistorical: false, isStale: false,
    precursors: formulas.map((formula, row) => ({ id: `${index}-${formula}`, displayName: formula, formula, molarQuantity: row === 3 ? "1/3" : "1", solverMolarQuantity: row === 3 ? "0.333333333333" : "1", solverMolarQuantityExact: row === 3 ? "1/3" : "1", hasPostSolverAdjustment: false, finalMass: ["1.245", "0.702", "0.468", "2.769"][row]!, purityPercent: row === 3 ? "99.5" : "100", molarMass: ["47.867", "26.9815385", "12.011", "59.878"][row]!, atomicRadius: row === 0 ? "147 pm · metallic" : "Not applicable", unit: "g", status: "OK" })),
  };
}

function PrintPreview({ value }: { value: PrintSettings }) {
  const job = useMemo(() => createPrintJob({ kind: "library", title: "Live settings preview", singleRecipeDetailed: false, settings: value, entries: Array.from({ length: value.recipesPerPage }, (_, index): PrintableRecipeEntry => ({ id: `preview-${index}`, summary: syntheticSummary(index) })) }), [value]);
  const label = `${value.paperSize === "letter" ? "US Letter" : "A4"} · ${value.orientation === "portrait" ? "Portrait" : "Landscape"} · ${value.recipesPerPage} recipes per page · ${value.density.replace("-", " ")}`;
  return <div className="mt-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{label}</strong><button className="rounded border px-3 py-2 text-sm font-semibold" onClick={() => launchPrintJob(job)} type="button">Print this preview</button></div><div aria-label={`${value.recipesPerPage} recipes per page print preview`} className="print-settings-preview mt-3 overflow-auto rounded border bg-slate-200 p-3"><PrintDocument job={job} preview /></div></div>;
}

function PrintSettingsEditor({ value, onChange }: { value: PrintSettings; onChange: (value: PrintSettings) => void }) {
  const setField = (field: PrintField, checked: boolean) => onChange({ ...value, fields: { ...value.fields, [field]: checked } });
  const select = <K extends "paperSize" | "orientation" | "density" | "formulaStyle" | "warningDetail" | "verificationDetail">(field: K, next: PrintSettings[K]) => onChange({ ...value, [field]: next });
  return <section aria-labelledby="print-settings-heading" className="mt-6 border-t pt-5"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="text-lg font-semibold" id="print-settings-heading">Print settings</h3><p className="text-sm">Presentation-only settings for dedicated print sheets. Local backups include them; recipes and scientific snapshots do not.</p></div><button className="rounded border px-3 py-2 text-sm font-semibold" onClick={() => onChange(createRecommendedPrintSettings())} type="button">Restore recommended print defaults</button></div>
    <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      <label className="text-sm font-semibold">Paper size<select className="mt-1 min-h-10 w-full rounded border px-3" onChange={(event) => select("paperSize", event.target.value as PrintSettings["paperSize"])} value={value.paperSize}><option value="letter">US Letter</option><option value="a4">A4</option></select></label>
      <label className="text-sm font-semibold">Orientation<select className="mt-1 min-h-10 w-full rounded border px-3" onChange={(event) => select("orientation", event.target.value as PrintSettings["orientation"])} value={value.orientation}><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></label>
      <label className="text-sm font-semibold">Recipes per page<select className="mt-1 min-h-10 w-full rounded border px-3" onChange={(event) => onChange({ ...value, recipesPerPage: Number(event.target.value) as 2 | 4 | 6 })} value={value.recipesPerPage}><option value="2">2</option><option value="4">4</option><option value="6">6</option></select></label>
      <label className="text-sm font-semibold">Density<select className="mt-1 min-h-10 w-full rounded border px-3" onChange={(event) => select("density", event.target.value as PrintSettings["density"])} value={value.density}><option value="comfortable">Comfortable</option><option value="compact">Compact</option><option value="ultra-compact">Ultra-compact</option></select></label>
      <label className="text-sm font-semibold">Formula display<select className="mt-1 min-h-10 w-full rounded border px-3" onChange={(event) => select("formulaStyle", event.target.value as PrintSettings["formulaStyle"])} value={value.formulaStyle}><option value="adjusted-feed-only">Adjusted feed only</option><option value="target-and-adjusted">Target and adjusted feed</option><option value="all-formulas">All formulas</option></select></label>
      <label className="text-sm font-semibold">Warning detail<select className="mt-1 min-h-10 w-full rounded border px-3" onChange={(event) => select("warningDetail", event.target.value as PrintSettings["warningDetail"])} value={value.warningDetail}><option value="action-required-only">Action-required only</option><option value="action-and-minor">Action-required and minor</option><option value="all">All calculation details</option></select></label>
      <label className="text-sm font-semibold">Notes inclusion<select className="mt-1 min-h-10 w-full rounded border px-3" onChange={(event) => { const notesMode = event.target.value as PrintSettings["notesMode"]; onChange({ ...value, notesMode, fields: { ...value.fields, notes: notesMode !== "none" } }); }} value={value.notesMode}><option value="none">No notes</option><option value="selected">Selected notes</option><option value="furnace-and-processing">Furnace and processing</option><option value="all">All notes</option></select></label>
      <label className="text-sm font-semibold">Verification detail<select className="mt-1 min-h-10 w-full rounded border px-3" onChange={(event) => select("verificationDetail", event.target.value as PrintSettings["verificationDetail"])} value={value.verificationDetail}><option value="status">Overall status</option><option value="status-and-largest-residual">Status and largest residual</option><option value="compact-table">Compact table (2-up)</option></select></label>
    </div>
    <fieldset className="mt-5"><legend className="font-semibold">Printed fields</legend><p className="text-xs text-slate-600">Required identity, feed, weighing mass, and total fields are locked on.</p><div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{(Object.keys(PRINT_FIELD_LABELS) as PrintField[]).map((field) => { const required = REQUIRED_PRINT_FIELDS.has(field) || (field === "precursorName" && !value.fields.precursorFormula) || (field === "precursorFormula" && !value.fields.precursorName); return <label className="flex items-center gap-2 rounded border p-2 text-sm" key={field}><input checked={value.fields[field]} disabled={required} onChange={(event) => setField(field, event.target.checked)} type="checkbox" />{PRINT_FIELD_LABELS[field]}{required && <span className="text-xs text-slate-500">required</span>}</label>; })}</div></fieldset>
    <fieldset className="mt-5"><legend className="font-semibold">Page metadata</legend><div className="mt-2 flex flex-wrap gap-4">{([["showPageNumbers", "Page numbers"], ["showPrintDate", "Print date"], ["showApplicationName", "Application name"], ["repeatTableHeaders", "Repeat table headers"]] as const).map(([field, label]) => <label className="flex items-center gap-2 text-sm" key={field}><input checked={value[field]} onChange={(event) => onChange({ ...value, [field]: event.target.checked })} type="checkbox" />{label}</label>)}</div></fieldset>
    <div className="mt-5"><h4 className="font-semibold">Live print preview</h4><p className="text-xs text-slate-600">This is the same page component, printable model, field logic, typography, and paginator used by the dedicated print view. No chemistry calculation is run.</p><div className="mt-2 flex gap-2" role="tablist" aria-label="Recipes per page preview">{([2, 4, 6] as const).map((count) => <button aria-selected={value.recipesPerPage === count} className={`rounded border px-3 py-2 text-sm ${value.recipesPerPage === count ? "bg-slate-900 text-white" : ""}`} key={count} onClick={() => onChange({ ...value, recipesPerPage: count, density: count === 2 ? "comfortable" : count === 4 ? "compact" : "ultra-compact" })} role="tab" type="button">{count} per page</button>)}</div><PrintPreview value={value} /></div>
  </section>;
}

export function UserSettingsPanel({ repositories, onStatus }: { repositories: LocalDataRepositories; onStatus: (message: string) => void }) {
  const { preference, setPreference } = useTheme();
  const [settings, setSettings] = useState<LocalUserSettings>();
  const [error, setError] = useState("");
  useEffect(() => { let active = true; void repositories.getSettings().then((value) => { if (active) setSettings(value); }).catch((reason) => onStatus(`Settings unavailable: ${reason instanceof Error ? reason.message : "local database error"}`)); return () => { active = false; }; }, [onStatus, repositories]);
  if (!settings) return <section className="rounded border bg-white p-4 lg:col-span-2"><h2 className="text-lg font-semibold">User settings</h2><p>Loading local settings…</p></section>;
  const patchFeed = (patch: Partial<LocalUserSettings["feedDefaults"]>) => setSettings({ ...settings, feedDefaults: { ...settings.feedDefaults, ...patch } });
  const save = async () => { const current = { ...settings, appearance: preference }; const errors = validateUserSettings(current); if (errors.length) { setError(errors.join(" ")); return; } setError(""); await repositories.saveSettings(current); const stored = await repositories.getSettings(); setSettings(stored); onStatus("Settings saved locally and will apply to new calculations and current display preferences."); };
  const resetDisplay = () => { const defaults = createDefaultUserSettings(); setSettings({ ...settings, resultDisplay: defaults.resultDisplay }); onStatus("Display settings restored in the editor. Save settings to keep this change."); };
  const resetAll = async () => { if (!window.confirm("Reset all MAXCalc user settings? Recipes, routes, notes, snapshots, and layouts will not be deleted.")) return; const defaults = await repositories.resetSettings(); setSettings(defaults); setError(""); onStatus("All user settings reset. Scientific records and layouts were unchanged."); };
  const field = (id: string, label: string, value: string, onChange: (value: string) => void, helper: string) => <label className="block text-sm font-semibold" htmlFor={id} key={id}>{label}<input aria-describedby={`${id}-help`} className="mt-1 min-h-10 w-full rounded border px-3 font-mono" id={id} inputMode="decimal" onChange={(event) => onChange(event.target.value)} value={value} /><span className={`mt-1 block text-xs ${validatePositiveDecimal(value) ? "text-red-800" : "text-slate-600"}`} id={`${id}-help`}>{validatePositiveDecimal(value) ?? helper}</span></label>;
  return <section className="rounded border bg-white p-4 lg:col-span-2" aria-labelledby="user-settings-heading"><h2 className="text-xl font-bold" id="user-settings-heading">Local user settings</h2><p className="mt-1 text-sm">One versioned IndexedDB record controls starting defaults and presentation. Saved recipes, routes, and historical snapshots keep their stored values.</p>
    <section className="mt-5" aria-labelledby="appearance-heading"><h3 className="text-lg font-semibold" id="appearance-heading">Appearance</h3><p className="mt-1 text-sm">Dark is neutral charcoal; Midnight is near-black and line-oriented. System follows your operating-system Light/Dark preference without replacing the saved System selection.</p><label className="mt-3 block max-w-xl text-sm font-semibold">Appearance<select className="mt-1 min-h-10 w-full rounded border px-3" onChange={(event) => { const appearance = event.target.value as AppearancePreference; setSettings({ ...settings, appearance }); void setPreference(appearance); }} value={preference}><option value="light">Light</option><option value="dark">Dark</option><option value="midnight">Midnight</option><option value="system">Use system setting</option></select></label></section>
    <section className="mt-5" aria-labelledby="feed-defaults-heading"><h3 className="text-lg font-semibold" id="feed-defaults-heading">Formula and feed defaults</h3><div className="mt-3 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{field("default-aluminum", "Default aluminum per formula", settings.feedDefaults.aluminumPerFormula, (value) => patchFeed({ aluminumPerFormula: value }), "Used as the starting Al feed coefficient for new compatible calculations.")}{(["211", "312", "413"] as const).map((template) => field(`default-carbon-${template}`, `${template} carbon per formula`, settings.feedDefaults.carbonPerFormula[template], (value) => patchFeed({ carbonPerFormula: { ...settings.feedDefaults.carbonPerFormula, [template]: value } }), validatePositiveDecimal(settings.feedDefaults.carbonPerFormula[template]) ? `Ideal template value: ${{ "211": 1, "312": 2, "413": 3 }[template]}` : `Ideal template value: ${{ "211": 1, "312": 2, "413": 3 }[template]} · ${relativeTemplateCarbonLabel(template, settings.feedDefaults.carbonPerFormula[template])}`))}</div><p className="mt-3 text-xs">Precedence: saved or historical recipe → explicit saved route or example → user default → system fallback. Carbon defaults apply only to new pure-carbide 211/312/413 templates, never nitrides or explicit mixed C/N sites.</p></section>
    <section className="mt-6" aria-labelledby="save-behavior-heading"><h3 className="text-lg font-semibold" id="save-behavior-heading">Save behavior</h3><label className="mt-2 block max-w-xl text-sm font-semibold">Default Save action<select className="mt-1 min-h-10 w-full rounded border px-3" onChange={(event) => setSettings({ ...settings, saveBehavior: { defaultPostSaveAction: event.target.value as LocalUserSettings["saveBehavior"]["defaultPostSaveAction"] } })} value={settings.saveBehavior.defaultPostSaveAction}><option value="save">Save</option><option value="save-and-blank">Save and start new blank recipe</option><option value="save-and-copy">Save and open a copy of the current recipe</option></select></label><p className="mt-1 text-xs">The main Save action and Enter use this default. The split menu always retains all three actions, and navigation waits for a successful transaction.</p></section>
    <section className="mt-6" aria-labelledby="weighing-display-heading"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-lg font-semibold" id="weighing-display-heading">Weighing-results display</h3><p className="text-sm">Final mass and precursor identity protections are enforced.</p></div><button className="rounded border px-3 py-2 text-sm font-semibold" onClick={resetDisplay} type="button">Reset this section</button></div><label className="mt-3 block max-w-xl text-sm font-semibold">Elemental atomic-radius dataset<select className="mt-1 min-h-10 w-full rounded border px-3" onChange={(event) => setSettings({ ...settings, resultDisplay: { ...settings.resultDisplay, atomicRadiusDatasetId: event.target.value } })} value={settings.resultDisplay.atomicRadiusDatasetId}><option value="">No dataset selected</option>{DEFAULT_ATOMIC_RADIUS_REGISTRY.usableDatasets.map((dataset) => <option key={dataset.datasetId} value={dataset.datasetId}>{dataset.name} · {dataset.definition} · {dataset.datasetVersion}</option>)}</select></label><div className="mt-4 grid gap-4 xl:grid-cols-2"><DisplayEditor mode="standard" onChange={(value) => setSettings({ ...settings, resultDisplay: { ...settings.resultDisplay, standard: value } })} value={settings.resultDisplay.standard} /><DisplayEditor mode="advanced" onChange={(value) => setSettings({ ...settings, resultDisplay: { ...settings.resultDisplay, advanced: value } })} value={settings.resultDisplay.advanced} /></div><div className="mt-4 grid gap-4 xl:grid-cols-2"><Preview datasetId={settings.resultDisplay.atomicRadiusDatasetId} display={settings.resultDisplay.standard} mode="standard" /><Preview datasetId={settings.resultDisplay.atomicRadiusDatasetId} display={settings.resultDisplay.advanced} mode="advanced" /></div></section>
    <section className="mt-6 border-t pt-5" aria-labelledby="account-sync-settings-heading"><h3 className="text-lg font-semibold" id="account-sync-settings-heading">Account and sync</h3><p className="mt-1 text-sm">Signed-in accounts synchronize automatically in the foreground. Local changes remain durable while offline or signed out.</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{([
      ["automaticSync", "Automatic synchronization"],
      ["syncOnStartup", "Sync when MAXCalc starts"],
      ["syncAfterLocalChanges", "Sync after local changes"],
      ["syncOnReconnect", "Sync after reconnecting"],
      ["syncOnFocus", "Check when returning to MAXCalc"],
      ["remoteChangeNotifications", "Listen for changes from other devices"],
      ["routineSuccessNotifications", "Show routine success notifications"],
    ] as const).map(([key, label]) => <label className="flex items-center gap-2 rounded border p-3 text-sm" key={key}><input checked={settings.cloudSync[key]} onChange={(event) => setSettings({ ...settings, cloudSync: { ...settings.cloudSync, [key]: event.target.checked } })} type="checkbox" />{label}</label>)}</div><label className="mt-3 flex items-center gap-2 rounded border border-amber-400 p-3 text-sm font-semibold"><input checked={settings.cloudSync.paused} onChange={(event) => setSettings({ ...settings, cloudSync: { ...settings.cloudSync, paused: event.target.checked } })} type="checkbox" />Pause synchronization until resumed</label></section>
    <PrintSettingsEditor onChange={(print) => setSettings({ ...settings, print })} value={settings.print} />
    <section className="mt-6 border-t pt-4" aria-labelledby="settings-data-heading"><h3 className="text-lg font-semibold" id="settings-data-heading">Data and reset</h3><p className="mt-1 text-sm">Full verified backups include this settings record. Ordinary recipe CSV and JSON exports do not.</p>{error && <p aria-live="assertive" className="mt-3 rounded bg-red-50 p-3 text-sm font-semibold text-red-900">{error}</p>}<div className="mt-3 flex flex-wrap gap-2"><button className="rounded bg-teal-800 px-4 py-2 font-semibold text-white" onClick={() => void save()} type="button">Save settings</button><button className="rounded border border-red-400 px-4 py-2 font-semibold text-red-900" onClick={() => void resetAll()} type="button">Reset all settings…</button></div></section>
  </section>;
}
