import "fake-indexeddb/auto";
import { afterEach, describe, expect, it } from "vitest";
import { MaxStoichDatabase } from "../../lib/persistence/database";
import { XRDReferenceRepository } from "../../lib/xrd/references";
import type { CalculatedXRDPattern, ExperimentalXRDMeasurement, RawXRDArtifact } from "../../lib/xrd/schemas";
import { XRDMeasurementRepository } from "../../lib/xrd/persistence";

const databases: MaxStoichDatabase[] = [], cif = "data_Si\n_cell_length_a 5.43\n_cell_length_b 5.43\n_cell_length_c 5.43\n";
async function hash(value: string) { return [...new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)))].map((v)=>v.toString(16).padStart(2,"0")).join(""); }
async function pattern(): Promise<CalculatedXRDPattern> { const sha=await hash(cif); return { schemaVersion:"1.0.0", reference:{sourceType:"user-cif",sourceId:"silicon.cif",formula:"Si",phaseName:"Silicon",spaceGroup:"Fd-3m",crystalSystem:"cubic",publication:null,doi:null,referenceStatus:"theoretical",retrievedAt:"2026-09-25T00:00:00Z",sourceRevision:null,cifSha256:sha,sourceUrl:null}, radiation:{kind:"preset",label:"Cu Kα",wavelengthAngstrom:1.54184}, twoThetaRange:{minDeg:10,maxDeg:90}, lattice:{aAngstrom:5.43,bAngstrom:5.43,cAngstrom:5.43,alphaDeg:90,betaDeg:90,gammaDeg:90}, crystalSystem:"cubic",spaceGroup:"Fd-3m",reflections:[{twoThetaDeg:28.4,relativeIntensity:100,dAngstrom:3.13,hkls:[{h:1,k:1,l:1,multiplicity:8}]}],calculationProvenance:{engine:"pymatgen.XRDCalculator",engineVersion:"test",serviceVersion:"test",calculatedAt:"2026-09-25T00:00:00Z",inputCifSha256:sha},cifContent:cif}; }
function db() { const database=new MaxStoichDatabase(`xrd-references-${crypto.randomUUID()}`);databases.push(database);return database; }
afterEach(async()=>{while(databases.length){const database=databases.pop()!;database.close();await database.delete();}});

describe("versioned XRD reference library",()=>{
  it("saves exact CIF content, detects duplicate content, and reopens offline",async()=>{const database=db(), repository=new XRDReferenceRepository(database), calculated=await pattern();const first=await repository.createStructure({pattern:calculated,cifText:cif});const second=await repository.createStructure({pattern:calculated,cifText:cif,displayName:"Intentional second entry"});expect(second.duplicates).toHaveLength(1);database.close();const reopened=new MaxStoichDatabase(database.name);databases.push(reopened);const saved=await new XRDReferenceRepository(reopened).get(first.reference.referenceId);expect(saved?.revision.payload.kind).toBe("STRUCTURE");if(saved?.revision.payload.kind==="STRUCTURE")expect(saved.revision.payload.cifText).toBe(cif);});
  it("imports a validated portable bundle under a new identity without overwriting",async()=>{const database=db(),repository=new XRDReferenceRepository(database),saved=await repository.createStructure({pattern:await pattern(),cifText:cif});const imported=await repository.importBundle(repository.exportBundle(saved.reference,saved.revision));expect(imported.reference.referenceId).not.toBe(saved.reference.referenceId);expect(await database.xrdReferences.count()).toBe(2);if(imported.revision.payload.kind==="STRUCTURE")expect(imported.revision.payload.cifSha256).toBe(saved.revision.cifSha256);});
  it("creates immutable validation revisions",async()=>{const database=db(),repository=new XRDReferenceRepository(database),created=await repository.createStructure({pattern:await pattern(),cifText:cif});const revised=await repository.revise(created.reference.referenceId,{validationStatus:"REVIEWED"},"Independent review completed","VALIDATION");expect(revised.revisionNumber).toBe(2);expect((await repository.revisions(created.reference.referenceId)).map((r)=>r.validationStatus)).toEqual(["REVIEWED","UNREVIEWED"]);});
  it("promotes a measurement without duplicating arrays and preserves raw lineage",async()=>{const database=db(),sha="b".repeat(64),artifactId=`xrd-artifact-sha256-${sha}`,raw:RawXRDArtifact={schemaVersion:"1.0.0",artifactId,originalFilename:"sample.xy",byteLength:7,mimeType:"text/plain",sha256:sha,importedAt:"2026-09-25T00:00:00Z",sourceMetadata:null};const measurement:ExperimentalXRDMeasurement={schemaVersion:"1.0.0",measurementId:"m1",rawArtifactId:artifactId,rawArtifactSha256:sha,sourceFilename:"sample.xy",importedAt:"2026-09-25T00:00:00Z",sampleName:"Sample",maxcalcSampleId:null,acquisitionMetadata:{radiationSourceName:"Cu Kα",wavelengthAngstrom:1.54184,instrumentManufacturer:null,instrumentModel:null,scanDate:null,operator:null,sampleName:"Sample",notes:null},parserProvenance:{schemaVersion:"1.0.0",parserId:"maxcalc.generic-delimited-text",parserVersion:"1.0.0",detectedFormat:"text",detectionConfidence:"high",textEncoding:"utf-8",delimiter:"whitespace",decimalConvention:"period",headerRows:0,commentPrefixes:[],twoThetaColumn:{index:0,name:null},intensityColumn:{index:1,name:null},userOverrides:{},warnings:[],serviceVersion:"test"},twoThetaDeg:[10,11],intensity:[100,200],characterization:{pointCount:2,minTwoThetaDeg:10,maxTwoThetaDeg:11,minIntensity:100,maxIntensity:200,allValuesFinite:true,ordering:"strictly-increasing",duplicateTwoThetaCount:0,medianSpacingDeg:1,spacingVariationDeg:0,rejectedNumericalRowCount:0},validationStatus:"valid",validationIssues:[]};await new XRDMeasurementRepository(database).save(raw,new Blob(["10 100\n"]),measurement);const saved=await new XRDReferenceRepository(database).createEmpirical({measurementId:"m1",displayName:"LMSL Sample",formula:"Ti3AlC2",wavelengthAngstrom:1.54184});expect(saved.revision.rawArtifactSha256).toBe(sha);expect("twoThetaDeg" in saved.revision.payload).toBe(false);});
  it("blocks deletion when an exact reference revision has Stage 4 descendants",async()=>{const database=db(),repository=new XRDReferenceRepository(database),saved=await repository.createStructure({pattern:await pattern(),cifText:cif});await database.xrdReferenceMatchingResults.add({id:"matching-child",parentPeakAnalysisId:"p",parentProcessedRepresentationId:"r",parentMeasurementId:"m",referenceCifSha256:saved.revision.cifSha256!,rawArtifactSha256:"c".repeat(64),createdAt:"2026-09-25T00:00:00Z",result:{libraryReference:{referenceId:saved.reference.referenceId,revisionId:saved.revision.revisionId,revisionNumber:1}}} as never);await expect(repository.remove(saved.reference.referenceId)).rejects.toThrow(/Deprecate/);});
  it("creates a scientific revision when an empirical structure association changes",async()=>{const database=db(),repository=new XRDReferenceRepository(database),structure=await repository.createStructure({pattern:await pattern(),cifText:cif});const sha="d".repeat(64),artifactId=`xrd-artifact-sha256-${sha}`,raw:RawXRDArtifact={schemaVersion:"1.0.0",artifactId,originalFilename:"x.xy",byteLength:4,mimeType:null,sha256:sha,importedAt:"2026-09-25T00:00:00Z",sourceMetadata:null},measurement={schemaVersion:"1.0.0",measurementId:"m2",rawArtifactId:artifactId,rawArtifactSha256:sha,sourceFilename:"x.xy",importedAt:"2026-09-25T00:00:00Z",sampleName:null,maxcalcSampleId:null,acquisitionMetadata:{radiationSourceName:null,wavelengthAngstrom:1.54184,instrumentManufacturer:null,instrumentModel:null,scanDate:null,operator:null,sampleName:null,notes:null},parserProvenance:{schemaVersion:"1.0.0",parserId:"maxcalc.generic-delimited-text",parserVersion:"1.0.0",detectedFormat:"text",detectionConfidence:"high",textEncoding:"utf-8",delimiter:"whitespace",decimalConvention:"period",headerRows:0,commentPrefixes:[],twoThetaColumn:{index:0,name:null},intensityColumn:{index:1,name:null},userOverrides:{},warnings:[],serviceVersion:"test"},twoThetaDeg:[1,2],intensity:[3,4],characterization:{pointCount:2,minTwoThetaDeg:1,maxTwoThetaDeg:2,minIntensity:3,maxIntensity:4,allValuesFinite:true,ordering:"strictly-increasing",duplicateTwoThetaCount:0,medianSpacingDeg:1,spacingVariationDeg:0,rejectedNumericalRowCount:0},validationStatus:"valid",validationIssues:[]} satisfies ExperimentalXRDMeasurement;await new XRDMeasurementRepository(database).save(raw,new Blob(["1 3\n"]),measurement);const empirical=await repository.createEmpirical({measurementId:"m2",displayName:"Empirical",formula:"Si",wavelengthAngstrom:1.54184});if(empirical.revision.payload.kind!=="EMPIRICAL")throw new Error("fixture");const linked=await repository.revise(empirical.reference.referenceId,{payload:{...empirical.revision.payload,associatedStructure:{referenceId:structure.reference.referenceId,revisionId:structure.revision.revisionId,revisionNumber:1}}},"Associated reviewed structure","SCIENTIFIC");expect(linked.revisionNumber).toBe(2);expect((await repository.getRevision(empirical.revision.revisionId))?.payload.kind).toBe("EMPIRICAL");});
});
