import "fake-indexeddb/auto";
import { strToU8, unzipSync, zipSync } from "fflate";
import { afterEach, describe, expect, it } from "vitest";
import { MaxStoichDatabase } from "../../lib/persistence/database";
import { braggTwoThetaDeg, cubicDSpacing, dSpacingFromTwoTheta, hexagonalDSpacing, refinementScientificStatuses, XRD_RADIATION_PRESETS } from "../../lib/xrd/conventions";
import { XRDAnalysisRepository, XRDMeasurementRepository } from "../../lib/xrd/persistence";
import { exportXrdProjectPackage, importXrdProjectPackage } from "../../lib/xrd/project-package";
import { createXrdPublicationFigureSpec, parseXrdFigureSpec, renderXrdPublicationSvg, serializeXrdFigureSpec, xrdFigureRasterPixels, xrdPublicationCsv } from "../../lib/xrd/publication";
import type { ExperimentalXRDMeasurement, RawXRDArtifact } from "../../lib/xrd/schemas";
import { defaultProcessingConfig, type ProcessedXRDRepresentation, type XRDPeakAnalysis } from "../../lib/xrd/stage3";

const databases: MaxStoichDatabase[] = [], provenance = { serviceVersion:"test",pythonVersion:"3.12",numpyVersion:"2",scipyVersion:"1",pybaselinesVersion:"1",lmfitVersion:"1" };
async function hash(value: string) { return [...new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)))].map((v)=>v.toString(16).padStart(2,"0")).join(""); }
async function fixture() { const text="10 1\n11 4\n12 2\n", sha=await hash(text), artifactId=`xrd-artifact-sha256-${sha}`; const raw:RawXRDArtifact={schemaVersion:"1.0.0",artifactId,originalFilename:"golden.xy",byteLength:new TextEncoder().encode(text).length,mimeType:"text/plain",sha256:sha,importedAt:"2026-09-25T00:00:00Z",sourceMetadata:null}; const measurement:ExperimentalXRDMeasurement={schemaVersion:"1.0.0",measurementId:"m1",rawArtifactId:artifactId,rawArtifactSha256:sha,sourceFilename:"golden.xy",importedAt:raw.importedAt,sampleName:"Golden",maxcalcSampleId:null,acquisitionMetadata:{radiationSourceName:"Cu Kα1",wavelengthAngstrom:1.54056,instrumentManufacturer:null,instrumentModel:null,scanDate:null,operator:null,sampleName:"Golden",notes:null},parserProvenance:{schemaVersion:"1.0.0",parserId:"maxcalc.generic-delimited-text",parserVersion:"1.0.0",detectedFormat:"text",detectionConfidence:"high",textEncoding:"utf-8",delimiter:"whitespace",decimalConvention:"period",headerRows:0,commentPrefixes:[],twoThetaColumn:{index:0,name:null},intensityColumn:{index:1,name:null},userOverrides:{},warnings:[],serviceVersion:"test"},twoThetaDeg:[10,11,12],intensity:[1,4,2],characterization:{pointCount:3,minTwoThetaDeg:10,maxTwoThetaDeg:12,minIntensity:1,maxIntensity:4,allValuesFinite:true,ordering:"strictly-increasing",duplicateTwoThetaCount:0,medianSpacingDeg:1,spacingVariationDeg:0,rejectedNumericalRowCount:0},validationStatus:"valid",validationIssues:[]}; const processed:ProcessedXRDRepresentation={schemaVersion:"1.0.0",processedRepresentationId:"p1",parentMeasurementId:"m1",rawArtifactSha256:sha,createdAt:"2026-09-25T00:01:00Z",processingConfig:defaultProcessingConfig,twoThetaDeg:[10,11,12],rawIntensity:[1,4,2],estimatedBaseline:null,baselineCorrectedIntensity:null,smoothedIntensity:null,analysisIntensity:[1,4,2],transformationOrder:["raw"],warnings:[],diagnostics:{baselineAlgorithm:null,converged:null,iterationCount:null,finalTolerance:null},scientificProvenance:provenance}; const analysis:XRDPeakAnalysis={schemaVersion:"1.0.0",peakAnalysisId:"a1",revision:1,parentProcessedRepresentationId:"p1",parentMeasurementId:"m1",rawArtifactSha256:sha,createdAt:"2026-09-25T00:02:00Z",detectionConfig:{schemaVersion:"1.0.0",minimumProminence:1,minimumHeight:null,minimumDistanceDeg:null,minimumWidthDeg:null,maximumWidthDeg:null},fittingConfig:{schemaVersion:"1.0.0",localBackground:"linear",minimumWindowDeg:.4,maximumWindowDeg:3,widthMultiplier:4,maximumGroupPeaks:3,centerBoundDeg:.3,minimumFwhmDeg:.01,maximumFwhmDeg:2},candidatePeaks:[],fittedPeaks:[],fitGroups:[],excludedCandidateIds:[],manualEdits:[],warnings:[],scientificProvenance:provenance}; return {text,raw,measurement,processed,analysis}; }
function db(){const value=new MaxStoichDatabase(`xrd-stage6-${crypto.randomUUID()}`);databases.push(value);return value;} afterEach(async()=>{while(databases.length){const value=databases.pop()!;value.close();await value.delete();}});

describe("XRD scientific conventions",()=>{it("uses exact named wavelengths and independent Bragg conversions",()=>{expect(XRD_RADIATION_PRESETS.CuKa.wavelengthAngstrom).toBe(1.54184);expect(XRD_RADIATION_PRESETS.CuKa1.wavelengthAngstrom).toBe(1.54056);const d=cubicDSpacing(5.431,1,1,1),angle=braggTwoThetaDeg(d,1.54056);expect(dSpacingFromTwoTheta(angle,1.54056)).toBeCloseTo(d,12);expect(hexagonalDSpacing(3.075,18.58,0,0,2)).toBeCloseTo(9.29,12);});});
describe("XRD scientific status",()=>{it("does not equate optimizer completion with a well-constrained result",()=>{expect(refinementScientificStatuses({diagnostics:{optimizerSuccess:true,rank:1,parameterCount:2,degreesOfFreedom:0,rmsDeltaTwoThetaDeg:.4,covariance:null},warnings:[]})).toEqual(["underdetermined","high-residual","covariance-unavailable"]);});});

describe("portable XRD project",()=>{it("round-trips immutable source arrays and remaps all local identities",async()=>{const source=db(),f=await fixture(),measurements=new XRDMeasurementRepository(source),analyses=new XRDAnalysisRepository(source);await measurements.save(f.raw,new Blob([f.text]),f.measurement,"Golden");await analyses.saveProcessed(f.processed);await analyses.saveAnalysis(f.analysis);const archive=await exportXrdProjectPackage(source,{peakAnalysisId:"a1",projectName:"Golden project",applicationVersion:"test"});const target=db(),result=await importXrdProjectPackage(target,archive),measurement=await target.xrdMeasurements.get(result.measurementId),processed=await target.xrdProcessedRepresentations.get(result.processedRepresentationId),peak=await target.xrdPeakAnalyses.get(result.peakAnalysisId);expect(result.measurementId).not.toBe("m1");expect(measurement?.measurement.twoThetaDeg).toEqual([10,11,12]);expect(processed?.representation.analysisIntensity).toEqual([1,4,2]);expect(peak?.analysis.parentProcessedRepresentationId).toBe(result.processedRepresentationId);expect((await target.xrdRawArtifacts.get(measurement!.rawArtifactId))?.sha256).toBe(f.raw.sha256);});it("rejects a package whose hashed content was changed",async()=>{const source=db(),f=await fixture(),measurements=new XRDMeasurementRepository(source),analyses=new XRDAnalysisRepository(source);await measurements.save(f.raw,new Blob([f.text]),f.measurement);await analyses.saveProcessed(f.processed);await analyses.saveAnalysis(f.analysis);const files=unzipSync(await exportXrdProjectPackage(source,{peakAnalysisId:"a1",projectName:"Golden",applicationVersion:"test"}));files["records/peaks.json"]=strToU8("{}\n");await expect(importXrdProjectPackage(db(),zipSync(files))).rejects.toThrow(/integrity check failed/);});});

describe("XRD publication output",()=>{it("persists display transformations without mutating scientific arrays and emits vector-only SVG",async()=>{const f=await fixture(),data={measurement:f.measurement,processed:f.processed,peaks:f.analysis,measurementLabel:"Golden"},initial=createXrdPublicationFigureSpec(data),spec={...initial,layers:{...initial.layers,measured:true,processed:true},display:{...initial.display,measuredNormalization:"max-100" as const,measuredOffset:20}},before=[...f.measurement.intensity],svg=renderXrdPublicationSvg(spec,data);expect(parseXrdFigureSpec(serializeXrdFigureSpec(spec))).toEqual(spec);expect(f.measurement.intensity).toEqual(before);expect(svg).toContain('data-layer="experimental"');expect(svg).not.toContain("<image");expect(xrdPublicationCsv(spec,data)).toContain("max-100");});it("converts required physical dimensions exactly",async()=>{const f=await fixture(),initial=createXrdPublicationFigureSpec({measurement:f.measurement,measurementLabel:"Golden"});expect(xrdFigureRasterPixels({...initial,geometry:{...initial.geometry,width:3.5,height:2.5,unit:"in",dpi:300}})).toEqual({width:1050,height:750});expect(xrdFigureRasterPixels({...initial,geometry:{...initial.geometry,width:3.5,height:2.5,unit:"in",dpi:600}})).toEqual({width:2100,height:1500});expect(xrdFigureRasterPixels({...initial,geometry:{...initial.geometry,width:7,height:4.5,unit:"in",dpi:600}})).toEqual({width:4200,height:2700});expect(xrdFigureRasterPixels({...initial,geometry:{...initial.geometry,width:88.9,height:63.5,unit:"mm",dpi:300}})).toEqual({width:1050,height:750});});});
