import { z } from "zod";
import { physicalSizeInInches, type FigureLengthUnit } from "../emi/publication-figure";
import type { ExperimentalXRDMeasurement } from "./schemas";
import type { ProcessedXRDRepresentation, XRDPeakAnalysis } from "./stage3";
import type { XRDReferenceMatchingResult, XRDLatticeRefinementResult } from "./stage4";
import type { CalculatedXRDPattern } from "./schemas";

export const XRD_FIGURE_SCHEMA_VERSION = "1.0.0" as const;
export interface XRDPublicationFigureSpec {
  readonly schemaVersion: typeof XRD_FIGURE_SCHEMA_VERSION; readonly rendererVersion: "maxcalc-xrd-svg-1"; readonly id: string; readonly name: string;
  readonly sources: { readonly measurementId: string; readonly rawArtifactSha256: string; readonly processedRepresentationId: string | null; readonly peakAnalysisId: string | null; readonly referenceRevisionId: string | null; readonly referenceCifSha256: string | null; readonly matchingResultId: string | null; readonly refinementId: string | null };
  readonly geometry: { readonly width: number; readonly height: number; readonly unit: FigureLengthUnit; readonly dpi: number; readonly background: "white" | "transparent"; readonly margin: { readonly top: number; readonly right: number; readonly bottom: number; readonly left: number } };
  readonly text: { readonly title: string; readonly titleVisible: boolean; readonly subtitle: string; readonly subtitleVisible: boolean; readonly panelLabel: string; readonly panelLabelVisible: boolean };
  readonly typography: { readonly family: string; readonly axisTitlePt: number; readonly tickPt: number; readonly legendPt: number; readonly annotationPt: number; readonly titlePt: number };
  readonly axes: { readonly xMinimum: number | null; readonly xMaximum: number | null; readonly xMajorTick: number | null; readonly yVisible: boolean; readonly yLabel: string; readonly lineWidthPt: number };
  readonly layers: { readonly measured: boolean; readonly processed: boolean; readonly fittedPeakCenters: boolean; readonly fittedComponents: boolean; readonly referenceSticks: boolean; readonly hklLabels: "none" | "matched" | "strongest-n" | "manual"; readonly strongestN: number; readonly manualReflectionIndices: readonly number[]; readonly hiddenReflectionIndices: readonly number[] };
  readonly display: { readonly measuredNormalization: "none" | "max-100"; readonly processedNormalization: "none" | "max-100"; readonly measuredOffset: number; readonly processedOffset: number; readonly referenceOffset: number; readonly referenceStickHeight: number; readonly referenceStickWidthPt: number; readonly hklFontSizePt: number; readonly hklRotationDeg: number };
  readonly styles: { readonly measuredColor: string; readonly processedColor: string; readonly referenceColor: string; readonly fittedColor: string; readonly measuredWidthPt: number; readonly processedWidthPt: number };
  readonly export: { readonly includeFigureSpec: true; readonly includePlottedCsv: true };
}

const color = z.string().regex(/^#[0-9a-f]{6}$/i);
const specSchema: z.ZodType<XRDPublicationFigureSpec> = z.object({
  schemaVersion: z.literal(XRD_FIGURE_SCHEMA_VERSION), rendererVersion: z.literal("maxcalc-xrd-svg-1"), id: z.string(), name: z.string().min(1),
  sources: z.object({ measurementId: z.string(), rawArtifactSha256: z.string().regex(/^[a-f0-9]{64}$/), processedRepresentationId: z.string().nullable(), peakAnalysisId: z.string().nullable(), referenceRevisionId: z.string().nullable(), referenceCifSha256: z.string().nullable(), matchingResultId: z.string().nullable(), refinementId: z.string().nullable() }),
  geometry: z.object({ width: z.number().positive(), height: z.number().positive(), unit: z.enum(["in", "mm", "cm", "px"]), dpi: z.number().int().min(72).max(2400), background: z.enum(["white", "transparent"]), margin: z.object({ top: z.number().nonnegative(), right: z.number().nonnegative(), bottom: z.number().nonnegative(), left: z.number().nonnegative() }) }),
  text: z.object({ title: z.string(), titleVisible: z.boolean(), subtitle: z.string(), subtitleVisible: z.boolean(), panelLabel: z.string(), panelLabelVisible: z.boolean() }),
  typography: z.object({ family: z.string(), axisTitlePt: z.number().positive(), tickPt: z.number().positive(), legendPt: z.number().positive(), annotationPt: z.number().positive(), titlePt: z.number().positive() }),
  axes: z.object({ xMinimum: z.number().nullable(), xMaximum: z.number().nullable(), xMajorTick: z.number().positive().nullable(), yVisible: z.boolean(), yLabel: z.string(), lineWidthPt: z.number().positive() }),
  layers: z.object({ measured: z.boolean(), processed: z.boolean(), fittedPeakCenters: z.boolean(), fittedComponents: z.boolean(), referenceSticks: z.boolean(), hklLabels: z.enum(["none", "matched", "strongest-n", "manual"]), strongestN: z.number().int().min(1).max(100), manualReflectionIndices: z.array(z.number().int().nonnegative()), hiddenReflectionIndices: z.array(z.number().int().nonnegative()) }),
  display: z.object({ measuredNormalization: z.enum(["none", "max-100"]), processedNormalization: z.enum(["none", "max-100"]), measuredOffset: z.number(), processedOffset: z.number(), referenceOffset: z.number(), referenceStickHeight: z.number().positive(), referenceStickWidthPt: z.number().positive(), hklFontSizePt: z.number().positive(), hklRotationDeg: z.number().min(-90).max(90) }),
  styles: z.object({ measuredColor: color, processedColor: color, referenceColor: color, fittedColor: color, measuredWidthPt: z.number().positive(), processedWidthPt: z.number().positive() }), export: z.object({ includeFigureSpec: z.literal(true), includePlottedCsv: z.literal(true) }),
}).superRefine((value, context) => { if (value.axes.xMinimum !== null && value.axes.xMaximum !== null && value.axes.xMinimum >= value.axes.xMaximum) context.addIssue({ code: "custom", path: ["axes"], message: "X minimum must be less than X maximum." }); });

export interface XRDPublicationData { readonly measurement: ExperimentalXRDMeasurement; readonly processed?: ProcessedXRDRepresentation; readonly peaks?: XRDPeakAnalysis; readonly reference?: CalculatedXRDPattern; readonly matching?: XRDReferenceMatchingResult; readonly refinement?: XRDLatticeRefinementResult; readonly measurementLabel: string; readonly referenceLabel?: string }

export function createXrdPublicationFigureSpec(data: XRDPublicationData): XRDPublicationFigureSpec {
  return { schemaVersion: XRD_FIGURE_SCHEMA_VERSION, rendererVersion: "maxcalc-xrd-svg-1", id: crypto.randomUUID(), name: `${data.measurementLabel} XRD`,
    sources: { measurementId: data.measurement.measurementId, rawArtifactSha256: data.measurement.rawArtifactSha256, processedRepresentationId: data.processed?.processedRepresentationId ?? null, peakAnalysisId: data.peaks?.peakAnalysisId ?? null, referenceRevisionId: data.matching?.libraryReference?.revisionId ?? null, referenceCifSha256: data.reference?.reference.cifSha256 ?? null, matchingResultId: data.matching?.matchingResultId ?? null, refinementId: data.refinement?.refinementId ?? null },
    geometry: { width: 3.5, height: 2.5, unit: "in", dpi: 600, background: "white", margin: { top: 42, right: 16, bottom: 44, left: 54 } },
    text: { title: `${data.measurementLabel} XRD`, titleVisible: false, subtitle: "", subtitleVisible: false, panelLabel: "(a)", panelLabelVisible: false }, typography: { family: "Arial, Helvetica, sans-serif", axisTitlePt: 9, tickPt: 8, legendPt: 7, annotationPt: 7, titlePt: 10 },
    axes: { xMinimum: null, xMaximum: null, xMajorTick: null, yVisible: true, yLabel: "Intensity (a.u.)", lineWidthPt: .75 },
    layers: { measured: !data.processed, processed: Boolean(data.processed), fittedPeakCenters: false, fittedComponents: false, referenceSticks: Boolean(data.reference), hklLabels: "none", strongestN: 8, manualReflectionIndices: [], hiddenReflectionIndices: [] },
    display: { measuredNormalization: "none", processedNormalization: "none", measuredOffset: 0, processedOffset: 0, referenceOffset: 0, referenceStickHeight: 18, referenceStickWidthPt: .8, hklFontSizePt: 6, hklRotationDeg: -90 },
    styles: { measuredColor: "#111111", processedColor: "#0072b2", referenceColor: "#d55e00", fittedColor: "#009e73", measuredWidthPt: 1, processedWidthPt: 1.1 }, export: { includeFigureSpec: true, includePlottedCsv: true } };
}

export function xrdFigureRasterPixels(spec: XRDPublicationFigureSpec): { width: number; height: number } { return { width: Math.round(physicalSizeInInches(spec.geometry.width, spec.geometry.unit) * spec.geometry.dpi), height: Math.round(physicalSizeInInches(spec.geometry.height, spec.geometry.unit) * spec.geometry.dpi) }; }
export function serializeXrdFigureSpec(spec: XRDPublicationFigureSpec): string { return JSON.stringify(specSchema.parse(spec), null, 2); }
export function parseXrdFigureSpec(text: string): XRDPublicationFigureSpec { let value: unknown; try { value = JSON.parse(text); } catch { throw new Error("XRD figure configuration is not valid JSON."); } return specSchema.parse(value); }
const xml = (value: string) => value.replace(/[&<>"']/g, (item) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&apos;" }[item]!));
const normalize = (values: readonly number[], mode: "none" | "max-100") => { if (mode === "none") return [...values]; const max = Math.max(...values.map(Math.abs)); return max > 0 ? values.map((value) => value / max * 100) : values.map(() => 0); };
const unitSuffix = (unit: FigureLengthUnit) => unit === "px" ? "" : unit;

export function renderXrdPublicationSvg(specInput: XRDPublicationFigureSpec, data: XRDPublicationData): string {
  const spec = specSchema.parse(specInput), width = Math.max(1, Math.round(physicalSizeInInches(spec.geometry.width, spec.geometry.unit) * 96)), height = Math.max(1, Math.round(physicalSizeInInches(spec.geometry.height, spec.geometry.unit) * 96));
  const { left, right, top, bottom } = spec.geometry.margin, plotWidth = width-left-right, plotHeight = height-top-bottom;
  const allX = data.measurement.twoThetaDeg, minX = spec.axes.xMinimum ?? Math.min(...allX), maxX = spec.axes.xMaximum ?? Math.max(...allX), x = (value: number) => left + (value-minX)/(maxX-minX)*plotWidth;
  const series: { name: string; x: readonly number[]; y: number[]; color: string; width: number }[] = [];
  if (spec.layers.measured) series.push({ name: `${data.measurementLabel} — measured`, x: data.measurement.twoThetaDeg, y: normalize(data.measurement.intensity, spec.display.measuredNormalization).map((value) => value+spec.display.measuredOffset), color: spec.styles.measuredColor, width: spec.styles.measuredWidthPt });
  if (spec.layers.processed && data.processed) series.push({ name: `${data.measurementLabel} — processed`, x: data.processed.twoThetaDeg, y: normalize(data.processed.analysisIntensity, spec.display.processedNormalization).map((value) => value+spec.display.processedOffset), color: spec.styles.processedColor, width: spec.styles.processedWidthPt });
  const visibleY = series.flatMap((item) => item.y.filter((_, index) => item.x[index]! >= minX && item.x[index]! <= maxX)); const minY = Math.min(...visibleY, 0), maxY = Math.max(...visibleY, 1), y = (value: number) => top+plotHeight-(value-minY)/(maxY-minY || 1)*plotHeight;
  const path = (sx: readonly number[], sy: readonly number[]) => sx.map((value, index) => `${index ? "L" : "M"}${x(value).toFixed(3)} ${y(sy[index]!).toFixed(3)}`).join(" ");
  const parts = [`<svg xmlns="http://www.w3.org/2000/svg" width="${spec.geometry.width}${unitSuffix(spec.geometry.unit)}" height="${spec.geometry.height}${unitSuffix(spec.geometry.unit)}" viewBox="0 0 ${width} ${height}" data-maxcalc-xrd-figure-schema="${spec.schemaVersion}">`, `<rect width="100%" height="100%" fill="${spec.geometry.background === "white" ? "#fff" : "none"}"/>`, `<g font-family="${xml(spec.typography.family)}" fill="#111">`];
  if (spec.text.titleVisible) parts.push(`<text x="${width/2}" y="${spec.typography.titlePt+4}" font-size="${spec.typography.titlePt}pt" text-anchor="middle">${xml(spec.text.title)}</text>`);
  parts.push(`<path d="M${left} ${top}V${top+plotHeight}H${left+plotWidth}" fill="none" stroke="#111" stroke-width="${spec.axes.lineWidthPt}"/>`);
  const tick = spec.axes.xMajorTick ?? (maxX-minX)/4; for (let value = Math.ceil(minX/tick)*tick; value <= maxX+tick*1e-9; value += tick) parts.push(`<path d="M${x(value)} ${top+plotHeight}v4" stroke="#111"/><text x="${x(value)}" y="${top+plotHeight+15}" font-size="${spec.typography.tickPt}pt" text-anchor="middle">${Number(value.toPrecision(8))}</text>`);
  parts.push(`<text x="${left+plotWidth/2}" y="${height-5}" font-size="${spec.typography.axisTitlePt}pt" text-anchor="middle">2θ (degrees)</text>`); if (spec.axes.yVisible) parts.push(`<text x="12" y="${top+plotHeight/2}" font-size="${spec.typography.axisTitlePt}pt" text-anchor="middle" transform="rotate(-90 12 ${top+plotHeight/2})">${xml(spec.axes.yLabel)}</text>`);
  for (const item of series) parts.push(`<path d="${path(item.x, item.y)}" fill="none" stroke="${item.color}" stroke-width="${item.width}" vector-effect="non-scaling-stroke" data-layer="experimental"/>`);
  if (spec.layers.referenceSticks && data.reference) for (const [index, reflection] of data.reference.reflections.entries()) if (reflection.twoThetaDeg >= minX && reflection.twoThetaDeg <= maxX) { const base = top+plotHeight-spec.display.referenceOffset, stick = spec.display.referenceStickHeight*reflection.relativeIntensity/100; parts.push(`<path d="M${x(reflection.twoThetaDeg)} ${base}V${base-stick}" stroke="${spec.styles.referenceColor}" stroke-width="${spec.display.referenceStickWidthPt}" vector-effect="non-scaling-stroke" data-layer="reference-stick"/>`); const selected = spec.layers.hklLabels === "manual" ? spec.layers.manualReflectionIndices.includes(index) : spec.layers.hklLabels === "strongest-n" ? [...data.reference.reflections].sort((a,b)=>b.relativeIntensity-a.relativeIntensity).slice(0,spec.layers.strongestN).includes(reflection) : spec.layers.hklLabels === "matched" ? data.matching?.proposedMatches.some((match)=>match.accepted&&match.referenceReflectionId===`reflection-${index}`) : false; if (selected && !spec.layers.hiddenReflectionIndices.includes(index)) { const label = reflection.hkls.map((item)=>`(${item.h} ${item.k} ${item.l})`).join("/"); const stagger = index % 3 * (spec.display.hklFontSizePt+2); parts.push(`<text x="${x(reflection.twoThetaDeg)}" y="${base-stick-3-stagger}" font-size="${spec.display.hklFontSizePt}pt" fill="${spec.styles.referenceColor}" text-anchor="start" transform="rotate(${spec.display.hklRotationDeg} ${x(reflection.twoThetaDeg)} ${base-stick-3-stagger})">${xml(label)}</text>`); } }
  if (spec.layers.fittedPeakCenters && data.peaks) for (const peak of data.peaks.fittedPeaks) if (peak.included && peak.fittedCenterTwoThetaDeg !== null) parts.push(`<circle cx="${x(peak.fittedCenterTwoThetaDeg)}" cy="${top+6}" r="2.5" fill="${spec.styles.fittedColor}" data-layer="fitted-peak"/>`);
  if (spec.text.panelLabelVisible) parts.push(`<text x="${left}" y="${top}" font-size="${spec.typography.titlePt}pt" font-weight="bold">${xml(spec.text.panelLabel)}</text>`); parts.push("</g></svg>"); return parts.join("");
}

export function xrdPublicationCsv(spec: XRDPublicationFigureSpec, data: XRDPublicationData): string {
  const rows = [["series", "two_theta_deg", "display_intensity", "display_transformation", "visual_offset"]]; const add = (name: string, x: readonly number[], values: readonly number[], normalization: "none"|"max-100", offset: number) => normalize(values, normalization).forEach((value, index) => rows.push([name, String(x[index]), String(value+offset), normalization, String(offset)]));
  if (spec.layers.measured) add("measured", data.measurement.twoThetaDeg, data.measurement.intensity, spec.display.measuredNormalization, spec.display.measuredOffset); if (spec.layers.processed && data.processed) add("processed", data.processed.twoThetaDeg, data.processed.analysisIntensity, spec.display.processedNormalization, spec.display.processedOffset); if (spec.layers.referenceSticks && data.reference) data.reference.reflections.forEach((item) => rows.push(["reference-stick", String(item.twoThetaDeg), String(item.relativeIntensity), "calculated-relative-0-100", String(spec.display.referenceOffset)])); return `${rows.map((row)=>row.join(",")).join("\r\n")}\r\n`;
}
